patternfly/patternfly-org

source/get-started/contribute/index.md
Not necessary to include what’s new text. removing redundancy.
=> Got rid of the What's New text on the Contribute page

source/get-started/index.html
Usage and Examples - There's a typo "Usages guidelines" (Usage
guidelines")
Design - There's a typo "guildelines" (guidelines)
Design  - There's a typo "difference" (different)
Usability Tests  - There's a typo "to the results" (of the results)
Code  - There's a typo "flexibilities" (flexibility)
Community  - There's a typo in "Connet" (Connect)
=> Typo and Grammar Corrections on Getting Started Page

source/_includes/nav-tabs-code.html, source/pattern-library/application-framework/login-page/index.md
Fix for issue #89 
Renamed code tab from "Angular-PatternFly" to "AngularJS".
Added missing nav for login code page.
=> Renamed code tab to "AngularJS".

source/_whats-news/2015-11-19.md, source/_whats-news/2015-12-04.md, source/_whats-news/2015-12-07.md, source/_whats-news/2015-12-08.md, source/_whats-news/2015-12-14.md, source/_whats-news/2015-12-22.md, source/_whats-news/2016-01-19.md, source/_whats-news/2016-01-21.md, source/_whats-news/2016-01-24.md, source/_whats-news/2016-02-02.md, source/_whats-news/2016-02-15.md, source/_whats-news/2016-02-26.md, source/_whats-news/2016-02-29.md, source/_whats-news/2016-03-01.md, source/_whats-news/2016-03-02.md, source/_whats-news/2016-03-04.md, source/_whats-news/2016-03-17.md, source/_whats-news/2016-04-27.md, source/_whats-news/2016-04-28.md, source/_whats-news/2016-04-29.md, source/_whats-news/2016-05-10.md, source/_whats-news/2016-05-25.md, source/whats-new/index.html
Updated all the what's new posts for this year and up to November 5, 2015. There are older posts, but not certain we need all that or if it's even relevant for the new site? It's time consuming to add each post to it's own file, fix the broken links, etc.
By default, we're only showing the last 3 posts on the home page. If you click on the view more link, it was only showing the last 10; although, I changed that to 50.
=> Updated all the posts for what's new

source/styles/terminology-and-wording/index.md, source/styles/typography/index.md
Added missing “Links” and "Common Terms and Words” sections to /styles/terminology-and-wording
=> Added missing “Links” and "Common Terms and Words” sections

source/pattern-library/forms-and-controls/forms/index.md
@dlabrecq It solves #105 
We don't need to show the css, its just for our website to show the modal. This snippet is not meant to be use in production.
=> Removes css from modal example

source/_less/patternfly-site.less
Widgets: Copy link is out of place #110
Widgets: pretty print example has the copy link #112
=> Fixed copy button for pretty print examples

source/pattern-library/communication/about-modal/index.md, source/pattern-library/communication/notification-drawer/index.md
New PatternFly site: PatternFly Modal Design page - link goes to old site #119
New PatternFly site: Notification Drawer Design page - link goes to old site #121
New PatternFly site: Notification Drawer Design page - Misspelled word #122
=> Fixed broken links.

source/pattern-library/forms-and-controls/field-level-help/index.md
Form level help example is broken #104
=> Gave form level help example more room to prevent icon wrapping.

source/styles/color-palette/index.md
Green, blue, and gold under secondary colors codes had typos.
Cherry-picked commit from @kybaker (i.e., PR #199).
=> Fix typos on the lists

README.md
patternfly-org is already integrated with TravisCI, this PR just adds a badge to the README.md file.
=> Added TravisCI badge to README.md

bower.json, source/_config.yml, source/_includes/widgets, source/get-started/frequently-asked-questions/index.md
Patternfly changed the tests-src directory. The widgets directory is now located in tests/pages/_includes/widgets.
=> Modified paths to patternfly widgets.

bower.json
Travis build won't complete until a "suitable version" of patternfly is selected -- angular-patternfly is using an older version.
=> Travis build needs to pick a "suitable version" of patternfly

source/get-started/frequently-asked-questions/index.md
The previous work on adding the migration guides left remnants of the merges. This PR fixes those.
=> remove merge comments from markdown page, which render on patternfly.org

source/pattern-library/communication/inline-notifications/index.md, source/pattern-library/communication/toast-notifications/index.md
Addresses #259 by showing the Angular code for Inline Notifications on the [Inline Notifications](https://www.patternfly.org/pattern-library/communication/inline-notifications/#/_code) page and hide the same code on the [Toast Notifications](https://www.patternfly.org/pattern-library/communication/toast-notifications/#/_code) page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/patternfly/patternfly-org/261)
=> Move Angular code for Inline Notifications to correct page.

.travis.yml, scripts/publish.sh
Description
Now that developers are building their own dist directories via Travis, we no longer want the email property set in travis.yml. Currently, all build notifications are being sent to patternfly-build@redhat.com, even for personal forks. The committer/author should be notified when building their own repos, not patternfly-build@redhat.com.
Removed global email
Created a valid user in GitHub for committing dist changes.
Now GitHub shows dist commits by a valid user patternfly-build with email patternfly-build@redhat.com.
=> Removed global email.

source/pattern-library/communication/notification-drawer/index.md, source/pattern-library/communication/notification-drawer/notification-drawer-horizontal-nav.html, source/pattern-library/communication/notification-drawer/notification-drawer-vertical-nav.html
- Added Live example for Notification Drawer for Horizontal Nav in Code Tab.
- Updated Overwiew tab replacing images with live examples for Horizontal and Vertical Nav.
- Fixed "kebab" typo in Design tab.
- Renamed title in code tab to "Notification Drawer for Vertical Navigation" to keep consistency with patternfly.
- Renamed file to notification-drawer-vertical-nav.html to keep consistence with file in patternfly.
=> PTNFLY-1462 Add live example for Notification Drawer for Horizontal Nav.

source/get-started/setup/index.md
On the "Setting Up PatternFly" page, the bower install command was missing the npm bit.
=> fix type on bower install command on patternfly setup page

source/pattern-library/content-views/list-view/index.md
Fix for a bug Liz B. encountered on pf.org, where the ListView code example (variant # 1) show donut charts located off the page.
The first problem is that the chart IDs have been omitted. However, once the IDs are added, the charts appear off the page. Therefore, this fix also depends on setting the chart width. See PR https://github.com/patternfly/patternfly/pull/472
Changes
Set the width of donut charts in list view example
This is an image from pf.org:
=> ListView example shows donut charts incorrectly

source/pattern-library/forms-and-controls/toolbar/index.md
Fix for issue #293.
Problem is that the javascript was inside the toolbar.html, that was being imported twice. Thus, the duplicated javascript was not working.
I removed the javascript from the toolbar.html and added it to the page code.
This depends on an update in patternfly project.
=> Find dropdown is not opening in Toolbar component #293

source/_config.yml
This changes the address of the bug on the menu removing the s on `https` for the blog link.
=> solves bug on the menu with the link to the blog

source/_includes/header.html, source/_includes/menu-node.html, source/_plugins/pf_jekyll_pattern_libraries.rb
In this PR I've introduced a jekyll plugin that scans the `site.pages` to dynamically create the _pattern-library_ menu items for the site.
The plugin executes and the menus are generated on every build.  No special action is required to enable this functionality.  Simply run: `grunt serve`
=> Introduce a static menu generator

Gruntfile.js, package.json, source/_includes/code/cards/aggregate-status-card/code.md, source/_includes/code/cards/utilization-bar-card/code.md, source/_includes/code/cards/utilization-trend-card/code.md, source/_includes/code/data-visualization/area-chart/code.md, source/_includes/code/data-visualization/bar-chart/code.md, source/_includes/code/data-visualization/donut-chart/code.md, source/_includes/code/data-visualization/line-chart/code.md, source/_includes/code/data-visualization/pie-chart/code.md, source/_includes/code/data-visualization/sparkline/code.md, source/_includes/code/data-visualization/utilization-bar-chart/code.md, source/_includes/code/navigation/horizontal-navigation/code.md, source/_includes/code/navigation/vertical-navigation/code.md, source/_includes/head.html, source/pattern-library/widgets/index.md
This PR introduces a change where the component dependencies are copied from node_modules rather than bower_components.  This makes it unnecessary to run `bower install` before building the site.
Please review @dlabrecq
=> Copied the component dependencies from node_modules rather than bower_components

source/styles/icons/index.md
There is an offending line in our site CSS that positions the table overtop of the paragraph, so the padding of the table obscures the links and captures the click events.  This PR introduces a style tag into the page to overcome this bug.  A proper treatment of the underlying CSS problem will be followed up on in a PTNFLY story.
cc: @jennyhaines @LHinson
=> A CSS hack to fix the tables that were covering the links

source/assets/js/patternfly-site.js
Fix for URL handling in Pattern Library.
jQuery requires special characters in quotes, i.e. `a[href="#api"]`, instead of just `a[href=#api]` (which doesn't work and unlike other situations throws an error).
=> fix jQuery selector

README.md
original readme has "grunt serve" to start up the server and it should be "grunt server"
=> fixed typo in readme.me

package.json, source/get-started/setup/index.md
Corrected typo and added correct path for setting up patternfly page using npm. This would close #426
=> Fixing incorrect code sample for npm

source/_less/patternfly-site.less
Added a z-index to navbar to fix date picker year issue which would close #388 and #361 
I also played around in dev tools with moving the top to 70px for the date picker since it was absolute positioned but that would put it too close to the "Reference Markup" text and it would need to be moved over more to the right in that case. 
Can you please review @bleathem and @andresgalante :)
=> Date picker year behind navbar z-index fix

source/pattern-library/widgets/index.md
Hi, mkrajnak noticed that there is an old link for bootstrap-combobox github repo in patternfly website. I think it should be updated to this one. https://github.com/patternfly/patternfly-org/issues/386
=> replace the old link to new link (bootstrap-combobox )

source/community/monthly-community-meeting/index.md
Updated the community meetings page to include link to the agenda for the next PF-R community meeting.
=> Included agenda for PR-R community meeting

source/_includes/code/application-framework/launcher/code.md, source/_less/patternfly-site.less
CSS in ng-docs.css was causing the issue noted in #451 related to the logo. I found that the horizontal nav example had additional css to fix this. I added the same class `example-navbar`, and then included additional css for this class to fix the display within the vertical nav as well.
=> Includes css to overwrite ng-docs.css for app launcher

source/community/monthly-community-meeting/index.md
I moved meeting info for the PatternFly-ng and PatternFly-React meetings to the Prior Meetings section, and included a link to slides and recording for the React meeting.
I chatted with @catrobson about posting contents for the pf-ng meeting, and she will add that later, so I left those table cells empty for now.
=> Updated community meeting page for PF-R

README.md
This will avoid running into a problem where the target is `undefined`
e.g.
```
Running "serve:undefined" (serve) task
....
Running "jekyll:undefined" (jekyll) task
Verifying property jekyll.undefined exists in config...ERROR
>> Unable to process task.
Warning: Required config property "jekyll.undefined" missing. Use --force to continue.
```
=> 📝 Fix the `grunt serve` command example

source/get-started/setup/index.md
I found a tiny typo in Setting Up PatternFly page. It's a trivial but beginners may stumble at this by their copy&paste first trial.
Thank you!
=> Fix PatternFly JS URL in setup page

source/community/monthly-community-meeting/index.md
I updated the community meeting page to include links to slides and the recording for the Jan 2018 patternfly-react community meeting.
=> Update meeting page for recent pf-r meeting

source/_includes/code/navigation/horizontal-navigation/code.md, source/_includes/header.html
* normalize spelling of "dropdown"
* add white space to "Widgets" in the left/burger menu so it aligns with the rest of the links
=> dropdown misspelling and space around "Widgets" in left nav

source/_layouts/page-pattern.html
Making a second update to change the image path from ```/img/icon-code-clear.svg"``` to ```/assets/img/icon-code-clear.svg"``` in order to show the icon for when there is no pf-core code available.
Note:
#509 contained the wrong path needed to render the icon on to pf-org
=> Updating the img path for the icon when no pf-core code available

source/pattern-library/index.md
removing these thumbnails to remove 404 link errors. Soon this page will be replaced with the design status page so didn’t bother updating to ensure all tiles match the patterns published.
Closes #418
=> Update overview pattern page

source/assets/js/patternfly-site.js
This PR is targeted to fix issue - https://github.com/patternfly/patternfly-org/issues/474
Please review the [Demo page](https://rawgit.com/dabeng/patternfly-org/info-tip-dist/_site/pattern-library/widgets/#info-tip) to confirm conflict resolution.
=> fix(info tip): Info tip .navbar-toggle also toggles the site's navbar

Gruntfile.js, package.json, source/_less/patternfly-site.less, source/pattern-library/index.md
Populating the Pattern Library Overview page with the design status page table. 
https://patternfly.atlassian.net/browse/PTNFLY-2669 and fixes: #489 based off the design.
[view here](https://rawgit.com/amarie401/patternfly-org/design-status-overview-dist/_site/pattern-library/)
* fetching data from design-status.json
* populating jquery data table with `design-status.json`
* searching data table for pattern name
* modifying css for table
Tried to match the design as closely as I could. In the design, the table and search are centered on the page, was having some trouble replicating that in css. Was able to center the table but not the search input. Any idea on how I can go about centering everything from a css standpoint or if I need to restructure my html @matthewcarleton ?  
Is it a …
=> Populating pf-org overview page with design status page

source/_includes/head.html, source/_less/patternfly-site.less, source/pattern-library/index.md
This PR introduces enhancements to the current pattern overview table and fixes #544 and fixes #543 
* Each pattern name now links to it's corresponding overview page.
* Incorporating pf filters and dataTables to filter/search by name and category. 
[Pattern Library Overview](https://rawgit.com/amarie401/patternfly-org/overview-table-dist/_site/pattern-library/)
=> enhancements to pattern overview table

source/_includes/code/navigation/context-selector/code.md, source/pattern-library/navigation/context-selector/context-selector-vertical-nav.html
Related to this jira story: https://patternfly.atlassian.net/browse/PTNFLY-2786
and this issue: https://github.com/patternfly/patternfly-design/issues/589
Changes introduced:
1. ~~Creating a `doc.md` file for dev notes (which will also need to be included as a variable (`code_doc` in the design repo in a separate PR)~~ Dev notes can be added in a separate PR.
2. Include `contextselector: true` to the current vertical navigation on patternfly and add that to `code.md` file example as an iframe.
* [Preview](https://rawgit.com/amarie401/patternfly-org/context-selector-example-dist/_site/pattern-library/navigation/context-selector/#code)
Issues/Questions: 
1. The navbar brand logo for pf disappears when `contextselector:true` is present. I think it may have something to with this part of the …
=> Adding context selector example to pf-org

source/_includes/code/application-framework/login-page/doc.md
Update the login docs to account for the use of `.login-pf` and applying it to a page's `<body>` element
fixes https://github.com/patternfly/patternfly-org/issues/553
=> fix(login): Update login docs

package.json
* This PR updates the package.json of bootstrap-select to lock in version 1.12.2. The patternfly-org build updated the version to 1.13.1 even though the package.json is using 1.12.2 which was causing issues with the styling and breaking. 
This will fix the styling/breaking issues for the bootstrap select, context-selector, and other example components that are using bootstrap-select as a dependency.
Since core is currently using version 1.12.2 it will be better not to update to 1.13.1 at this time for consistency.
Fixes #555 
* package.json
=> Update package.json of bootstrap-select to lock in version 1.12.2

source/index.html
This PR introduces a fix to the dead link/404 page error for the downloads page and replaces it with a new path to repositories page.
Related to this issue: #560
=> fix dead link for download page and replace with new repositories page

source/pattern-library/widgets/index.md
This PR is targeted to fix issue #495
However, bootstrapswitch.com is also broken, we should use latest bootstrapswitch.site
@dgutride Please review this PR whenever you get the chance 😊
=> fix(link): Bootstrap-switch link is broken

source/get-started/community/index.md, source/get-started/index.html
Community page has been updated this fixes #565 
- update text to include link to the community meeting page
- update community link under get-started page to fix broken page.
=> updated community page text and link

Gruntfile.js
I've refactored the icon table in patternfly-design (patternfly/patternfly-design#677), this will be required for it to take effect if the PR gets merged.
=> feat(icons) consume icons.json from patternfly-design

source/get-started/index.html
**Current result:**
```html
there are a number of 
<a href="https://www.patternfly.org/get-started/our-repos/">
PatternFly JS framework implementations</a> 
available.
```
**Expected result:**
Link should point to https://www.patternfly.org/get-started/repositories/
=> fix 404 broken link to get-started/repositories

source/_includes/code/navigation/horizontal-navigation/code.md
This PR is targeted to fix issue #598 
Here's the [demo page](https://rawgit.com/dabeng/patternfly-org/dist-two-level/_site/pattern-library/navigation/horizontal-navigation/#code).
@LHinson @amarie401 Could you review this PR when you have time ?
=> chore(navigation): Remove two-level menu bar code example

source/_includes/code/navigation/pagination/code.md
This PR adds the pagination example to the website
Rawgit: [here](https://rawgit.com/amarie401/patternfly-org/pagination-dist/_site/pattern-library/navigation/pagination/#code)
fixes #643
=> add pagination example to site

packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/lists-and-tables/design.md
As per a question that came up, I added a sentence describing that column headers should align with the content (aka if your content is center aligned, center align the header as well). 
Open to suggestions of where it could go - I didn't include a lot of detail because there was already a lot going on in that list item.
=> Adding content about header alignment

packages/patternfly-4/src/components/footer/footer.js, packages/patternfly-4/src/components/footer/footer.scss, packages/patternfly-4/src/images/aboutPF4Lines.svg, packages/patternfly-4/src/pages/index.js, packages/patternfly-4/src/pages/styles.scss, packages/patternfly-4/src/workspace.scss
Updates to the homepage based off of reviews.
- Adjust positioning of the individual SVG elements on in-between screen sizes
- Fix background image bleed when resizing the screen
- Apply a solid background on smaller screen to eliminate visual clutter and improve load times
- Set inline SVGs to use `<object>` inside of empty `<div>` containers
- Fix footer wrapping on smaller screens
=> fix(homepage): update homepage from reviews

packages/patternfly-4/src/components/_core/Documentation/SideNav.js, packages/patternfly-4/src/components/_react/Documentation/SideNav.js, packages/patternfly-4/src/components/layout.js, packages/patternfly-4/src/components/switcher/index.js, packages/patternfly-4/src/pages/index.js, packages/patternfly-4/src/styles/_animation.scss, packages/patternfly-4/src/styles/_homepage.scss, packages/patternfly-4/src/styles/_navigation.scss, packages/patternfly-4/src/styles/_variables.scss, packages/patternfly-4/src/workspace.scss
Update the horizontal and vertical navigations to match the latest designs. Changes include:
- change active/hover/focus styling of navigation items
- add extra margin/spacing to elements in order to improve readability
- update font weights and sizes to improve readability
- remove hamburger menu on screen sizes above 768px, add back in when screen is below 768px wide
**Desktop**
**Mobile (nav closed)**
**Mobile (nav open)**
=> fix(navigation): update navigations to match designs

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json
Updating 'design-guidelines-navigation.json' to add Empty state documentation recently merged.
=> Add Empty State to nav

packages/patternfly-4/_repos/react-core/src/components/BackgroundImage/BackgroundImage.md, packages/patternfly-4/_repos/react-core/src/components/LoginPage/LoginPage.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/PageLayout.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutDefaultNav.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutExpandableNav.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutGroupsNav.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutHorizontalNav.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutManualNav.md, packages/patternfly-4/_repos/react-core/src/demos/PageLayout/examples/PageLayoutSimpleNav.md
There now seems to be a problem loading the styles for the login and background image pages. The actual components are rendering, though. Not sure what started causing this.
=> fix(react-core): fullscreen previews

packages/patternfly-4/src/pages/index.js, packages/patternfly-4/src/styles/_homepage.scss
Remove the grey background from the 'About PatternFly' section on the home page.
Fixes issue https://github.com/patternfly/patternfly-org/issues/931
=> fix(homepage): remove grey from section background

packages/patternfly-4/src/components/_react/Documentation/styles.scss, packages/patternfly-4/src/styles/_navigation.scss, packages/patternfly-4/src/templates/template.scss
Sync the highlight styling of the expanded navigation between the Get started, Design guidelines, and Documentation sections.
Fixes issue https://github.com/patternfly/patternfly-org/issues/967
=> fix(nav): sync highlights over expanded nav

packages/patternfly-4/src/workspace.scss
=> fix clipboard copy styling

packages/patternfly-4/src/components/switcher/index.js
Fixes #812 
Fixes #965
(Duplicate issues)
This PR changes the framework switcher so that when it is rendered, it takes the current path and replaces `/core/` with `/react/` or vice versa, then checks to see if the result is a valid path. If so, the rendered link will take the user to the page matching their current component, otherwise it will still take them to the about modal page.
As long as the paths to our react and core component pages are consistently named, this should result in an intuitive framework toggle that can switch between frameworks without switching components.
=> Attempt to find matching component page when switching frameworks

packages/patternfly-4/content/design-guidelines/usage-and-behavior/forms/design.md
Fixes part of #966 
> CURRENT: Field labels can be aligned to the left or top of the field depending on the layout of your page and the amount of space you have to work with.
> CHANGE TO: Field labels can be aligned to the top or left of the field depending on the layout of your page and the amount of space you have to work with.
=> Forms text update

packages/patternfly-4/src/components/switcher/index.js
A lesson learned: always test your fix in a real build... whoops.
In https://github.com/patternfly/patternfly-org/pull/992 I didn't properly handle gatsby's prefixed paths, so it only worked in a dev server and not in a production build of the site. The graphql query returns paths like `/documentation/core/components/button` but the current path looks like `/v4/documentation/core/components/button`, so because of that `/v4/` nothing was ever matching and the `validReactPath` / `validCorePath` would always fall back to `aboutmodal`.
With this change, the path being verified must contain (rather than equal) the matching path from the query. I also changed the `glob` in the query to exclude `/documentation/core` and `/documentation/react` root paths, because otherwise every path would always …
=> Properly handle prefixed paths in framework switcher

packages/patternfly-4/src/components/_core/Documentation/styles.scss, packages/patternfly-4/src/components/css-variables.js, packages/patternfly-4/src/templates/template.scss
Close #863 close #989 close #955 close #969 close #937 close #935
- Quick update to styles to add `white-space: normal` to code blocks so that they break when inside of table data. 
- Add a modifier to the css variables table so that it breaks at a larger viewport. 
- update padding the for table at a medium viewport so that it is not as wide.
=> fix for tables

packages/patternfly-4/src/components/_core/Documentation/index.js, packages/patternfly-4/src/components/_react/Documentation/index.js, packages/patternfly-4/src/components/switcher/index.js, packages/patternfly-4/src/components/switcher/styles.scss, packages/patternfly-4/src/templates/mdxPF4Template.js, packages/patternfly-4/src/workspace.scss
- fixes Framework title size and spacing from top
- override padding in the page main section
=> fix framework size and padding for documentation

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json, packages/patternfly-4/content/design-guidelines/styles/colors-for-charts.md, packages/patternfly-4/content/design-guidelines/styles/colors.mdx, packages/patternfly-4/content/design-guidelines/usage-and-behavior/charts/design.md
Fixes the error we were getting when you click on "colors for charts" and "colors" remains selected.
=> update colors for charts name

packages/patternfly-4/src/pages/index.js
just needed to update the objects to divs because objects dont render in FF without proper capability.
=> fix firefox imgs on homepage

packages/patternfly-4/content/design-guidelines/styles/colors.mdx, packages/patternfly-4/src/styles/content/colors.scss
=> update blue colors

packages/patternfly-4/content/design-guidelines/styles/colors.mdx, packages/patternfly-4/src/styles/content/colors.scss, packages/patternfly-4/src/workspace.scss
Update the Colors page to properly render on mobile devices (smaller viewports). Set the column widths to be 12 columns on smaller screens, fixing the text/color block overlaps to occurred.
This PR also fixes the issue where the Sample Chart image appeared on smaller screens, injecting itself in the middle of the Chart Colors sample area.
fixes issue https://github.com/patternfly/patternfly-org/issues/983
Old screenshot | New screenshot
--- | ---
=> fix(colors): adjust mobile alignments for colors page

packages/patternfly-4/content/get-started/gettingstarted-design.md
Refined content on designers get started page:
1. Edited the link to match the newest one for PF4 symbol library (https://sketch.cloud/s/gb1ka)
2. Edited the content so it would no longer give a PF4 template in sketch assets
=> Content refinement for designers get started

packages/patternfly-4/src/components/layout.js, packages/patternfly-4/src/workspace.scss
Adjust the specificity of the Search styling, as the styles from the Search in the navigation affected the search in other pages (not intended).
This will be improved with the existing PR https://github.com/patternfly/patternfly-org/pull/1099.
=> fix(search): adjust specificity for Search styling

packages/patternfly-4/src/styles/_navigation.scss, packages/patternfly-4/src/styles/_search.scss
Update the Search styling to closer match designs.
- Improve the usability on smaller viewports by expanding the display width of the results dropdown.
- Improve padding around the results to increase clickable area (from around 25px to around 40px in height).
- Improve contrast of the Input Placeholder
- Shrink footprint of the Search input (width) so that it fits better in the navigation and does not sit right next to the PatternFly logo.
fixes Issues https://github.com/patternfly/patternfly-org/issues/755 and https://github.com/patternfly/patternfly-org/issues/904
----
**Desktop**
**Mobile**
----
=> fix(search): update styling for Search

packages/patternfly-4/src/pages/documentation/core/css-variables.js, packages/patternfly-4/src/pages/documentation/react/css-variables.js
close #1074 
@rachael-phillips I pulled in the markdown code styles into the CSS Variables file. Could you double check that the code styles should apply to all these words underneath too, they do have the `<code>` wrapper around them so they should be ok
=> make code consistent across site

packages/patternfly-4/content/documentation/avatar.md
Close #1130 
Commented out the Link to the Masthead as that page doesnt exist right now. Wondering if it should link to the "page" or "nav" components as they are probably closest to the masthead? cc: @stacymcauliffe
=> comment out broken link

packages/patternfly-4/content/design-guidelines/usage-and-behavior/lists-and-tables/design.md
The related Components and demos links on https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/lists-and-tables are broken. This change sets the destination page name to all lower case.
=> Fix broken links on Lists and Tables page

packages/patternfly-4/content/design-guidelines/usage-and-behavior/modal/design.md
Fixed 404 error when clicking on the "content guidelines" link in Modal Dialog. Now directs to the writing section of Content.
=> fix(link): link now working(1159)

packages/patternfly-4/content/design-guidelines/usage-and-behavior/alerts-and-notifications/design.md
Fixed the 404 error when clicking on the "message dialog design guidelines" link. Now directs to the Modal Dialogs page.
=> fix(link): link now working

packages/patternfly-4/content/design-guidelines/styles/icons.md, packages/patternfly-4/src/components/content/icons.js
closes #872 
@rachael-phillips @stacymcauliffe could you double check the copy and also the icon? The button links to the search input.
=> feat(icons): add empty state component to the icons page

packages/patternfly-4/content/get-started/getstarted-dev.md, packages/patternfly-4/src/components/_core/Documentation/styles.scss, packages/patternfly-4/src/components/_core/Example/styles.scss, packages/patternfly-4/src/templates/template.scss
=> fix(code): code now breaks responsively

packages/patternfly-4/src/components/css-variables.js, packages/patternfly-4/src/components/css-variables.scss
Fixes #1021 
Updates the table to break earlier using the new 2xl breakpoint from Core. Also changes the border colors on mobile to match the background-color, after speaking with Kyle
=> change color of border to match background

packages/patternfly-4/content/design-guidelines/usage-and-behavior/forms/design.md
1. Added note in General guidelines for labels to use sentence-style capitalization for all text elements
2. Fixed formatting in listed items (semi colon instead of -, and capitalized sentences after colon) for consistency. Had discussed this with Stacy last week.
Also note: do not have access to fixing the picture examples on the website
(so this fixes half of issue #1171 )
=> Fixes in Form tab of design guidelines

packages/patternfly-4/src/styles/_navigation.scss
close #1207 
Makes the nav buttons 100% height and overrides the top assignment to 0. Also change the padding in the nav link items so that the text inside aligns with the arrows in the tab scroll buttons.
=> fix nav buttons

packages/patternfly-4/package.json, packages/patternfly-4/src/components/ShadowDomPreview.js, yarn.lock
Fixes: https://github.com/patternfly/patternfly-react/issues/2335
`?shadow=false` appended to a URL turns off shadow DOM encapsulation for the examples.
=> turn off shadow dom with url param

packages/patternfly-4/src/components/css-variables.js, packages/patternfly-4/src/components/css-variables.scss
Fixed CSS variable search box a11y issues by adding label and changing color of border. closes #1302
=> fix(a11y): fix css variables search box (iss1302)

packages/patternfly-4/content/design-guidelines/styles/colors-for-charts.md
Added alt captions for two images on the page. closes #1293
=> fix(a11y): added captions for imgs(iss1293)

packages/patternfly-4/content/design-guidelines/usage-and-behavior/navigation-system/design.md
fix #1300 
The anchor link was pointing to an invalid ID
=> fix(a11y): fix navigation system link

packages/patternfly-4/src/templates/template.scss
=> fix(markdownTable): remove word break on code elements

packages/patternfly-4/src/components/_react/propsTable/propsTable.js
This is a possible quick fix to the property table issue https://github.com/patternfly/patternfly-org/issues/1468 by preventing word wrapping on the 1st, 2nd, and 4th columns.
=> Fix property table documentation wrapping

packages/patternfly-4/src/content/get-started/developers.md
fixed a11y issue: heading levels should only increase by one. closes #1301
=> fix(a11y): fixed a11y issues in get-started/dev (iss1301)

packages/patternfly-4/gatsby-node.js, packages/patternfly-4/gatsby-theme-patternfly-org/versions.json, scripts/checkoutVersion.js, yarn.lock
Also give up on backfilling 2019.09. That release is difficult to reverse-engineer to get working in org.
=> bump repos for 2019.11

packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
=> fix(docs): hide version switcher on mobile

packages/patternfly-4/gatsby-theme-patternfly-org/helpers/extractExamples.js
=> fix(examples): fix html-formatter for HTML not starting with <

packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js, packages/patternfly-4/gatsby-theme-patternfly-org/helpers/extractExamples.js, packages/patternfly-4/gatsby-theme-patternfly-org/helpers/index.js
To make https://github.com/patternfly/patternfly-next/pull/2665 clean.
=> export example className methods

packages/patternfly-4/gatsby-config.js, packages/patternfly-4/gatsby-theme-patternfly-org/components/propsTable/propsTable.js, packages/patternfly-4/gatsby-theme-patternfly-org/index.js, packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js, packages/patternfly-4/gatsby-transformer-react-docgen-typescript/gatsby-node.js, packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md, packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/data-loading/data-loading.md, packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/filters/filters.md, packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/toolbar/toolbar.md, packages/patternfly-4/src/pages/index.js
This PR updates the docs to refer to what was previously "experimental" components/properties as "beta" components/properties. These changes go along with and are dependent upon https://github.com/patternfly/patternfly-next/pull/2680 and https://github.com/patternfly/patternfly-react/pull/3663.
=> Experimental beta

packages/patternfly-4/gatsby-theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js, packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.css, packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js, packages/patternfly-4/gatsby-theme-patternfly-org/components/propsTable/propsTable.js, packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js
This PR adds support for badges to represent beta properties and examples. Should help facilitate this design https://github.com/patternfly/patternfly-org/issues/1646#issuecomment-582939063
=> feat(beta): add badge support for beta properties and examples

packages/patternfly-4/gatsby-theme-patternfly-org/components/propsTable/propsTable.js
This PR fixes an issue where we get development time warnings about non-unique keys when the new beta prop flag is used.
=> fix(keys): use unique keys for beta badge in props table

packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js
Temporarily revert #1686 until design confirms which pages this should and should not display on.
=> Fix(docs): remove Feedback section at bottom of each page

packages/patternfly-4/gatsby-theme-patternfly-org/components/gdprBanner/gdprBanner.css, packages/patternfly-4/gatsby-theme-patternfly-org/components/gdprBanner/gdprBanner.js
Closes #1715 - this PR updates the classes and CSS styles applied to the GDPR banner in order to position the "X" close button in the top-right rather than centered vertically.
=> updated classes and CSS rules for close button alignment

packages/patternfly-4/gatsby-theme-patternfly-org/pages/404.js, packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js, packages/patternfly-4/src/pages/get-in-touch.js, packages/patternfly-4/src/pages/index.js
This PR updates all usage of Title component to explicitly set the `headingLevel` prop. Pairs along with https://github.com/patternfly/patternfly-react/pull/3922
Nothing should actually have changed in terms of what heading levels are applied on the site, just that they are now set explicitly. Upcoming changes for Title will make this a required prop so just getting ahead of it.
=> chore(title): set headingLevel explicitly in Title usage

packages/patternfly-4/gatsby-theme-patternfly-org/components/gdprBanner/gdprBanner.js
Fixes #1724 - moved conditional render statement outside of banner wrapper to ensure border is not rendered when banner is closed.
=> completely remove GDPR banner when closed

packages/v4/src/content/design-guidelines/content/writing.md
Per issue #912 I am removing the text and image addressing use of a string table as this goes beyond the scope and intent of this guideline.
Closes #912
=> Remove guidance on using string table

packages/v4/src/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md
Closes #1708 
This PR fixes the broken links from the Bulk Selection page to the Data Toolbar (Core & React) pages
=> fix(docs): fix broken datatoolbar links in bulk selection docs

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css, packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
Closes #1678 
- removed PF3 banner
- added PF3 to version switcher
- fixed version switcher links
- limited version switcher to 4 versions
=> chore(docs): Remove PF3 banner, update version switcher

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
Towards #1769 
This PR fixes the positioning of the search results on mobile so they don't stretch off the right side of screen.
=> fixed positioning of search results on mobile

packages/gatsby-theme-patternfly-org/templates/mdx.js
closes #1823 
The padding between the release note cards is not correct. The fix is to move to using the new "hasGutter" prop.
=> Releasenotes toc has gutter 1823

packages/gatsby-theme-patternfly-org/pages/global-css-variables.md
Breaking build in React currently since pf-m-redhat-font was removed.
=> fix(css-variables): remove font type temporarily

packages/gatsby-theme-patternfly-org/components/sideNav/sideNav.css
Closes #1832
side-nav-link colors now match page background.
=> fix(css): side-nav-link colors

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
Fix for version switcher dropdown items not linking anywhere
=> fix version switcher href

.circleci/upload-staging.sh, packages/gatsby-theme-patternfly-org/components/topNav/topNav.js, packages/gatsby-theme-patternfly-org/components/trainingCard/trainingCard.js, packages/gatsby-theme-patternfly-org/gatsby-node.js, packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js, packages/gatsby-theme-patternfly-org/versions.json, packages/v4/gatsby-ssr.js, packages/v4/package.json, yarn.lock
=> fix(org): update to RC1 versions

packages/v4/src/content/design-guidelines/styles/icons/icon-migrations.js
Closes #1872 
Fixes last row of icons recommendations table - removes text from 2nd column "Updated icon" and updates text in 3rd row "Contextual usage"
=> fix(docs): updated recommended icon table - pf-icon-spinner row text

packages/gatsby-theme-patternfly-org/components/trainingCard/trainingCard.css, packages/gatsby-theme-patternfly-org/components/trainingCard/trainingCard.js, packages/gatsby-theme-patternfly-org/index.js, packages/gatsby-theme-patternfly-org/templates/mdx.js, packages/gatsby-transformer-react-docgen-typescript/gatsby-node.js, packages/v4/gatsby-config.js, packages/v4/src/content/training/core-training.md, packages/v4/src/content/training/react-training.md
closes #1874 
@redallen there used to be navigation in the top right corner of the tutorial page, I think the code is still there but im not sure why its not displaying any more
=> Add alert to Training because Katacoda is down

packages/gatsby-theme-patternfly-org/templates/mdx.css, packages/v4/src/content/design-guidelines/styles/typography/typography.js, packages/v4/src/content/design-guidelines/styles/typography/typography.md, packages/v4/src/pages/get-in-touch.css, packages/v4/src/pages/get-in-touch.js
Closes #1892 
See original issue https://github.com/patternfly/patternfly/issues/3185
This PR adds back 'Red Hat Display' on Typography, Get in touch, and Release notes pages.
=> chore(docs): updated font family text to add back RedHatDisplay

packages/gatsby-theme-patternfly-org/layouts/trainingLayout/trainingLayout.js
Closes #1891 
renamed `toolbar` prop to `headerTools` in PageHeader
=> fix(docs): Fixed missing breadcrumb in training modules

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
Closes #1868 
Closes #1900 
Removed custom styles from PageHeader that were causing:
- PF brand logo to float towards the center rather than align left beside hamburger menu
- search box to have black box below it at certain widths as seen in #1900 
- nav items to be squished at exactly 1200px width as seen in #1868
=> fix(site nav): removed custom styles from PageHeader

packages/gatsby-theme-patternfly-org/templates/mdx.css, packages/gatsby-theme-patternfly-org/templates/mdx.js, packages/v4/src/content/design-guidelines/styles/typography/typography.js, packages/v4/src/content/design-guidelines/styles/typography/typography.md
Org release feedback:
- fix styling of "latest" badge on release notes
- fix font weight for heading level 4 on Typography page
- switch "i.e." to "e.g." on Typography page
=> fix(release): fixes for Org bump

packages/v3/source/get-started/frequently-asked-questions/index.md
Followup to #1778.
https://www.patternfly.org/v4/get-started/about#supported-browsers now says only 1 latest version of each browser is supported by PF4.
https://www.patternfly.org/v3/get-started/frequently-asked-questions/ says PF4 supports 2 latest.
I don't myself know which is correct :man_shrugging:  but @ncameronbritt said in internal chat https://coreos.slack.com/archives/CB53T9ZHQ/p1591285796394900?thread_ts=1591282182.390900&cid=CB53T9ZHQ :
> confirmed that the v4 version is accurate. Support latest version only.
@evwilkin @redallen @ncameronbritt please review.
=> Update PF4 supported browsers "latest 2" -> "latest"

packages/v4/src/content/design-guidelines/styles/icons/IconsTable.js, packages/v4/src/content/design-guidelines/styles/icons/icons.md
Made a few updates to the icon guidelines text to further emphasize the fact that designers can use any FA free icon offered.
Fixes #1888
=> Update to icon guidelines to emphasize ability to use any FA free icon

packages/gatsby-theme-patternfly-org/templates/mdx.js
The previous issue with Katacoda (the files in the file tree not appearing) and the v4 updates to the tutorials have been resolved. But now there is an issue regarding how the tutorials are embedded and we are waiting on Katacoda to respond, so I have updated the message on our training page accordingly to redirect users to Katacoda.com where the tutorials are working.
The issue is documented here: https://github.com/patternfly/training-scenarios/issues/305
cc: @janwright73 @dgutride
=> update error message on training

packages/gatsby-theme-patternfly-org/helpers/extractExamples.js, packages/gatsby-theme-patternfly-org/index.js, packages/gatsby-theme-patternfly-org/templates/fullscreenMDX.js
Fix fullscreen pages and extracting ids for examples without meta strings.
=> fix(example): h3s for react

packages/v4/src/content/design-guidelines/styles/typography/typography.css, packages/v4/src/content/design-guidelines/styles/typography/typography.js, packages/v4/src/content/design-guidelines/styles/typography/typography.md
Closes #1974 
Follow-up to #1915 - this PR adds the correct font-family styling to the code text sample
=> applied className & font-family styling to code text example

packages/theme-patternfly-org/pages/global-css-variables.md, packages/theme-patternfly-org/pages/red-hat-font.md
Removing release notes and upgrade guide will have to be done upstream. It will also affect the live site to do that, so we're probably better off waiting to do this after our last normal site release.
=> move 2 pages to get started

packages/v4/src/content/design-guidelines/content/brand-voice-and-tone.md, packages/v4/src/content/design-guidelines/content/content.css, packages/v4/src/content/design-guidelines/content/error-messages.md, packages/v4/src/content/design-guidelines/content/numerics.md, packages/v4/src/content/design-guidelines/content/product-tours.md, packages/v4/src/content/design-guidelines/content/punctuation.md, packages/v4/src/content/design-guidelines/content/sentence-structure.md, packages/v4/src/content/design-guidelines/content/ux-writing-best-practices.md
Closes #2063 
This PR wraps markdown tables within the `UX writing` section with `<div class="ws-content-table">` to apply fixed `table-layout` styling.
Note: Table at bottom of `Terminology` section remains unchanged, as do tables outside of the `UX writing` section, ex: http://localhost:8003/guidelines/filters
=> Align columns in UX writing section

packages/theme-patternfly-org/templates/mdx.css
Closes #2078 
Changes `width` property to `max-width` so content doesn't overflow off smaller screens
=> updated width to max-width

packages/v4/src/content/design-guidelines/styles/colors-for-charts/colors-for-charts.md, packages/v4/src/content/design-guidelines/styles/colors-for-charts/colors-grid.js
Closes #2080 
Follow-up to #2076 
Previous PR introduced 2 console errors on the Colors for charts page which are fixed by this PR.
=> resolved console errors on Colors for charts

packages/v4/package.json, packages/v4/src/content/design-guidelines/styles/icons/icons.js, yarn.lock
Closes #2101 
This PR bumps `react-docs` to pull in the latest updates to `react-icons`, and updates the icons table in the docs to hide the `AnsibeTowerIcon` and instead show the corrected `AnsibleTowerIcon`.
=> fix(icons): hide AnsibeTowerIcon, show AnsibleTowerIcon

package.json, packages/theme-patternfly-org/package.json, packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js, packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js, packages/v4/package.json, yarn.lock
~3s faster reload times in React. The theme, `@patternfly/react-*` packages, and `node_modules` packages are now nicely split:
=> change cacheGroups, add lodash-es

packages/theme-patternfly-org/versions.json
Closes #2140 
This PR updates the versions.json to rename the 2020.11 release versions to 2020.12, and adds the missing 2020.11 release versions.
=> renamed 2020.11 versions to 2020.12, added missing 2020.11 versions

packages/v4/patternfly-docs.source.js
Closes #2182 
Adds Datetime package to MD docs sourcing to pull in React docs.
TODO: update versions/React release notes?
=> fix(docs): fixed MD sourcing to display React docs & React demos tabs correctly

packages/theme-patternfly-org/helpers/codesandbox.js, packages/theme-patternfly-org/helpers/fonts.js, packages/theme-patternfly-org/helpers/index.js, packages/theme-patternfly-org/scripts/cli/generate.js, packages/theme-patternfly-org/scripts/md/mdx-ast-to-mdx-hast.js, packages/theme-patternfly-org/scripts/md/parseMD.js
Towards https://github.com/patternfly/patternfly-react/issues/4988
Example:
```
node_modules/@patternfly/react-charts/src/components/ChartLegend/examples/ChartLegend.md
1:1  warning  Must have valid example identifier for JS example Basic with right aligned legend
1:1  warning  Must have valid example identifier for JS example Bottom aligned legend
1:1  warning  Must have valid example identifier for JS example Standalone legend
```
=> force valid example identifiers

packages/v4/src/content/design-guidelines/components/empty-state/empty-state.md
just fixed a header in the empty state examples that was supposed to be H3 but was H2.
=> empty state header fix

packages/v4/src/content/design-guidelines/components/banner/banner.md, packages/v4/src/content/design-guidelines/styles/icons/icons.md
Closes #2236 
This PR changes incorrect em dashes (—) to double dashes (--) on Icons page and Banner design guidelines in code examples.
=> fix(docs): fix double dashes where they've been replaced by em dashes

packages/v4/src/content/design-guidelines/content/numerics.md
We no longer use moment.js –– this edit aligns our library examples with that change.
=> Removing moment.js from "Numerics" localization library suggestions 

packages/theme-patternfly-org/templates/html.ejs
Closes #2249 
This PR adds a `<meta name="description"` tag to the site with a content attribute describing the site.
=> chore(docs): add meta description tag

packages/v4/src/content/contribute/design-guidelines/design-guidelines.md
Changing the words "PR name" to "branch name" to alleviate confusion. Right now, the mention of PR title vs PR name gets confused. In reality, what was being referred to as "PR name" is actually the "branch name", so I changed it to reflect that!
=> change "PR name" to "branch name"

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
Based on a conversation with @redallen . Just a nice little shortcut easter egg for those of us vim nerds who like to quickly start a search by pressing the `/` key. Also includes `S` as an alternate key in case `/` is already bound (in Firefox, it triggers the "find in page" bar). The search box won't be focused if the key press is coming from within an `<input>` or `<textarea>` in one of the examples. Also, if the user presses the `Escape` key while they are focused in the search box, it will close.
Before this approach, I tried to use the `keyboardShortcuts` option for Algolia detailed at https://github.com/algolia/autocomplete.js#global-options, but because our search input is not in the DOM until we call `setSearchExpanded`, the built in keyboard shortcut wasn't working. I couldn't …
=> Add S and / as hotkeys to open the search bar, and ESC to close it

packages/v4/src/content/design-guidelines/content/writing-design-documentation.md
I also reordered our **Style, voice, and tone** list so that our relative hyperlink guidance leads directly into our info about using relative URLs instead of full ones.
Closes #2280
=> Adding guidance for relative URLs to "Writing design guidelines"

packages/theme-patternfly-org/helpers/buble.js
Fixes problem @jschuler reported in https://github.com/patternfly/patternfly-react/pull/5172 where there was no space between "hi" and "there" for examples like this:
```jsx
<div>
hi <a href="#">there</a>
</div>
```
and this:
```jsx
<div>
hi
<a href="#">there</a>
</div>
```
=> fix whitespace in JSXText

packages/v4/src/content/design-guidelines/styles/icons/icons.js
Following up on https://github.com/patternfly/patternfly-design/issues/930#issuecomment-735936630.
cc @redallen @bdellasc @mcoker @evwilkin
=> Add ResourcesEmptyIcon to icons page

packages/theme-patternfly-org/package.json, packages/theme-patternfly-org/scripts/tsDocgen.js, yarn.lock
5.3.1 fixes:
> /home/circleci/project/node_modules/@patternfly/react-table/src/components/Table/examples/Table.md
1:1  warning  Prop component TableComposable missing from tsDocgen
1:1  warning  Prop component Td missing from tsDocgen
1:1  warning  Prop component Th missing from tsDocgen
Which is caused by no AST support for the optional chaining operator:
>  No component found in /Users/zallen/src/patternfly-org/node_modules/@patternfly/react-table/src/components/TableComposable/TableComposable.tsx: Error: did not recognize object of type "ChainExpression"
at Object.getFieldNames (/Users/zallen/src/patternfly-org/node_modules/ast-types/lib/types.js:660:19)
at visitChildren (/Users/zallen/src/patternfly-org/node_modules/ast-types/lib/path-visitor.js:184:36)
at …
=> upgrade react-docgen

packages/theme-patternfly-org/app.js, packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js, packages/theme-patternfly-org/templates/mdx.js
Only create page for `/components/about-modal` and NOT `/components/about-modal/react` (or whatever the first tab is in the source order).
Reduce number of pages by ~33%.
=> remove duplicate routes

packages/v3/source/get-started/index.html, packages/v4/src/content/contribute/design-guidelines/design-guidelines.md, packages/v4/src/content/contribute/design/design.md, packages/v4/src/content/design-guidelines/components/login-page/login-page.md, packages/v4/src/pages/home.js
Updates `Github` to `GitHub` in a few places, including the homepage button.
=> Update GitHub capitalization

packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js
This makes it difficult for Algoila to know whether urls like `https://www.patternfly.org/v4/get-started/design` or `https://www.patternfly.org/v4/charts/area-chart` are sourced from but this fix at least tells it they exist and that they exist only once.
=> update sitemap to reflect new urls

packages/v4/patternfly-docs.source.js
Closes #2320 
This PR remove react-datetime package from the source file as it was previously combined into react-core in https://github.com/patternfly/patternfly-react/pull/5201
=> removed react-datetime from source

packages/v4/src/content/design-guidelines/content/numerics.md
Addresses #2209: 
Catherine's feedback deletes some of Pat's feedback concerning ISO standards for international currency. @abigaeljamie, are we planning on removing that feedback from the page? I left it under the **Currency** heading just in case, and we can follow up next week.
=> Applying feedback to Numerics page

packages/v4/src/content/contribute/design-guidelines/design-guidelines.md, packages/v4/src/content/get-started/design.md
Shortened Sketch Cloud URLs [broke last year](https://updates.sketch.cloud/support-for-short-cloud-sharing-urls-is-ending-175140). This PR replaces them so that they work again.
Resolves #2345
=> Fix Sketch links

packages/theme-patternfly-org/components/sideNav/sideNav.js, packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css, packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
Closes #2205 
This PR:
- Adds dropshadow to sidenav on mobile
- Closes sidenav on mobile when user clicks a page link in the sidenav by passing `onNavToggle` to `Sidenav` component & triggering in `onClick` in `navItem`
=> fix(docs): add sidenav shadow on mobile, close sidenav on NavItem click on mobile

packages/v4/src/pages/community.js
Closes #2368 
This PR fixes the "Join our mailing list" link in the body copy of the Community page.
=> fixed mailing list link

packages/v4/src/content/design-guidelines/styles/icons/IconsTable.js, packages/v4/src/content/design-guidelines/styles/icons/icons.css, packages/v4/src/content/design-guidelines/styles/icons/icons.js
Closes #2223 
This PR:
- Adds new `Tooltip labels` column
- Adds tooltip labels to a handful of icons
- Hides the `Type` column, but still allows it to be searchable
=> Add tooltip labels & hide Type column

packages/theme-patternfly-org/helpers/buble.js
Makes
```jsx
<div>
1 <span>2</span> 3
</div>
```
into
```js
return React.createElement("div",{},"1 ",React.createElement("span",{},"2")," 3");
```
just like [the Babel compiler!](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwEwlgbgfAUABHAjHYBnADgQwHZQEzAD0GOUcAzDEeNEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.11&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.12.1)
Related: #2284
=> fix(buble): perfect JSXText regex?

packages/v4/src/content/get-started/design.md
This PR updates the get started for designers instructions so that it incorporates the proper details for non-Sketch users.
fixes #2152
=> Updating get started - design instructions

packages/v4/src/pages/community.js
Adds the PatternFly Fritz2 (Kotlin) project to the Community page as a new community project.
=> Add PatternFly-Fritz2 community project links

packages/v4/src/pages/community.js
The landing page for PatternFly Elements is now at: patternflyelements.org.
Thanks!
=> Updating the URL for PatternFly Elements

packages/theme-patternfly-org/versions.json, packages/v4/package.json, packages/v4/patternfly-docs.source.js, yarn.lock
2021.06 Org bump
Adds `react-log-viewer` to source file.
=> bumping for 2021.06 release and updated for log viewer package

packages/theme-patternfly-org/helpers/codesandbox.js, packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js
Closes #2422 
This PR fixes Codesandbox showing broken images for HTML examples with images and not building for React examples with images by replacing the imports/relative hrefs with links back to the PF.org images.
- updated codesandbox template to point back to pf.org hosted images
- updated webpack config to use file-loader for gif|svg
=> fix(docs): Fix codesandbox broken/missing images

packages/v4/src/content/get-started/design.md
Reverts patternfly/patternfly-org#2521
@redallen Sorry for reverting it back, but Sketch migrated our old library yesterday and preserved all links. We don't have to change links on the PF website then. Thank you!
=> Revert "Updated broken library links"

scripts/writeVersionPrefix.js
Fixes copying images in version prefix builds
=> fix copying non-utf8 files

packages/v4/src/content/developer-resources/accessibility-development.md, packages/v4/src/content/developer-resources/accessibility-guide.md, packages/v4/src/content/developer-resources/patternfly-accessibility.md
Fix some odd code styling and use sentence case for titles:
=> sentence case and fix code blocks

packages/v4/src/content/design-guidelines/components/toolbar/toolbar.md
Updated the Toolbar design guidelines to try and clarify the definition of toggle groups in the context of a toolbar and differentiate from the toggle group component. Also updated the subheading levels in the Elements section so they show in the TOC.
Closes: #2187
=> Clarified toggle group definition

packages/theme-patternfly-org/templates/mdx.css
This changes cell alignment to `top` for workspace tables so that multi-line code snippets don't throw off the vertical alignment. The high specificity is required to get past the `.pf-c-table` cell style.
Fixes #2605
=> fix(workspace): vertically align docs tables

packages/theme-patternfly-org/components/propsTable/propTypeWithLinks.js, packages/theme-patternfly-org/components/propsTable/propsTable.js, packages/theme-patternfly-org/templates/mdx.js
Resolves #2608.
@redallen I had a hunch this would work and couldn't help myself.
Followup to #2586. When rendering each row of the `PropsTable`, this new `PropTypeWithLinks` component will look at the type name for that row and see if it contains full words matching any of the other component/interface names on the page. If so, it will split the type name into pieces isolating those matches and render the matched segments as links using the existing `slugger()` helper to generate the ids. This `slugger()` is what the `AutoLinkHeader` already uses to generate the ids of the referenced prop tables, so we know the ids being linked will always be consistent.
See the prop type for `customSteps` at v4/components/slider/#slider:
Several examples can also be seen in the new v4/components/table/ …
=> feat(propsTable): Convert interface names referenced in prop types on the same page into links

packages/theme-patternfly-org/components/example/exampleToolbar.js
Accidentally was hiding on https://www.patternfly.org/v4/components/background-image
=> fix(example): show readonly code for fullscreen example

packages/theme-patternfly-org/helpers/buble.js
Allow `<div boolAttr />` to be converted.
=> fix(ts->js): bool attributes

packages/v4/src/content/design-guidelines/components/alert/alert.md
Adding a "Customizing alerts" section as per #1953 
@mmenestr should we also include a visual example of what custom alerts might look like, or does the link to the examples suffice?
Thanks for your patience on this PR! :)
=> Adding custom alert guidance

packages/v4/src/pages/community.js
Closes #2620 
Fixes accessibility guide link on Community page, points it to Accessibility fundamentals page.
=> fixed accessibility guide link on community page

packages/theme-patternfly-org/helpers/acorn-typescript.js
=> fix(parser): allow arrow function types and paretheses array types

packages/theme-patternfly-org/components/link/link.js
Fixes #2615 
This PR replaces `window.location.hash` with `history.pushState` which updates the URL but does not trigger route change which was causing a re-render of the page and breaking the jumplinks.
This fixes the issue of clicking an autolinkheader (link icon beside a section/example heading corresponding with a jumplink) would break the jumplinks, always causing the first jumplink to show as active and no longer following the user's scrolling on the page.
=> updated link to use history.pushState to avoid route change

packages/v4/src/content/accessibility/button/button.md
A11y documentation for the Button PF component
Closes #2557
=> docs(button): add a11y documentation

packages/theme-patternfly-org/helpers/acorn-typescript.js
Fixes parsing `let a: b['c']['d]`
=> fix(ts): parse multiple type accessors

packages/theme-patternfly-org/components/example/example.css, packages/theme-patternfly-org/components/propsTable/propsTable.js, packages/theme-patternfly-org/scripts/md/styled-tags.js
Closes #2645 
This PR:
- Increases the "Type" column on component props tables from 15% to 20% width to help with text wrapping.
- Adds `breakWord` transform to the "Description" column on component props tables to fix long strings causing table to exceed parent container's width, such as with the URL in the `locale` prop description for calendar month [seen here](https://www.patternfly.org/v4/components/calendar-month/#props).
- Removes the "Required" column from the react props tables, replacing this with a red asterisk beside required prop names.
- For components with required props, instructional text at the top of the table explains that the asterisk marks required props, and those props are listed first in alphabetical order before the rest of the optional props.
=> fix(docs): update props table column widths & word breaks

packages/theme-patternfly-org/templates/mdx.css, packages/theme-patternfly-org/templates/mdx.js
Closes #2654 
This PR adds the new back to top button to the site, as well as custom css to set the z-index so that the button does not disappear behind the footer.
=> feat(docs): added back to top button to site

packages/theme-patternfly-org/templates/mdx.css, packages/theme-patternfly-org/templates/mdx.js
Closes #2691 
This PR:
- adds `flex-grow: 1` to `#main-content` to cause it to expand to fill the space when the contained content doesn't fill the screen.  This fixes the problem of the footer rising on the page.
=> fix(docs): fixed footer floats up the page by making #main-content flex-grow

packages/v4/patternfly-docs.source.js
Adds the OUIA page under the developer resources sections of the v4 docs
@evwilkin FYI
Resolves https://github.com/patternfly/patternfly-org/issues/2715
=> 2715 Add OUIA page to website

packages/theme-patternfly-org/components/example/example.js, packages/theme-patternfly-org/helpers/codesandbox.js
Found when testing https://github.com/patternfly/patternfly-react/pull/6168.
Currently, the codesandbox export code assumes any non-HTML examples are JS, and uses `index.js` for the filename and `create-react-app` for the codesandbox template.
This PR checks if the example being exported is written in TypeScript, and if so it will use `index.tsx` for the filename and `create-react-app-typescript` for the template.
It also adds the `@babel/runtime` dependency for TS sandboxes, because I was getting errors without that. It's strange because that dependency is not present when manually creating a sandbox with the CRA-typescript template, but that template also does not explicitly import React or ReactDOM or call render(). Instead it just makes the component the default export and codesandbox …
=> fix(docs): Export TypeScript examples to CodeSandbox with the correct configuration

packages/theme-patternfly-org/templates/mdx.js
Closes #1541 
This PR adds a link to the beta promotion schedule within the beta alert at the top of beta components.
@nicolethoen let me know if you know of a better place to link to, or if we'd like to add a README to this linked page with a little context.
=> docs(beta): linked to beta promotion schedule in beta alert

packages/v4/src/content/accessibility/brand/brand.md
=> docs(brand): add a11y documentation

packages/ast-helpers/stringify.js
=> fix: TS to JS conversion - Ability to spread props within components & allow for empty tags (fragments)

packages/theme-patternfly-org/app.js, packages/theme-patternfly-org/templates/html.ejs, packages/v3/source/_includes/google-analytics.html, packages/v4/src/pages/community.js
Closes #2793 
Closes #2792 
This PR:
- Replaces analytics.js tag with new gtag.js tag
- [Reference docs](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs): see [Replace the analytics.js snippet with the gtag.js snippet](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs#analyticsjs_2_gtagjs) and [Measure pageviews](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs#measure_pageviews) sections.
- Manually sets the page title for the `Community` page which is not updating when navigating from another page
- note: only change is `if` statement and adding `return` keyword at the top (diff shows much larger due to these updates pushing around the rest of the code)
Tested in PF's GA account …
=> updated GA to gtag.js, manually set Community page title

packages/theme-patternfly-org/scripts/md/mdx-hast-to-jsx.js, packages/theme-patternfly-org/scripts/md/parseMD.js, packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js
Windows has a different string for path separator `\`, we need to replace those to POSIX standard separator `/` to correctly import all the resources in the markdown files. Also, update the webpack config to correctly apply the babel loader.
=> Feat/Enable build and development for Windows users

packages/v4/patternfly-docs.config.js
Closes #2754 
Rather than track searches through Google Analytics, this PR enables the default search analytics automatically tracked by Algolia & accessible through the user dashboard in our account.
No analytics were previously being tracked, but these have been enabled by simply updating our API key to the current key & providing the `appId` as well - this last step is not clearly laid out in the docsearch docs as a requirement for analytics but was key in getting this working.
Note: confirming it is okay for this API key to be publicly viewable, per Algolia:
> This is the public API key which can be safely used in your frontend code.This key is usable for search queries and it's also able to list the indices you've got access to.
Result showing test searches coming through:
=> chore(docs): enabled algolia search analytics

packages/theme-patternfly-org/components/link/link.js
Closes #2836 
This PR reinstates default link behavior of detecting cmd/ctrl+click on links, fixing the current inability to cmd/ctrl+click on a sidenav link to open it in a new tab.
=> fix(docs): fixed to allow cmd/ctrl+click opening in new tab

packages/v4/src/content/design-guidelines/styles/icons/icons.js
Closes #2805 
This PR: 
- Adds the font awesome `FileIcon` to our [Icons page](https://patternfly-org-pr-2834-v4.surge.sh/v4/guidelines/icons) (it was already included in our code base but was not one of the icons displayed on our site [here](https://github.com/patternfly/patternfly-org/blob/main/packages/v4/src/content/design-guidelines/styles/icons/icons.js))
- TODO:  @doruskova - need to add "Type" (Framework/Brands/Status/Action/Object/View Type) and "Contextual usage" copy to add to this icon listing.
=> feat(icons): added FileIcon to icons page

packages/theme-patternfly-org/templates/mdx.css
to test, make your viewport width very narrow.
before this change, notice the examples are spilling over to the right like in the screenshot below from the Table with actions example where the actions kabob is completely off screen to the right. After this change, the examples don't spill over.
before:
=> fix: stop example widths from being wider than parent on mobile viewports

packages/v4/src/content/contribute/design/design.md
This PR updates the link to the design issues backlog and related text. This goes along with the migration of design sprint planning from the ZenHub board to the GitHub PatternFly Issues board.
=> Update design backlog link

packages/theme-patternfly-org/components/example/example.css, packages/theme-patternfly-org/components/example/exampleToolbar.js, packages/theme-patternfly-org/components/tableOfContents/tableOfContents.css, packages/theme-patternfly-org/components/tableOfContents/tableOfContents.js, packages/theme-patternfly-org/templates/mdx.css, packages/theme-patternfly-org/templates/mdx.js
Closes #2843 
This PR:
- Unhides the jumplinks which are currently hidden at <=1450px and utilizes the component's mobile layout plus custom styles from designs in #2843 
- Removes background from example headers/controls
- Remove borders from CodeEditorControls below each example, except for the blue bottom border on hover/focus/active
- Remove border below `.pf-c-code-editor__header` above example code except when example code is expanded
- Simplifies copy function for example code to fix console error currently being thrown
=> chore(docs): added mobile jumplinks and example styling

packages/theme-patternfly-org/templates/mdx.js
Closes #2925
[Date and time picker demo](https://patternfly-org-pr-2926-v4.surge.sh/v4/demos/date-and-time-picker/) for convenience.
As noted in the issue's additional information, the icons page also has a case of a link using "here" as link text, but that is something I plan to look into before another issue is opened.
=> Update link text for Beta component alert

packages/theme-patternfly-org/app.js
Closes #2827 
This PR checks the visited URL vs the matched path - if user is sent to 404 page but didn't specifically visit 404 page, sends Google Analytics event tracking original page URL.
<details>
<summary>For testing:</summary>
Unfortunately surge doesn't redirect to the 404 page so to test the code needs to be pulled, updated, and run locally.
1. pull code
2. change [this line](https://github.com/patternfly/patternfly-org/blob/main/packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js#L25) to the following to enable google analytics calls to fire in dev mode: `googleAnalyticsID: googleAnalyticsID,`
3. goto a nonexisting URL (e.g. http://localhost:8003/v4/404-test) and filter the `Network` tab in developer tools by the text 'collect'.
A network call should go out …
=> chore(docs): send GA tracking event w/URL when redirected to 404 page

packages/v4/src/content/get-started/develop.md
Closes #2832 
This PR fixes typos in the getting started for developers page around font awesome implementation instructions.
=> fix(docs): fixed font awesome typos

packages/theme-patternfly-org/templates/html.ejs
Closes #2881 
This PR adds the following opt-in fonts to the `<body>` tag in theme-patternfly-org, which trickles to the Core, React, and Org workspaces and the website:
- `.pf-m-redhat-updated-font`
- `.pf-m-redhatmono-font`
=> chore(docs): added opt-in font classes

README.md
Closes #2936 by adding the required Node version to the readme.
=> chore(docs): specify node version required to run locally

packages/theme-patternfly-org/components/tableOfContents/tableOfContents.js
closes #2969 
This PR:
- Mirrors the structure of the [nested jump links example](https://www.patternfly.org/v4/components/jump-links#expandable-vertical-with-subsection) from our docs to fix a11y error of a `<ul>` nested directly inside another `<ul>`.
Fix:
Previously we were either rendering `<JumpLinksList>` directly inside the `<JumpLinks>` component:
```
<JumpLinks>
<JumpLinksItem><JumpLinksItem>
<JumpLinksList><JumpLinksList/>
</JumpLinks>
```
We should always render a `<JumpLinksItem>` and place any needed `<JumpLinksList>`s within them where needed.
```
<JumpLinks>
<JumpLinksItem></JumpLinksItem>
<JumpLinksItem>
<JumpLinksList><JumpLinksList/>
</JumpLinksItem>
</JumpLinks>
```
=> fix(toc): fixed jumplinks in TOC to resolve a11y nesting issue

packages/theme-patternfly-org/components/example/example.css
Closes #2970 
This PR applies `overflow: hidden` to the HTML examples on the site to fix the problem of items meant to scroll off of a full page view still being visible when scrolling off of a contained example.
=> fix(docs): hid overflow in HTML examples

packages/theme-patternfly-org/components/cssVariables/cssVariables.js, packages/theme-patternfly-org/components/example/example.js, packages/theme-patternfly-org/components/example/exampleToolbar.js
- add ids to css variable tables to avoid using default id values and conflicting with examples
- adds example name to code editor toolbar control labels on each example to make them unique
=> fix duplicate ids/labels in generated component doc elements

packages/theme-patternfly-org/components/cssVariables/cssVariables.js, packages/theme-patternfly-org/components/inlineAlert/inlineAlert.js, packages/theme-patternfly-org/components/topNav/topNav.js
Updates include:
- more descriptive aria-label on the nav (to avoid conflicts with examples' navs more generic aria-labels)
- remove empty `<th>` in CSS variables table on react example pages by adding expand/collapse all toggle
- change the headingLevel in beta tag alerts to `<h2>` to maintain valid html heading level order
=> few more a11y fixes

packages/theme-patternfly-org/components/footer/footer.js
A programmatic way to use the current year would probably be best, but for now just updating the year to 2022.
=> Update copyright year

packages/theme-patternfly-org/components/example/example.css
Closes #3036 
This PR replaces the rule hiding all overflow on Core examples:
```
.ws-preview-html {
overflow: hidden;
}
```
with a more narrowly-scoped rule hiding overflow specifically on the Page examples, for both Core & React examples:
```
.ws-core-c-page.ws-preview > .ws-preview-html,
.ws-react-c-page.ws-preview > .pf-c-page {
overflow: hidden;
}
```
=> fix(docs): narrowed scope of rule hiding overflow on page examples

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js, packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js, packages/v4/patternfly-docs.config.js
Closes #2885 
Closes #2959
This PR adds a dark theme switcher to the website.  No designs to work from so open to feedback.
Note:  current code will expose switcher on the live site & not in the workspaces.  Once design is confirmed & approved, we'll need to edit the `patternfly-docs.config.js` file in each repo separately to add the `hasDarkThemeSwitcher` property to the exports & set it to true (to show the switcher) or false (to not render the switcher).
=> feat(docs): add dark theme switcher

packages/v4/patternfly-docs/content/accessibility/tooltip/tooltip.md, packages/v4/patternfly-docs/content/design-guidelines/components/tooltip/tooltip.md
Closes #2596
[Tooltip a11y tab](https://patternfly-org-pr-2892-v4.surge.sh/v4/components/tooltip/accessibility)
Current implementation for a11y docs on the tooltip. This is based off of the current changes made in https://github.com/patternfly/patternfly-react/pull/7332 and https://github.com/patternfly/patternfly-react/pull/7335.
Additionally, I added in some verbiage in regards to tooltips on static elements. In https://github.com/patternfly/patternfly-org/issues/1108#issuecomment-495262558 it was mentioned that tooltips on static elements shouldn't be recommended. However, utilizing the pattern of `aria-live` instead of `aria-describedby` does seem to resolve the gaps mentioned.
Original comment:
One proposal I want to put out there is whether we should include verbiage for when a …
=> docs(Tooltip): add a11y docs

packages/v4/patternfly-docs/content/design-guidelines/components/alert/alert.md
=> changing alert guidelines

packages/v4/patternfly-docs/content/design-guidelines/components/button/button.md
=> Updates button info architecture to align with guidelines.

packages/v4/patternfly-docs/content/accessibility/tabs/tabs.md
Closes #3071 
[Tabs a11y tab](https://patternfly-org-pr-3074-v4.surge.sh/v4/components/tabs/accessibility)
Added in several attributes to the HTML table which will require HTML examples to be updated as a follow-up (this can be done alongside updating the Accessibility section(s) on that tab).
=> docs(Tabs): update a11y doc to new template

package.json, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/v3/Gemfile, packages/v3/readme.md, packages/v4/patternfly-docs/patternfly-docs.config.js, scripts/writeV3Redirects.js
Closes #3048 
Remove references to v3 in package.json, the side nav, and the redirects file.
Also turned off the dark theme switcher - which is only supposed on be on in the workspaces.
There was talk of no longer needing the 'v4' in the URL, I imagine we could update `scripts/writeV3Redirects.js` again to redirect a url with a v4 in it to the url without it if we update the config to no long append 'v4' in the urls. what do you think @evwilkin @dgutride ?
=> Clean up after removing v3

packages/v4/patternfly-docs/content/design-guidelines/components/text-input-group/text-input-group.md
Adds design guidelines for the Text input group component that includes examples for attribute-value and auto-complete search.
Closes #2407
=> Text input group: add design guidelines

packages/documentation-framework/components/example/example.css, packages/documentation-framework/components/example/exampleToolbar.js
fixes https://github.com/patternfly/patternfly-org/issues/3137
--
I noticed a bunch of other discrepancies between the buttons, so I tried updating all of them to use [`<CodeEditorControl>`](https://github.com/patternfly/patternfly-react/blob/main/packages/react-code-editor/src/components/CodeEditor/CodeEditorControl.tsx), and with @nicolethoen's help, we discovered that [passing `exitDelay` from a state var (`isCopied`)](https://github.com/patternfly/patternfly-org/blob/9298e0ede6347f0b1ced12de5c2c924d8859d163/packages/documentation-framework/components/example/exampleToolbar.js#L90) doesn't work if there are multiple `trigger` values passed... or something like that. Got a little tricky for me, and our fearless leader @nicolethoen is going to look at it.
This PR
* adds a new CSS var to …
=> fix(example): increase code editor button tooltip size, other cleanup

packages/v4/package.json, packages/v4/patternfly-a11y.config.js, packages/v4/patternfly-docs/patternfly-docs.source.js, yarn.lock
Also omitting react-next doc pages from a11y builds.
=> Update v4 docs source to allow for 'react-next' source names

packages/documentation-framework/package.json, packages/documentation-framework/scripts/webpack/webpack.base.config.js
Closes #3175 
This PR adds `@babel/plugin-proposal-optional-chaining` to the `documenation-framework` package in order to properly handle files contained within this package that include optional chaining.
=> fix(docs): added support for optional chaining in docs-framework

packages/v4/patternfly-docs/content/design-guidelines/components/modal/modal.md
Closes #3198
Moved the `aria-label` properties from child `<i>` elements to parent `<span>` elements.
However, this then brings up the issue where the `role` property must be assigned a value. I've assigned `role="img"` to the <span> elements for the time being, let me know if these should be some other value or if there is another solution.
=> docs(Modal): move aria-label from <i> to <span>

packages/v4/patternfly-docs/content/accessibility/card/card.md, packages/v4/patternfly-docs/content/design-guidelines/components/card/card.md
Closes #2809, closes #3112 
[Card a11y preview build](https://patternfly-org-pr-3153-v4.surge.sh/v4/components/card/accessibility/)
I included some verbiage about placing multiple cards within a list container, though I don't believe this is a convention we've shown in card examples. Would like to hear any other opinions on it.
=> docs(Card): update a11y doc to new template

packages/documentation-framework/helpers/codesandbox.js, packages/documentation-framework/scripts/md/mdx-hast-to-jsx.js
I spent some time parsing these regexp trying to figure out if the lookbacks were necessary. Everything seems to work without them and they are [not supported in Safari](https://caniuse.com/js-regexp-lookbehind).
=> fix: remove lookbacks in regex to support safari 16

packages/v4/patternfly-docs/content/accessibility/accordion/accordion.md, packages/v4/patternfly-docs/content/accessibility/alert-group/alert-group.md, packages/v4/patternfly-docs/content/accessibility/alert/alert.md, packages/v4/patternfly-docs/content/accessibility/avatar/avatar.md, packages/v4/patternfly-docs/content/accessibility/tabs/tabs.md, packages/v4/patternfly-docs/content/accessibility/tooltip/tooltip.md
This reformats the avatar a11y documentation, and also fixes a typo that's gotten copied to a few sections.
Fixes #3242
=> chore(avatar): reformat a11y docs, also fix a typo

packages/documentation-framework/components/footer/footer.css, packages/documentation-framework/components/footer/footer.js, packages/documentation-framework/templates/mdx.js, packages/v4/patternfly-docs/pages/community.js
Fixes #3184 
Adds IsWidthLimited to the description section, but since that adds a `pf-c-page__main-body` with its own padding, I had to remove the utility class on the page section and instead directly modify the variable to remove top padding on `pf-c-page__main-body`.
=> fix(components): width limit the description section

packages/v4/package.json, packages/v4/patternfly-docs/content/design-guidelines/styles/icons/icons.js, yarn.lock
Closes #3223 
This PR adds the new `pf-icon-open-drawer-right` icon to the website, which includes pulling in a newer `react-docs` version in order to get the new icon.
=> chore(docs): added new opendrawerrighticon to docs

packages/v4/patternfly-docs/content/accessibility/menu/menu.md
Closes #https://github.com/patternfly/patternfly-org/issues/3255
This feels like a start, but I'm not sure how much detail to include and how much I should go into specific examples
=> docs(Menu): add accessibility documentation

packages/v4/patternfly-docs/content/accessibility/button/button.md
Closes #3286 
The HTML a11y section mentions `aria-pressed`. Would it be worth keeping this verbiage and adding a prop to React? Currently the attribute isn't used anywhere for the component, but React does have examples of native button elements being used with `aria-pressed` passed in, so if we ever plan to update those examples to use our component instead it'd make sense.
=> chore(Button): updated a11y docs

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/v4/patternfly-docs/content/design-guidelines/styles/icons/icons.js
Closes #3305 
This PR adds the `data-sink` and `data-source` icons to the website icons page.
=> chore(docs): added data sink/source icons

packages/documentation-framework/templates/mdx.js
Adds some logic to resolve the discrepancies in page header colors, and adds tab section to examples that were missing it as noted by @mcoker in #3239.
Closes #3239
=> fix page header colors, add missing tab sections

packages/documentation-framework/app.js
Resolves bug causing issues in graphlib dependency of the topology extension when attempting to add topology documentation.
Bug reported here: https://patternfly.slack.com/archives/C4FM977N0/p1671037144183429
Bug TLDR: the graphlib dependency of the dagre package which topology relies on throws a runtime error of `_.constant is not a function` when attempting to run topology components using the pf docs framework.
I think the issue is rooted in [this webpack alias](https://github.com/patternfly/patternfly-org/blob/31f12aca3284b6eadb1d458990023a512ede352a/packages/documentation-framework/scripts/webpack/webpack.base.config.js#L123) as removing that also fixes the issue. Not sure what the exact mechanism of the issue is though as constant seems like it also exists on lodash-es. Either way …
=> fix(lodash): add lodash.constant to global._

packages/v4/patternfly-docs/content/accessibility/calendar-month/calendar-month.md
Closes #3288 
Added some verbiage about using `aria-current="date"` (this could also apply to timepicker, but with "time" instead). [Marking elements as the current one using aria-current](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/current/#intended-use) states to avoid it for "now" (when the article was written in 2018) and to instead use visually hidden text. 
Additionally, date ranges might be an issue as well. Would all dates in the range have `aria-current="date"`, would only the 'range start' and 'range end' dates have that (possibly plus a visually hidden text to differentiate), or would only visually hidden text be more appropriate in that case?
=> chore(CalendarMonth): updated a11y docs

packages/documentation-framework/helpers/codesandbox.js
Closes #3266 
This PR updates the `dependencies` object passed to codesandbox with all imported packages for each example, fixing the error of `@reach/router` dependency not being declared in codesandbox when it's used in an example.
=> fix: update codesandbox dependencies per example import

packages/v4/patternfly-docs/content/accessibility/badge/badge.md, packages/v4/patternfly-docs/content/accessibility/tooltip/tooltip.md, packages/v4/patternfly-docs/content/design-guidelines/components/tree-view/tree-view.md
Closes #3276
The a11y docs already had some verbiage about not using only color which I mostly kept in tact, but I also added some verbiage about adding a `pf-screen-reader` class to add additional context for users navigating via AT. Depending on whether we'd want to keep that, it might be worth either updating the Badge examples and/or maybe adding a prop in React for adding in `screenReaderText`.
=> chore(Badge): update a11y docs

packages/v4/package.json, packages/v4/patternfly-docs/patternfly-docs.source.js, yarn.lock
Updated code to point to correct doc location for react log viewer.  This is needed since code has been moved out of PF repo and into it's own [repo](https://github.com/patternfly/react-log-viewer) for the extension.
=> fix(react-log-viewer):  Added react log viewer extension updates

packages/documentation-framework/scripts/webpack/getHtmlWebpackPlugins.js
This is the docs-framework update to fix build in https://github.com/patternfly/patternfly-react/pull/8586
=> fix(docs-framework): skip topology in prerendering step

packages/v4/patternfly-docs/content/accessibility/alert/alert.md, packages/v4/patternfly-docs/content/accessibility/modal/modal.md
Closes #2500, closes #3346 
This would require updates in React, possibly Core. For Core it'd probably just be updating/adding an example to show modal content overflowing, while React would need to add in functionality to set things under the hood for when modal content overflows. Would most likely be similar to the Accordion PRs that made similar updates (https://github.com/patternfly/patternfly/pull/5130 and https://github.com/patternfly/patternfly-react/pull/8515)
=> chore(Modal): updated a11y docs

packages/documentation-framework/scripts/md/parseMD.js, packages/documentation-framework/templates/patternfly-docs/content/extensions/extension/examples/basic.md
Closes #3331 
This PR allows propComponents to be pulled in for components with a different source (such as a component in the `next` directory referencing props from a standard component) by allowing an object to be passed as a `propComponent` in place of the component name string. 
This object should contain a `component` property mapped to the component name, and a `source` property mapped to the name of the source (ex: `react`).  Example:
```
propComponents: [
'Dropdown',
'DropdownGroup',
'DropdownItem',
'DropdownList',
{
component: 'MenuToggle',
source: 'react'
}
]
```
=> feat(docs): allow propComponents from another source

packages/documentation-framework/pages/404/index.js
=> fix(404 Page): Removed CardHeaderMain

packages/documentation-framework/app.js, packages/documentation-framework/scripts/webpack/webpack.base.config.js
Closes #2944 
This PR removes the harded coded Google Analytics ID from the documentation framework, instead picking it up where it's passed through by the user as it does in other places.
Additionally, this PR confirms completion of GA4 setup which was completed through the analytics account and does not require additional code changes at this time (see issue for relevant page links).
=> chore: remove hard coded GA ID

packages/documentation-framework/scripts/cli/build.js, packages/documentation-framework/scripts/cli/cli.js
Towards #3432
How to test:
0. Checkout branch
1. Set your node version to the latest LTS
2. Attempt to run `yarn build` to build the documentation, observe that it fails
3. `cd` to `packages/v4` and run `yarn build --legacySSL`, observe that it is now able to build
This shouldn't change how the package currently works, but will optionally enable use with node 18 (thus unblocking patternfly/patternfly-react#8303) until we are able to make the more substantial upgrade of webpack.
=> feat(docs-framework): add legacy ssl cli option

packages/v4/patternfly-docs/content/design-guidelines/styles/icons/IconRecommendations.js, packages/v4/patternfly-docs/content/design-guidelines/styles/icons/IconsTable.js
Closes #3482 
This PR fixes a few small display/search functionality bugs in the tables on the icons page:
> - Full icons list should include react icon name in the search (currently if you search the exact react icon name you may get 0 results)
> - Recommended icons should only show "contextual usage" for the updated icon, not the old icon.
> - Recommended icons "contextual usage" should include line break when there is copy for more than 1 recommended icon, currently these descriptions run together
> - Recommended icons currently only searches through the first two icons, but needs to be dynamic as in some cases there are multiple "old icons" or multiple "updated icons" and not just one old icon mapped to one updated icon.
=> fix(docs): fixes display & search bugs on icons page

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
Closes #3272
Adds a basic link to the version switcher. The link itself needs to be updated to point to wherever we decide to move `v4` (and if we choose `v4.patternfly.org` to match `v3`, then we also need to move the `core` site - maybe to `core.patternfly.org`?).
Also, do we want v4 to come before or after v3 in the list as v4 is more recent?
=> chore: add v4 version switcher link

packages/documentation-framework/components/footer/footer.js, packages/v4/patternfly-docs/content/contribute/about/about.md, packages/v4/patternfly-docs/content/get-started/about.md, packages/v4/patternfly-docs/pages/community.js
Move feature request instructions to the get-started/about page and replace references and links to the old PF Forum with links to GitHub Discussions. Updates include:
* Instructions about how to submit a feature request on Get Started/About
* Updates to the Community page to talk about requesting new features
* Change forum links to discussions in footer and Community page.
=> Feature requests as discussions

packages/v4/patternfly-docs/content/accessibility/label/label.md
Closes #3460 (also takes care of updating the Label a11y docs to the new template and creating LabelGroup docs)
[Label accessibility documentation](https://patternfly-org-pr-3484-v4.surge.sh/v4/components/label/accessibility)
=> chore(Label/LabelGroup): created combined a11y docs

packages/v4/patternfly-docs/content/training/react/fundamentals.md
Fixes a minor typo in the starting `<Button>` tag, at https://www.patternfly.org/v4/training/react-fundamentals-training/#step-2.2
=> docs: fix minor typo in "React fundamentals training" page

packages/documentation-framework/components/autoLinkHeader/autoLinkHeader.js, packages/documentation-framework/components/cssVariables/cssVariables.js, packages/documentation-framework/components/example/example.js, packages/documentation-framework/components/sideNav/sideNav.js, packages/documentation-framework/package.json, packages/documentation-framework/routes.js, packages/documentation-framework/scripts/md/parseMD.js, packages/documentation-framework/templates/mdx.js, packages/v4/package.json, packages/v4/patternfly-a11y.config.js, packages/v4/patternfly-docs/content/get-started/about.md, yarn.lock
Closes https://github.com/patternfly/patternfly-org/issues/3370
Closes https://github.com/patternfly/patternfly-org/issues/3371
Closes https://github.com/patternfly/patternfly-org/issues/3467
Closes https://github.com/patternfly/patternfly-org/issues/3489
Implements designs from design issue https://github.com/patternfly/patternfly-design/issues/1239
Note: I need to add some frontmatter metadata to a number of core/react to make banners appear at the top of some deprecated tabs. This PR is meant to enable the displaying of labels/banners, and still requires some follow up work in other repos.
=> feat(labels): add deprecated/demo/beta labels to headers + nav items

packages/documentation-framework/scripts/md/styled-tags.js
**What**: Closes [#9179](https://github.com/patternfly/patternfly-react/issues/9179)
NOTE: Screenshots were taken using these documenation-framework changes locally and applying to @patternfly/patternfly-react's react-docs.
=> fix(documentation-framework): Add missing pf5 styles to generated markdown tables

packages/documentation-framework/components/sideNav/sideNav.js
**What**: Closes #3553
NOTE: Ideally we could use optional chaining here (e.g. `onNavToggle?.()`), however that syntax is not permitted at the moment for this project file.
=> fix(doc-framework): undefined onNavToggle leads to page error

packages/documentation-framework/components/sectionGallery/TextSummary.js, packages/documentation-framework/components/sectionGallery/sectionDataListLayout.js, packages/documentation-framework/components/sectionGallery/sectionGallery.css, packages/documentation-framework/components/sectionGallery/sectionGallery.js, packages/documentation-framework/components/sectionGallery/sectionGalleryLayout.js, packages/documentation-framework/components/sectionGallery/sectionGalleryToolbar.js, packages/documentation-framework/components/sectionGallery/sectionGalleryWrapper.js
Closes #3568 
This PR:
- cleans up bugs that occurred when using `sectionGallery` without illustrations
- fixes bug with gallery page being listed in gallery due to pathPrefix interfering when looking for exact match to slug
- pulls the `SummaryComponent` out into a separate file renamed `TextSummary` and adds it to the grid view in addition to to the existing list view
- add new props to enable/disable both text & images in grid view and list view
- add new prop to set initial layout view (still defaults to grid)
=> enhancements & bug fixes to sectiongallery

packages/documentation-framework/components/sectionGallery/sectionGallery.css, packages/documentation-framework/components/sectionGallery/sectionGallery.js, packages/documentation-framework/components/sectionGallery/sectionGalleryWrapper.js, packages/documentation-framework/templates/mdx.css, packages/documentation-framework/templates/mdx.js, packages/v4/patternfly-docs/patternfly-docs.source.js
Closes #3595 
Preview:  https://patternfly-org-pr-3596-v4.surge.sh/v4/components/label
This PR:
- Updates logic behind `.ws-mdx-content-content` class being excluded on landing pages, and reverts style rule overriding 832px max-width for this class
- Applies new class to landing pages to separately apply max-width but allow override for gallery view to stretch full width
- Updates variable name referenced for header font
=> fix(docs): fixed gallery styles affecting width, font vars

.github/upload-preview.js
Now that the url and repo restructuring is merged, the workflow workaround to account for the old v4 names should no longer be required for the GH build.
=> misc: remove v4 workflow workaround

packages/documentation-framework/templates/mdx.js, packages/documentation-framework/versions.json, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md, packages/documentation-site/patternfly-docs/content/get-started/release-notes-data.js, packages/documentation-site/patternfly-docs/content/get-started/release-notes-table.js, packages/documentation-site/patternfly-docs/content/get-started/release-notes.md, packages/documentation-site/patternfly-docs/patternfly-docs.source.js, yarn.lock
Closes https://github.com/patternfly/patternfly-org/issues/3631
-Adds extensions to the release notes and a blurb about extensions to the release highlights
-adds user feedback documentation
-fixes and updates all other extensions docs (including topology)
=> fix: add extensions docs and release notes

packages/documentation-site/patternfly-docs/content/get-started/upgrade.md
these are all merged into pf now and don't need to be excluded
also `--fix` instead of `-fix`
=> fix(documentation): remove excludes from codemod command

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
fixes https://github.com/patternfly/patternfly-org/issues/3643
Relies upon https://github.com/patternfly/patternfly-react/pull/9342 being merged, which will allow for custom widths/heights to be passed when `<Brand>` has no children.
=> fix(documentation-framework): updated page logo size, props

packages/documentation-framework/package.json, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/get-started/release-notes-data.js, yarn.lock
bumps the latest react/core versions in documentation-site and documentation-framework
also add release note for https://github.com/patternfly/patternfly-react/pull/9342
=> fix: bump versions + add release note

beta-component-promotion/README.md, packages/documentation-framework/package.json, packages/documentation-framework/templates/mdx.js, packages/documentation-framework/versions.json, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/pages/home.js, scripts/latest-versions.sh, yarn.lock
closes https://github.com/patternfly/patternfly-org/issues/3660
closes https://github.com/patternfly/patternfly-org/issues/3661
also updates list of beta components and adds a latest_versions script
pulls in the RCs of all patternFly packages
=> fix: update site in preparation for release

packages/documentation-framework/components/footer/footer.js, packages/documentation-framework/pages/404/index.js, packages/documentation-site/patternfly-docs/content/design-guidelines/charts/donut-chart/donut-chart.md, packages/documentation-site/patternfly-docs/content/design-guidelines/charts/donut-utilization-chart/donut-utilization-chart.md, packages/documentation-site/patternfly-docs/content/design-guidelines/charts/line-chart/line-chart.md, packages/documentation-site/patternfly-docs/content/design-guidelines/charts/pie-chart/pie-chart.md, packages/documentation-site/patternfly-docs/content/design-guidelines/charts/stacked-chart/stacked-chart.md, packages/documentation-site/patternfly-docs/content/design-guidelines/components/form/forms.md, packages/documentation-site/patternfly-docs/content/design-guidelines/components/progress/progress.md, packages/documentation-site/patternfly-docs/content/design-guidelines/components/search-input/search-input.md, packages/documentation-site/patternfly-docs/content/design-guidelines/components/table/table.md, packages/documentation-site/patternfly-docs/content/design-guidelines/components/text/text.md, packages/documentation-site/patternfly-docs/content/design-guidelines/content/writing-design-documentation.md, packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/icons.md
just looked for any url pointing to `/guidelines/...` which doesn't exist anymore. Updated to `/design-foundations/...` or `/charts/...`
closes #3681
=> fix(links): fixed multiple broken linkes

packages/documentation-framework/pages/global-css-variables.md
Closes #3686 
This PR fixes the empty Global CSS Variables table by correcting the `selector` prop passed to the `CSSVariables` component from the `:root` selector previously used for global vars to the current `:where(:root)` selector.
=> fix(docs): fix missing vars in global css vars table

packages/documentation-framework/components/footer/footer.js
Closes #3702 
This PR updates the copyright dates in the footer.  Per research, copyright should include original publish date, or if content has been updated a range from original date through last published date.  As we will continually update docs site, the code has been updated to get the current year and range from 2014 (site creation) through the current year - this will avoid running into the same issue year after year.
=> chore: update copyright to range from 2014 through current year

packages/documentation-site/patternfly-docs/content/design-guidelines/components/breadcrumb/breadcrumb.md
=> docs(breadcrumb): Move placement section of design guidelines to H2.

packages/documentation-framework/components/tableOfContents/tableOfContents.css
Closes #3739 
The jump link styling will still be a bit off when applying `dir="rtl"`, until the Core RTL updates are pulled in.
=> chore(table of contents): updated styling for RTL

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/icons.md
=> docs(icons): updates icons guidelines as part of content audit.

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/documentation-framework/versions.json
Closes #3685 
This PR:
- marks all prior releases in `versions.json` with `hidden: true` to hide them from the version switcher on the V5 site (consumer can still use the external V4 link to go to the archive site to view v4 releases).
- adds logic to hide the "previous releases" section within the version switcher in this case as there are no previous releases that are not hidden, fixing the issue of a section title with no items within in.
=> fix(docs): hid previous v4 releases from version switcher on v5

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
Closes #3621 
Research of common practices did show GDPR/cookie banners loading after page content in DOM order.  This PR moves the banner to after the page content.
=> moved GDPR banner to after page content

packages/documentation-site/patternfly-docs/content/design-guidelines/components/select/select.md
=> Removing the redudancy in the file. Use is described above the text.

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
=> feat(dark-theme): replace dark theme switcher with toggle group

packages/documentation-site/patternfly-docs/content/accessibility/jump-links/jump-links.md
Closes #3807 
Not mentioned in the docs, but looking at our core and react examples, rather than using `aria-label` when the jump links have a visible label, we should consider utilizing `aria-labelledby` instead. Would just require a couple new props in React, and a followup needs to be opened in Core to add the `aria-current` attribute in examples, but interested what others think.
=> chore(JumpLinks): updated a11y docs to match template

packages/documentation-framework/versions.json
Not sure if I added the drag drop to a previous version or if another version was added between my PR and the merge but fixing the drag drop to be on the latest version again.
=> fix(drag drop): add drag drop to 5.1 versions.json

packages/documentation-site/patternfly-docs/content/accessibility/sidebar/sidebar.md
Closes #3811 
We could add a React followup to explicitly expose the props mentioned here, or we could try to automate this for consumers similar to what we're doing in AccordionContent:
https://github.com/patternfly/patternfly-react/blob/b3345c2d7b3dec8702f9d3f179dd4478f3ffdcbb/packages/react-core/src/components/Accordion/AccordionContent.tsx#L43-L51
=> chore(Sidebar): updated a11y docs

.github/workflows/extensions.yml
Updates our github action workflow to add new issues to the project board, not just with an extensions label
=> chore(actions): update github actions to add issues to project board

packages/documentation-site/patternfly-docs/content/accessibility/accordion/accordion.md, packages/documentation-site/patternfly-docs/content/accessibility/expandable-section/expandable-section.md
Closes #3800 
Couple of things to address before this gets merged in:
- In the React implementation we set an aria-labelledby on the content component with a value of the toggle. Essentially an expandable section content will have an accessible name of "Show less", possibly announced as "Show less, region". Which isn't exactly descriptive. I'm wondering if we should be adding aria-labelledby at all (and a role="region"), or if we should recommend providing more descriptive toggle text, e.g. "Show more for [content subject]".
- In React we're also always setting `aria-controls`. Doesn't really hurt to have it, but wondering if we really need it outside teh detached examples where it makes more sense. A detached example could have several other things between the toggle and content for …
=> chore(ExpandableSection): updated a11y docs to match template

packages/documentation-site/patternfly-docs/content/accessibility/code-editor/code-editor.md, packages/documentation-site/patternfly-docs/content/accessibility/tooltip/tooltip.md
Closes #3797 
Also made a quick tweak to Tooltip docs to mention the repercussion of too short an exit delay; I wanted to mention that in a more "universal" section rather than just the React props section.
=> chore(CodeEditor): updated a11y documentation to match template

package.json, packages/documentation-framework/package.json, packages/documentation-framework/versions.json, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md, yarn.lock
Bump for our 5.2.1 patch release.
=> feat(deps): version bump for 5.2.1 release

packages/documentation-site/patternfly-docs/content/accessibility/skip-to-content/skip-to-content.md
=> chore(SkipToContent): updated a11y docs to template

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/documentation-framework/templates/mdx.css, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/pages/home.js
Closes: https://github.com/patternfly/patternfly-org/issues/3901
=> feat: add pf 6 alpha banner to home page and version switcher

packages/documentation-framework/scripts/md/parseMD.js, packages/documentation-framework/templates/mdx.js, packages/documentation-framework/versions.json
Closes #3898 
Adds the templates package to `versions.json` to allow the docs to build successfully. Currently version is set to `1.0.0-alpha.0` but may be changed depending on what number we want to start on (1 vs 5 to match other PF packages).
=> feat(templates): add templates package to versions.json

packages/documentation-framework/components/sideNav/sideNav.css, packages/documentation-framework/components/tableOfContents/tableOfContents.css, packages/documentation-framework/templates/mdx.css, packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.css
Closes https://github.com/patternfly/patternfly-org/issues/3910
=> chore(dark theme styling): fix ws dark theme styles

packages/documentation-site/patternfly-docs/content/accessibility/page/page.md
=> chore(Page): updated a11y docs to new template

packages/documentation-framework/app.js, packages/documentation-framework/components/footer/footer.js, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/documentation-framework/templates/mdx.css
Closes https://github.com/patternfly/patternfly-org/issues/3609
=> chore(footer): Restructure new homepage footer

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js
Updates featured medium articles to include the v6 alpha article.
=> feat(docs): update medium article

packages/documentation-site/patternfly-docs/content/accessibility/tree-view/tree-view.md
Closes #3875 
Some of the additions I've made here currently are not things implemented in either core or React, but either things I noticed were missing or things gleamed from some of [W3's tree view examples](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/). Some of this may depend on if we would want to make such changes, namely:
- `aria-multiselectable`: in React the "active items" of a tree view are intended to be placed into an array, suggesting multiple items can be selected. Currently we don't indicate that to assistive tech.
- A mention about custom interactive content, based on https://github.com/patternfly/patternfly-react/issues/8255 and the link mentioned in that issue
- When a search input must be included (7 root nodes) based on W3's tree view examples (linked above); …
=> chore(TreeView): updated a11y docs to template

packages/documentation-framework/components/autoLinkHeader/autoLinkHeader.js, packages/documentation-framework/components/example/example.js, packages/documentation-framework/templates/mdx.js, packages/documentation-site/package.json, yarn.lock
=> feat(docs): update beta button style

packages/documentation-framework/templates/patternfly-docs/patternfly-docs.source.js, packages/documentation-site/patternfly-docs/patternfly-docs.source.js
Closes #3894.
The newer `__mocks__` directory in react was overriding existing props tables data with an empty array when it went to build the docs out, and the existing functionality for ignoring sets of files for the props data gathering wasn't actually working at all. This PR fixes the syntax for the ignore path matching, and adds mocks to the list.
Components that were affected: `Menu`, `MenuList`, `MenuItem`, `MenuContent`, `MenuGroup`, `Button`, `HelperText`
=> feat(docs): fix for missing props tables

packages/documentation-site/patternfly-docs/content/developer-resources/a11y-scores.js, yarn.lock
Closes #3744 
This PR updates the a11y scorecard with a new report link from 4/23/24 and links to a new epic (#3979) with 24 new bugs.
=> chore(a11y): updated a11y scorecard

packages/documentation-framework/package.json, packages/documentation-framework/scripts/md/parseMD.js, packages/documentation-site/package.json, yarn.lock
Unblocks https://github.com/patternfly/react-topology/issues/183. Towards #3988 
This change comments out the `visit` function which was imported by `unist-util-visit`, which was causing an error in the build step following the upgrade to Typescript 4.7.4.
cc @nicolethoen per our debugging session this afternoon
=> fix(build): bump ts version and fix docs build for v6

packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
=> docs(release-highlights): Adds highlights from patch releases.

packages/documentation-framework/components/example/example.js
Towards #4009 
This PR wraps the window.load listener in a check to see if the page has already completed loading before adding that listener (and if so, adds the page-loaded class).
- This fixes the race condition where that event listener sometimes does not fire in incognito when it is added after the page has loaded.
- Mirrors PR #4012 going into `main` branch.
=> chore(docs): fix page-loaded class

packages/documentation-site/patternfly-docs/content/developer-resources/accessibility-scorecard.md
There was a link that was incorrectly formatted and let to a 404 page
=> fix: Incorrectly formatted link

packages/documentation-framework/templates/mdx.css
fixes https://github.com/patternfly/patternfly-org/issues/4014
I think back to top should overlay everything, similar to skip-to-content. currently when it shows up when the jump links on the right are visible, the back to top button is visible, but clicking on it triggers a click on one of the jump links.
=> fix(docs-framework): adjust back to top z-index

packages/documentation-site/patternfly-docs/content/design-guidelines/content/numerics.md
Changes
- Swap EUR and GBP to match the sign and description at the end
- Correct from `GPB` to `GBP`
=> fix(docs): fix EUR-GBP currency UX writing example

packages/documentation-framework/components/example/example.css, packages/documentation-framework/components/example/example.js, packages/documentation-framework/components/propsTable/propsTable.js, packages/documentation-framework/templates/mdx.js, packages/documentation-site/package.json
Closes: https://github.com/patternfly/patternfly-org/issues/4060
this 'primarily' impacts the component docs/examples pages. The layout for each example on the page is now using Stacks with gutters rather than custom class names.
I had to leave overrides for:
- creating the dark theme switcher at the bottom of full page examples
- modifying the layout of the code editor at the bottom of each example
- beta tags and required stars in the props tables
=> fix: cleaning out example.css

packages/documentation-framework/components/tableOfContents/tableOfContents.css, packages/documentation-site/package.json
Closes: https://github.com/patternfly/patternfly-org/issues/4064
I cannot figure out how to get the mobile jumplinks/table of contents to scroll properly.
I tried to do overflow-y: scroll on the `.ws-toc.pf-m-expanded .pf-v6-c-jump-links__main` but it is clipping the toggle arrow. Very open to suggestions.
=> fix: clean up toc/JumpLinks styling

packages/documentation-framework/pages/404/index.js
Closes #4072 
Inline style rule not needed so removed, along with <p> wrapping component.
=> remove <p> and inline style

packages/documentation-framework/components/sectionGallery/sectionDataListLayout.js, packages/documentation-framework/components/sectionGallery/sectionGallery.css, packages/documentation-framework/components/sectionGallery/sectionGalleryLayout.js, packages/documentation-framework/components/sectionGallery/sectionGalleryToolbar.js, packages/documentation-site/package.json
Closes #4063 
This PR:
- Removes unused/unneeded custom styles for sectionGallery
- Cleans up code for sectionGallery, updates props as needed.
=> chore(docs): sectiongallery - remove unused styles, cleanup code

packages/documentation-framework/components/sectionGallery/sectionGallery.css
Closes #4179 
This PR adds `height: 100%` to the section gallery pages (ex: All components) so that all cards within a row stretch vertically to match the height of the tallest card in the row.
=> fix(docs): gallery cards fill row height

packages/documentation-framework/components/tableOfContents/tableOfContents.css
Closes #4184 
This PR adds text wrapping to table of contents jumplinks to avoid them running off the screen horizontally, and left-aligns text as it defaults to center-justified when wrapping.
=> fix(docs): wrap text on ToC jumplinks

packages/documentation-framework/scripts/md/typecheck.js, packages/documentation-framework/scripts/webpack/prerender.js
To enable https://github.com/patternfly/patternfly-react/pull/10854
=> feat(docs-framework): Add support for next subpaths in react-charts

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
Closes #4174 
This PR updates the light/dark theme toggle at the top of the website to match the example implementation (passing the icon directly rather than wrapped in the <Icon> component) to fix the issue of the icon showing black on a blue background when the button is selected.
=> fix(docs): update theme toggle icon colors

packages/documentation-framework/components/link/link.js, packages/documentation-framework/components/tableOfContents/tableOfContents.js
Closes https://github.com/patternfly/patternfly-org/issues/4085
Related to https://github.com/patternfly/patternfly-react/issues/10860 - scroll selector needed to be updated due to new wrapper component.
This PR updates the scrollable element passed to JumpLinks in the Table of Contents component, as well as references in the Link component (triggers scroll to top of page after link click), to `.pf-v6-c-page__main-container`, fixing:
- Scrollspy not working (active jumplink in the table of contents doesn't change as you scroll page)
- Scrolling down one page then navigating to another page does not scroll back to the top of new page
=> fix(docs): updated scroll selector for jumplinks, router links

packages/documentation-site/patternfly-docs/content/accessibility/checkbox/checkbox.md, packages/documentation-site/patternfly-docs/content/accessibility/radio/radio.md
Closes #4008 and #4187
- For 4008, since React is applying the for/id attributes regardless we really only needed to update the HTML section
- Radio docs didn't exist to this also covers closing 4187
=> chore(Radio): added a11y documentation

packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/accessibility/switch/switch.md
=> chore(Switch): added a11y docs

README.md, package.json, packages/documentation-framework/README.md
Added some info on how to generate screenshots and fix errors after discussion with PF team. Also removed old, out-of-date screenshots, etc. documentation in packages subfolder after discussion with PF team. I took out the Puppeteer, etc. section without discussing it because it doesn't seem to be required anymore. I was able to run this without installing Puppeteer separately.
=> chore(docs): Update READMEs

packages/documentation-site/patternfly-docs/content/get-started/develop.md
Closes #4115 
This PR fixes the incorrect link to react-code-editor on getting started/develop page.
=> fix(docs): fix broken link on get started-develop

package.json, packages/documentation-framework/package.json, packages/documentation-framework/versions.json, packages/documentation-site/package.json, yarn.lock
```
"@patternfly/patternfly": "5.4.0-prerelease.8",
"@patternfly/react-charts": "7.4.0-prerelease.17",
"@patternfly/react-code-editor": "5.4.0-prerelease.35",
"@patternfly/react-core": "5.4.0-prerelease.33",
"@patternfly/react-drag-drop": "5.4.0-prerelease.34",
"@patternfly/react-icons": "5.4.0-prerelease.10",
"@patternfly/react-styles": "5.4.0-prerelease.11",
"@patternfly/react-table": "5.4.0-prerelease.37",
"@patternfly/react-templates": "1.1.0-prerelease.40",
"@patternfly/react-tokens": "5.4.0-prerelease.10",
“@patternfly/react-topology”: "5.4.0-prerelease.13"
“@patternfly/react-console”: "5.1.0-prerelease.2",
“@patternlfy/react-log-viewer”: "5.2.0-prerelease.2",
“@patternfly/quickstarts”: "5.4.0-prerelease.4"
```
=> feat(ver): update to final 5.4 pre-release versions

packages/documentation-framework/components/tableOfContents/tableOfContents.css
It looks like some of the widths changed since v5. This caused flex to stop wrapping the table of contents at the smaller viewports mentioned in https://github.com/patternfly/patternfly-org/issues/4178. The table of contents was still present, but just at the bottom of the screen since the order was 1 (the main content is ordered at 0). Dropping down to this width for the table of contents seems to allow wrapping as expected again.
Should fix https://github.com/patternfly/patternfly-org/issues/4178. I went through every page at 1451px and made sure this jump link width worked ok (main content width appears to be extremely variable).
=> fix(docs): updated width on table of contents

.github/upload-staging.sh, README.md, lerna.json, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
Updated to push to staging instead of v6 staging for patternfly org.
=> chore: Updated to release to staging for aws instead of v6 staging.

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
The isFullHeight menu toggle adds extra padding to the version dropdown.
=> fix(homepage): remove is full height

packages/documentation-framework/components/sideNav/sideNav.js
=> fix(sideNav): Temporarily harcode breakpoint tokem token value

packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
Closes https://github.com/patternfly/patternfly-org/issues/4221 and replaces PR https://github.com/patternfly/patternfly-org/pull/4244, which had build errors I could not fix. 
Integrated the feedback comment as well
=> docs(release-highlights): Add more beta highlights.

packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/content/design-guidelines/components/table/table.md, packages/documentation-site/patternfly-docs/content/design-guidelines/content/numerics.md, packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
Replaces https://github.com/patternfly/patternfly-org/pull/4260 to fix the many build issues. 
---
The original issue mentions adding these details to the numerics page, but I added the bulk of the docs to our typography page instead, and linked to it from numerics (and also table). Can swap this around, though! But I thought it may make more sense for font-related details to live with the other typography info
Also, maybe this would benefit from an image to demonstrate the difference, but I'm struggling to understand what the actual styling difference is (slashed 0 or just a width change?). The "code" text style in Figma doesn't work for me, if that's the same idea
=> docs(design-foundations): Documents tabular font modifier.

packages/documentation-framework/versions.json, packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/patternfly-docs.source.js, yarn.lock
Fixes issue #4251 by reenabling quickstarts.
=> fix: Reenabled patternfly quickstarts.

packages/documentation-site/package.json, packages/documentation-site/patternfly-docs/pages/home.js
=> docs(homepage): Update upgrade card heading.

packages/documentation-site/patternfly-docs/content/design-guidelines/components/page/page.md
Closes #3751 
Very small change -- do we need any additional details? 
Sticky footers don't need drop shadows, right?
=> docs(page): Mention need for drop shadow with sticky page headers.

packages/documentation-site/patternfly-docs/content/get-started/about-patternfly.md
Closes #4307
Need to double check timeline mentioned
=> docs(about-patternfly): Adds information about version support.

packages/documentation-framework/components/cssVariables/cssVariables.js, packages/documentation-framework/components/footer/footer.js, packages/documentation-framework/components/sideNav/sideNav.js, packages/documentation-framework/templates/mdx.js
Closes #4339 
Closes #4176 
Closes #4340 
FYI - Line changes linked due to additional prettier formatting changes.
This PR:
- Fixes console errors:
- error thrown by missing `key` prop in CSSVariables table. (cssVariables.js [line 15](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-364df80da54886753ca572b74c68a1a32893da16c7a4d9c76d762725ff51f228R15))
- error thrown by use of `class` rather than `className` in the site footer. (footer.js [line 270](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-4ffaf2430cb77de5fb6652969a79ce1202dca821889f6ae5358c8adc6ca33dc9R270))
- Hard-codes "Tile" to be deprecated:
- Adds "deprecated" label to the Sidenav item (sideNav.js [line 169](https://github.com/patternfly/patternfly-org/pull/4341/files#diff-8e3c7674b90a7a160ac7 …
=> fix(docs): hardcode Tile deprecation, fix console errors

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js
Closes #4333 
note - because I have to size down the release blog image, it gets slightly blurry. don't think there's a workaround for that since the image is a figma png export, but it's not very noticeable
=> docs(home): Update featured blogs.

.gitignore, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/documentation-site/patternfly-docs/pages/home.js
This fix updates the link the v6 from staging to the official Patternfly.org site.
=> Fixes invalid link for v5.

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js, packages/documentation-framework/templates/html.ejs
Improves the handling of dark mode preferences by respecting the system/browser preference of the user first, and storing the preference in local storage when the user toggles the switch manually in the user interface. This allows the preference to be persisted between other tabs and windows.
Closes #4365
=> fix: improve handling of dark mode preferences

packages/documentation-framework/components/footer/footer.js
Closes [#4383](https://github.com/patternfly/patternfly-org/issues/4383)
=> fix(footer): calendar link

packages/documentation-framework/templates/html.ejs, packages/documentation-site/package.json
fixes https://github.com/patternfly/patternfly-org/issues/4404
=> fix(dark-theme): fixed issue with incorrect color-scheme being applied

.github/workflows-src/partials/build.yml, .github/workflows/pr-preview.yml, .github/workflows/release.yml, README.md
Upgrades the CI to use the latest LTS version of Node.js (v22). Also upgrades the `setup-node` action to the latest version (v4). And enables [Corepack](https://nodejs.org/api/corepack.html) (a pre-requisite for merging #4413).
=> chore: upgrade to Node.js v22.x (LTS) and enable Corepack

packages/documentation-framework/helpers/codesandbox.js
Add victory dependency to chart CodeSandbox examples
Closes https://github.com/patternfly/patternfly-react/issues/11441
=> Bug - Charts - CodeSandbox default imports

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/IconsTable.js
fixes #4449 
before:
```xml
<?xml version="1.0" standalone="no"?>
<span class="pf-v6-c-button__text" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%"><svg class="pf-v6-svg" viewBox="0 0 448 512" fill="currentColor" aria-hidden="true" role="img" width="1em" height="1em" color=""><path d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34zm192-34l-136-136c-9.4-9.4-24.6-9.4-33.9 0l-22.6 22.6c-9.4 9.4-9.4 24.6 0 33.9l96.4 96.4-96.4 96.4c-9.4 9.4-9.4 24.6 0 33.9l22.6 22.6c9.4 9.4 24.6 9.4 33.9 0l136-136c9.4-9.2 9.4-24.4 0-33.8z"></path></svg></span>
```
after:
```xml
<?xml version="1.0" standalone="no"?>
<svg class="pf-v6-svg" viewBox="0 0 448 …
```
=> fix: export valid SVGs in all icons page

packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
=> docs(release-highlights): Adds missing package version links.

packages/documentation-site/patternfly-docs/content/accessibility/helper-text/helper-text.md
Related to https://github.com/patternfly/patternfly-react/pull/11704
=> chore(HelperText): updated a11y docs for SR text

packages/documentation-framework/package.json, yarn.lock
`react-ssr-prepass` version bump is needed for the react-repo to bump to React 19.
Expanding the allowed version to include 19 works with the framework, but the build fails when I do so for the site package. Still investigating that, but it's possible that the react repo or other extensions need to also allow 19 for it.
May wait on merging this until 6.2 release is out and site is updated from that before messing too much with versions.
=> feat(ver): enable react 19 support in framework

packages/documentation-site/patternfly-docs/content/design-guidelines/charts/about/about.md, packages/documentation-site/patternfly-docs/content/developer-resources/dark-theme-handbook.md
Closes #2974 
As a follow up to this PR, I'll need to remove redundant info that I copied from the dark theme handbook.
=> docs(charts): Adds developer notes to about-charts page

packages/documentation-framework/package.json, yarn.lock
Extensions which import PatternFly seem to have problems pulling in React 19 due to the docs framework - trying this to see if it helps.
I tried dropping the docs framework within the extension, but we have code-editor, core, etc. as dependencies. It seems to ship as part of the dependency according to this install trail, so that doesn't help all that much. I verified that 6.2.2, etc. should have 19 support.
```
ralpert@ralpert-mac virtual-assistant % npm install        
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @patternfly/chatbot-root@0.0.0
npm warn Found: react@18.2.0
npm warn node_modules/react
npm warn   dev react@"^19" from the root project
npm warn   30 more (@monaco-editor/react, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer …
```
=> chore(deps): Temporarily allow for React 19 peer dependency

packages/documentation-site/patternfly-docs/content/developer-resources/cli-guidelines.md, packages/documentation-site/patternfly-docs/content/developer-resources/cli-writing.md
This PR adds a new CLI UX Guidelines page under Developer Resources.
The document provides best practices for:
- Naming conventions
- Flags, arguments, and help documentation
- Interactive prompts and default handling
- Output formatting, error messages, and accessibility
It is intended for developers building CLI tooling and UX designers collaborating on technical workflows.
=> Add CLI guidelines to developer resources

packages/documentation-site/patternfly-docs/content/design-guidelines/components/drag-and-drop/drag.md
Closes #4578 
Might need a review from an accessibility pov -- not sure if the language being used is inclusive enough for mouse vs keyboard, but this was a difficult thing to phrase.
=> docs(drag-and-drop): Updates design guidelines for accuracy.

packages/documentation-framework/components/tableOfContents/tableOfContents.css, packages/documentation-framework/components/tableOfContents/tableOfContents.js
Created a new CSS variable to add the `margin-bottom:  45px` to `JumpLinks` component returned by `tableOfContents.js`, making the last jump links item visible regardless of the browser window dimensions. Closes #4579
=> fix(styling): last link in jump links sidenav is now visible

packages/documentation-framework/components/example/example.js, packages/documentation-framework/hooks/useTheme.js, packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
This PR implements a comprehensive theme switcher that provides users with three choices: **System**, **Light**, and **Dark** themes, with proper persistence and synchronization across the entire application.
1. **🖥️ Automatic System Preference Detection**
- Detects user's `prefers-color-scheme` setting automatically
- Dynamically responds to system theme changes in real-time
- Defaults to system preference on first visit
2. **🎯 Tri-State Theme Selection**
- **System**: Follow user's operating system preference
- **Light**: Always use light theme regardless of system setting
- **Dark**: Always use dark theme regardless of system setting
3. **💾 Persistent User Preferences**
- Saves user's theme choice in localStorage
- Persists across page reloads and browser sessions
- Gracefully handles …
=> feat: Enhanced theme switcher with system preference detection and tri-state selection

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js
=> docs(homepage): Update featured blogs.

packages/documentation-framework/components/example/example.js, packages/documentation-framework/scripts/webpack/getHtmlWebpackPlugins.js
Closes: https://github.com/patternfly/patternfly-org/issues/4739
=> fix: remove duplicate source names in full page demo URLs

packages/documentation-framework/components/themeSelector/themeSelector.js
@wise-king-sullyman I tried seeing if Cursor could see a problem with the theme switcher that could be causing the behavior where the selector shows "Display" but it's really set to light or dark. This is what it came up with - full answer below. I can't verify the solution (I can't reproduce it locally and also don't know React 😝 ) but was hoping you'd take a 👀 please and see if any of it looks useful. I tried adding CPU/network throttling in case that triggered it if it's a timing thing, but no luck.
------------------------
Looking at the code, I can see a potential bug in the theme selector logic. Let me analyze the issue:
[1 tool called]
I found the bug! The issue is in the `getThemeDisplayText` function in `themeSelector.js`. Let me trace through the logic:
1. **In `useTheme.js`**: …
=> Potential theme selector fix

packages/documentation-site/package.json, yarn.lock
ChatBot example for transcripts uses file-saver for file downloads. It works fine on extension Surge website. The actual website was throwing "Uncaught TypeError: saveAs is not a function" since file-saver was not a website dependency. Adding the dependency gets rid of the issue.
=> fix(docs): Add file-saver dependency

packages/documentation-framework/versions.json, packages/documentation-site/package.json, yarn.lock
Pre-release versions of Core/React contained a change to CodeEditor that affected ChatBot styles. This new version should adapt to the changes.
=> fix(ChatBot): Update version
