source/get-started/index.html

Cleaned up, edited and changed some of the copy on the Get Started page.

Get Started Copy Updates

---

source/pattern-library/navigation/vertical-navigation/index.md
source/pattern-library/navigation/vertical-navigation/navigation-without-icons.html
source/pattern-library/navigation/vertical-navigation/navigation.html

Modified vert-nav test so code does is not duplicated in multiple places.
For example, both vert-nav examples, as well as the overview/code tabs of patternfly-org.

Modified vert-nav test so code does is not duplicated

---

source/pattern-library/navigation/horizontal-navigation/index.md

Fixing typo - "preferred" vs "prefered"

---

source/_less/patternfly-site.less
source/index.html

Modified carousel controls for featured content section of home page per usability study findings.
PTNFLY-1158 - New PatternFly.org Home Page Dev Update.

Modified carousel controls for featured content

---

source/pattern-library/application-framework/login-page/index.md

Added login-pf class to code snippet.

---

source/_includes/header.html
source/pattern-library/widgets/index.md

Added missing Kebabs, TreeGrid Table, and Fixed Height Accordion examples to widgets page.
Issue #94

Added missing Kebabs, TreeGrid, and Fixed Height Accordion examples

---

source/pattern-library/cards/aggregate-status-card/index.md

Aggregate Status Card: Copyediting #125

Updated design text for aggregate status card.

---

source/pattern-library/navigation/horizontal-navigation/index.md

Overlap with example and "reference markup" expand link #117

Added more height to prevent example from overlapping.

---

source/_includes/header.html
source/_less/patternfly-site.less
source/pattern-library/widgets/index.md

Widgets nav in alphabetical order, but widgets themselves are not #63
Pagination controls are detached from data tables. #135

Reordered widgets in alphabetical order and fixed pagination

---

source/pattern-library/navigation/vertical-navigation/index.md

Vertical menu missing something on the snippet #108

Added missing layout-pf-fixed class to code snippet.

---

source/_layouts/home.html
source/_less/patternfly-site.less

Sticky footer (#32) broke home page.
The home page not a full screen size design #87

Sticky footer (#32) broke home page.

---

source/_less/patternfly-site.less
source/pattern-library/navigation/horizontal-navigation/index.md

Vertical Navigation Page in Beta Site #172

Style changes for horizontal nav broke vertical nav images

---

source/community/monthly-community-meeting/index.md

Community meeting page updated with links to slides and blue jeans
recording.

Community Meeting Page Updated

---

source/community/monthly-community-meeting/index.md

Updated date to next meeting time

Leslie's Branch

---

bower.json
npm-shrinkwrap.json
package.json
source/index.html

@dtaylor113, @jeff-phillips-18 and/or @andresgalante please review.

Bumped version number to 3.5.1

---

publish.sh

Added code comments and included TARGET_BRANCH variable.

Small tweaks to travis publish script.

---

publish.sh

Updating travis build branch name to sync with angular-patternfly branch name.

Updating travis build branch name

---

bower.json
package.json
source/index.html

@dtaylor113 @jeff-phillips-18 or @bleathem please review/merge.

Bumped version number to 3.7.0

---

release.sh

Run "sh ./release.sh -h" to list options

Added a script used to help create releases

---

source/community/monthly-community-meeting/index.md

Updated with July links to deck and recording

Community Meeting Page Updates

---

source/get-started/setup/index.md

fix drunk html special character on setup page

---

.travis.yml
scripts/release.sh

Fixed temp release directory (+1 squashed commit)

Locked version of net-ssh to fix ruby dependency error during deploy.

---

scripts/release.sh

Modified -s switch to skip new clone, clean, and install to rebuild existing repo.

Modified -s switch of release.sh script

---

source/pattern-library/communication/toast-notifications/index.md

updated toast page so that "one toast at time" was removed. It will remain unspecified at this time.

removed detail that only one toast should appear at a time

---

source/_whats-news/2016-08-11.md
source/get-started/contribute/index.md

Update the Contribution Guidelines page per Google doc and include the update in the What's New section.

Update Contribution Guidelines

---

source/pattern-library/navigation/horizontal-navigation/index.md

Fixed link for horizontal annotation image

Bug to fix broken image link

---

source/pattern-library/content-views/list-view/index.md

Also removed the period after the sentence "jump to", since other pages don't have it.

Fixing links to HTML and Angular in List View page.

---

source/get-started/frequently-asked-questions/index.md
source/get-started/index.html

This fixes the 404 errors that appeared due to incorrect file paths.

Fix links that pointed to incorrect files/locations.

---

source/index.html

PTNFLY-1698 What's New Wordpress Template Font Update
Added what's new post from Patternfly blog to home page.
Blog posts must be tagged with the category name: "What’s New on PatternFly.org".
Using CORS to perform cross-site scripting.

Added what's new post from Patternfly blog to home page.

---

source/community/monthly-community-meeting/index.md

Updated the details for the next community meeting detail as well as added links forSeptember's meeting assets.

Community details page update 

---

source/community/monthly-community-meeting/index.md

@dlabrecq @andresgalante mind double checking this? Once merged, I can send an e-mail to the ML.

Updating community meeting page to include October's deck and slides.

---

Gruntfile.js
source/_includes/header.html
source/_layouts/page-pattern.html
source/pattern-library/data-visualization/bullet-chart/index.md
source/pattern-library/data-visualization/timeline/index.md
source/pattern-library/forms-and-controls/advanced-options/index.md
source/pattern-library/forms-and-controls/form-field-layouts/index.md

Some template and build changes required to support the posting.
To verify, check:
- http://localhost:9002/pattern-library/data-visualization/timeline/
- http://localhost:9002/pattern-library/data-visualization/bullet-chart/
- http://localhost:9002/pattern-library/data-visualization/bullet-chart/
- http://localhost:9002/pattern-library/forms-and-controls/advanced-options/

Posted some new designs. 

---

source/get-started/contribute/index.md

@dlabrecq @andresgalante @bleathem

updated formatting and fixed link.

---

source/community/index.html

@andresgalante @bleathem @dlabrecq

Updating links to include slack and GitHub repo. Removed IRC.

---

source/community/monthly-community-meeting/index.md

…with deck and updated date for next meeting. please check @bleathem @dlabrecq @andresgalante

Updating the community meeting page 

---

scripts/publish-ghpages.sh
source/CNAME

Changed the deploy script to allow the deploy to be run locally using the command:
`scripts/publish-ghpages.sh deploy`

Changed the deploy script to allow the deploy to be run locally

---

source/pattern-library/content-views/list-view/index.md

Please see PTNFLY-1974 for details.

Added expand row examples to list view page.

---

source/_includes/head.html

Some pages aren't working since the combobox has a different dependency now. (patternfly@facdc33)
This fixes #330

fix link for combobox

---

source/community/monthly-community-meeting/index.md

Includes: 
- Updated deck and slides for Dec meeting 
- Updated date for next meeting

Updating the community page

---

source/pattern-library/forms-and-controls/find/index.md

PTNFLY-1993 - Find: Post Code
Added find example to code tab per JIRA PTNFLY-1993.
https://patternfly.atlassian.net/browse/PTNFLY-1993

Posting code example for find

---

source/community/index.html

The rhcloud site is live on openshift now - this is ready to go in once approved.
@bleathem @dlabrecq

Change slack link to point at new autoenroll page

---

source/_includes/code/application-framework/login-page/code.md
source/pattern-library/application-framework/login-page/index.md

In this PR I extracted the code example out of the login-page index file, in perpetration for a future migration to a site.md file.

Extracted the code example out of the login-page index file

---

source/community/monthly-community-meeting/index.md

...with jan community meeting info

updating community page

---

.travis.yml
package.json

Removed the deploy to openshift, switched to using the publish-ghpages script in patternfly-eng-publish.
@dlabrecq please confirm the OpenShift deployment removal.

Travis build simplifications

---

source/styles/icons/index.md

Fixed the column width bounce when filtering icons

---

source/styles/icons/index.md

because I can't leave well enough alone.  cc: @LHinson

Added a search icon to the icon-search input

---

source/assets/js/patternfly-site.js
source/index.html

This is staged at:
https://bleathem.github.io/patternfly-org
Test it by navigating around pattern-library pages, selecting overview/design/code tabs, and refreshing the page.  Notice that the active tab is correctly activated. 
cc: @LHinson

Fixes the window.location tab handling

---

source/_includes/code/cards/aggregate-status-card/code.md
source/_includes/code/navigation/horizontal-navigation/code.md
source/_includes/code/navigation/vertical-navigation/code.md
source/pattern-library/communication/notification-drawer/notification-drawer-horizontal-nav.html
source/pattern-library/communication/notification-drawer/notification-drawer-vertical-nav.html
source/pattern-library/content-views/card-view/card-view-multi-select.html
source/pattern-library/content-views/card-view/card-view-single-select.html
source/pattern-library/navigation/horizontal-navigation/horizontal-navigation.html
source/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html
source/pattern-library/navigation/vertical-navigation/vertical-navigation.html

Fix the bug: [Show/hide functionality does not work on Vertical Nav example code when accessed from web site.](https://github.com/patternfly/patternfly/issues/607)

Show/hide functionality does not work on Vertical Nav

---

source/community/monthly-community-meeting/index.md

updating community page to include march slides and recording

Community meeting update

---

source/conference/2017/index.html

@bleathem @LHinson can you please merge this one?

fixes bug on FF

---

source/community/monthly-community-meeting/index.md

updates to community page. will send another PR to make link to react community deck more accessible (currently linking to google slides).

updated to community page

---

source/community/index.html
source/community/monthly-community-meeting/index.md

adding angular community meeting info

community page updates to include info for angular meeting

---

source/community/monthly-community-meeting/index.md

- Fixed bug for React recording 
- Added angular PF deck and recording
- Commented out meeting schedule for now (until new ones are scheduled)

Community page update

---

source/community/monthly-community-meeting/index.md

Adding details for the next react community meeting.

Adding date/time and link for next PF-React community meeting

---

source/community/monthly-community-meeting/index.md

Moved the React community meeting to the list of past meetings, and included links to recording and slides (in dropbox).

updated community meeting details

---

source/assets/js/patternfly-site.js

Hi @LHinson , now you don't have to click "Back button" twice.
@bleathem , please review it.

Fix-bug:Needed to hit the browser Back button twice to go back

---

source/community/monthly-community-meeting/index.md

Adding the August patternfly-ng community meeting to the website page.

Added patternfly-ng community meeting to monthly community meetings page

---

source/community/monthly-community-meeting/index.md

Including meeting info for next PF-R community meeting

included React community meeting info

---

source/community/monthly-community-meeting/index.md

Getting the Angular PatternFly Community Meeting info up on the site.
@LHinson @bleathem

Adding Angular Community Meeting Info

---

source/community/monthly-community-meeting/index.md

Updating the community meeting page to provide more context regarding our various community meetings.
@beanh66  interested in reviewing this one?

Updating the community meeting

---

source/community/monthly-community-meeting/index.md

Adding Angular PatternFly Community Meeting slides and recording to the community page. 
@LHinson Please review!

Adding Angular PatternFly Community Meeting slides and recording

---

source/_includes/code/application-framework/launcher/code.md

updating the launcher includes so that it does not show login page

---

source/_includes/code/application-framework/launcher/code.md

adding that expand and collapse for the code sample for app launcher

---

package.json

Fix the bug mentioned by deernano in https://github.com/patternfly/patternfly/issues/745

timepicker doesn't work on patternfly.org

---

source/_less/patternfly-site.less

@bleathem @LHinson , this PR is targeted to the issue -- https://github.com/patternfly/patternfly-org/issues/467

fix-bug: input boxes of widgets overlay the navigation bar

---

source/assets/js/patternfly-site.js

Hi @bleathem , this PR is targeted to issue -- [Can not navigate to the right widget section](https://github.com/patternfly/patternfly-org/issues/466)

fix-bug : Can not navigate to the right widget section

---

source/_includes/head.html

Fixing display of brand image in info tip navbar

---

source/_includes/code/communication/wizard/code.md

This PR is targeted to fix the [issue](https://github.com/patternfly/patternfly-design/issues/448). @bleathem , please review :)

fix-bug: Wizard Angular Code Tab is blank

---

source/_includes/head.html
source/_includes/header.html
source/pattern-library/index.md
source/pattern-library/widgets/index.md

Remove Timepicker from Forms and Controls and add to Widgets section.
This PR is targeted to the [task](https://patternfly.atlassian.net/browse/PTNFLY-2298)

Add Timepicker to the Widgets page

---

source/pattern-library/widgets/index.md

This is PR is targeted to the issue https://github.com/patternfly/patternfly/issues/644

Kebab example should be Headline caps

---

package.json

Bumped patternfly-eng-release version to sync with latest

Bumped patternfly-eng-release version

---

Gruntfile.js
package.json
source/_config.yml

- Dynamically build and record the jekyll config file so that it can be parsed by the publish script
- Skip loading the grunt-cli module when loading all grunt modules 
- Added an option to skip the repos update

Gruntfile.js updates to support automated build

---

.dockerignore
Dockerfile
Gruntfile.js
README.md
package.json

See the README for instructions on using Docker to develop the site

Added a Dockerfile to support site development using docker

---

source/community/monthly-community-meeting/index.md

@LHinson Just updating the Community site with the info for our next Angular PF community meeting in November. Please review, thanks!

Adding Angular PatternFly Community Meeting Details for November

---

package.json

Modified patternfly-eng-release to ensure the patternfly version is bumped properly during an automated release.

Ensures the patternfly version is bumped properly

---

source/community/monthly-community-meeting/index.md

Adding links to slides and recording from most recent Angular PF community meeting 
@LHinson please review!

Adding past Angular community meeting slides and recording links

---

source/community/monthly-community-meeting/index.md

Also moves listing for the PF-React community meeting to the list of past meetings.

Adds links to slides and recording for PF-R to Community page

---

source/assets/js/patternfly-site.js
source/pattern-library/widgets/index.md

This PR is targeted to fix issue https://github.com/patternfly/patternfly/issues/846
Here's the **[Demo](https://rawgit.com/dabeng/patternfly-org/popover-close-dist/_site/pattern-library/widgets/#popover)** page.
@jeff-phillips-18 @cliffpyles @matthewcarleton please review :)

fix(popover): Close (X) icon should toggle button for popovers

---

source/_includes/code/application-framework/launcher/code.md

Renaming variables to align with PatternFly master.
Close #520

fix variable names in launcher example

---

source/community/monthly-community-meeting/index.md

Adding links to the recording and slides for the community meeting we had last week.

Add links to pf-react community meeting

---

package.json
source/_includes/head.html

Fixes https://github.com/patternfly/patternfly-org/issues/530

fix(build): use cdn for bootstrap slider to make the size smaller

---

source/community/monthly-community-meeting/index.md

Updated community meeting page to include bluejeans info and link to agenda

Add details for next pf-react meeting

---

source/community/monthly-community-meeting/index.md

Updated for April, Archived March

Community Meeting Updates

---

package.json

This PR is targeted to fix the issue #534.
@amarie401 @jeff-phillips-18 . please review this PR whenever you get the chance.

chore(security vulnerability): Fix security vulnerabilities issue

---

source/_includes/code/content-views/tree-list-view/code.md
source/pattern-library/content-views/tree-list-view/tree-list-view-multiple-child-expansion.html
source/pattern-library/content-views/tree-list-view/tree-list-view-single-child-expansion.html

Expose tree list view demo on patternfly.org site. @dgutride Please review this PR 😊
The Travis CI build will succeed after [PR993](https://github.com/patternfly/patternfly/pull/993) is merged firstly

chore(tree-list-view): add tree-list-view to patternfly.org

---

source/community/monthly-community-meeting/index.md

We rescheduled our meeting for April 25.

Update date for next pf-r meeting

---

source/_includes/code/forms-and-controls/inline-edit/code.md
source/_includes/head.html

* This PR introduces the inline-edit example to pf-org
Fixes https://github.com/patternfly/patternfly-org/issues/556
* `code.md` introduced 
* [preview here](https://rawgit.com/amarie401/patternfly-org/inline-edit-dist/_site/pattern-library/forms-and-controls/inline-edit/#code)

Inline edit example for pf-org

---

source/styles/color-palette/index.md

This PR is targeted to fix issue #275.
This is [Demo](https://rawgit.com/dabeng/patternfly-org/color-palette-dist/_site/styles/color-palette/) page.
@dgutride Please review this PR whenever you get the chance 😊

fix(color palette): Tooltips for colors on color palette are not dismissable

---

source/styles/icons/index.md

This PR is targeted to fix issue #459 .
This is the [Demo](https://rawgit.com/dabeng/patternfly-org/first-4col-dist/_site/styles/icons/) page.
@mcarrano   @dgutride Please review the PR whenever you get the chance 😊

fix(icons table): Copy to clipboard should apply to first 4 columns

---

source/community/monthly-community-meeting/index.md

Updated the community meeting page with links to the bluejeans recording for the latest pf-react community meeting.

Update Community Meeting page with links for latest pf-react meeting

---

source/_includes/code/content-views/table-view/code.md

This PR is targeted to fix issue #514 . I refer to the [Data Tables widget](http://www.patternfly.org/pattern-library/widgets/#data-tables) and put forward this solution.
This is the [Demo](https://rawgit.com/dabeng/patternfly-org/table-view-gap-dist/_site/pattern-library/content-views/table-view/#code) page.
@dgutride  @amarie401 Please review the PR whenever you get the chance 😊

fix(table view): Remove unexpected gap in table view

---

source/_includes/code/forms-and-controls/inline-edit/code.md
source/pattern-library/content-views/list-view/list-view-inline-edit.html

This PR is used to add "inline edit in list view" demo to code tab section of inline edit pattern.
Here's the [demo page](https://rawgit.com/dabeng/patternfly-org/dist-ie-list-view/_site/pattern-library/forms-and-controls/inline-edit/#code).
@mcarrano @amarie401 @dgutride Could you review this PR whenever you got the chance 😊

chore(inline edit): Add inline edit for list view to patternfly.org

---

source/_includes/code/forms-and-controls/date-and-time/code.md
source/_includes/head.html

This PR is targeted to provide code section for "date and time" on patternfly.org site.
Here's the [demo page](https://rawgit.com/dabeng/patternfly-org/dist-date-and-time/_site/pattern-library/forms-and-controls/date-and-time/#code).
@mcarrano @dgutride @amarie401 Could you review this PR whenever you got the chance 😊

chore(date and time): update the Code page in the new Date and Time pattern

---

source/_includes/code/navigation/vertical-navigation/code.md
source/pattern-library/navigation/vertical-navigation/vertical-navigation-primary-only.html

This PR is targeted to fix issue #286 .
Here's the [demo](https://rawgit.com/dabeng/patternfly-org/dist-masthead/_site/pattern-library/navigation/vertical-navigation/#code) page.
@dgutride @amarie401 Would you like to review this PR whenever you have time ?

fix(vertical nav): Add primary navigation code example

---

source/community/monthly-community-meeting/index.md

Updates community meeting page with links from last pf-react community meeting.

Add pf-react community meeting links

---

source/get-started/frequently-asked-questions/index.md

updates to FAQ

---

source/get-started/index.html

fix typos on get started page

---

source/get-started/frequently-asked-questions/index.md

Fixed FAQ links so if click the question, it will go down to the answer.

fix links to match questions

---

source/get-started/frequently-asked-questions/index.md

added anchor links and deleted some outdated info

added anchor links and deleted some outdated info

---

source/get-started/frequently-asked-questions/index.md

fixes https://github.com/patternfly/patternfly-org/issues/648

fix(faq): fix links to widget and pattern library

---

packages/patternfly-4/src/content/get-started/about-pf.md
packages/patternfly-4/src/content/get-started/getstarted-dev.md
packages/patternfly-4/src/content/get-started/gettingstarted-design.md

Added new getting started content for devs/design as well as an overview/about section. 
Let me know if I've done this right. I had a bit of a struggle with switching branches.

added draft get started content

---

packages/patternfly-4/src/content/design-guidelines/content/voiceandtone.md
packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/template/design.md

Fixed broken links in content docs

fixed broken links in content docs

---

packages/patternfly-4/src/content/get-started/about-pf.md
packages/patternfly-4/src/content/get-started/getstarted-dev.md
packages/patternfly-4/src/content/get-started/gettingstarted-design.md

Updated get started content with review comments from Amy Glass. Also updated URLs.

updated getting started content based on review from a. glass

---

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json
packages/patternfly-4/content/get-started/get-started-navigation.json
packages/patternfly-4/content/main-navigation.json

Updated navigation items to reflect capitalization standards and changed some nav items to reflect topic title changes.

updated nav to follow caps standards

---

packages/patternfly-4/content/documentation/about-modal.md
packages/patternfly-4/content/documentation/aboutmodalbox.md
packages/patternfly-4/content/documentation/accordion.md
packages/patternfly-4/content/documentation/alert-group.md
packages/patternfly-4/content/documentation/alert.md
packages/patternfly-4/content/documentation/application-launcher.md
packages/patternfly-4/content/documentation/avatar.md

These are the initial set of short descriptions (I just did the A's) to test how these can be inserted into the related component pages.

Add initial short descriptions for demo and testing.

---

packages/patternfly-4/src/components/footer/footer.js
packages/patternfly-4/src/components/footer/footer.scss
packages/patternfly-4/src/components/layout.js

Update the footer to sit outside of the page component, allowing it to render above the sidenav.

fix(footer): update footer placement

---

packages/patternfly-4/content/design-guidelines/content/grammarandterminology.md

Added date and time information to the content standards

added date and time standards

---

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json

Updating JSON to add the Data Input to design guidelines nav

Add 'Data Input' to nav

---

packages/patternfly-4/src/components/footer/footer.js

Fixes issue https://github.com/patternfly/patternfly-org/issues/783

fix(footer): add additional links to footer

---

packages/patternfly-4/src/pages/index.js

Fix copy errors on the homepage, found during review.

fix(copy): fix copy errors on homepage

---

packages/patternfly-4/src/components/PreviewToolbar/styles.scss
packages/patternfly-4/src/components/_core/Documentation/SideNav.js
packages/patternfly-4/src/components/_core/Documentation/index.js
packages/patternfly-4/src/components/_core/Documentation/styles.scss
packages/patternfly-4/src/components/_core/Example/core-preview.scss
packages/patternfly-4/src/components/_core/Example/index.js
packages/patternfly-4/src/components/_core/Example/styles.scss
packages/patternfly-4/src/components/_core/GeneratedSource/styles.scss
packages/patternfly-4/src/components/_core/Preview/styles.scss
packages/patternfly-4/src/components/_react/Documentation/Documentation.styles.js
packages/patternfly-4/src/components/_react/Documentation/SideNav.js
packages/patternfly-4/src/components/_react/Documentation/index.js
packages/patternfly-4/src/components/_react/Documentation/styles.scss
packages/patternfly-4/src/components/css-variables.js
packages/patternfly-4/src/components/example/example.styles.js
packages/patternfly-4/src/components/example/liveDemo.js
packages/patternfly-4/src/components/example/liveDemo.styles.js
packages/patternfly-4/src/components/layout.css
packages/patternfly-4/src/components/switcher/index.js
packages/patternfly-4/src/components/switcher/styles.scss
packages/patternfly-4/src/styles/_navigation.scss
packages/patternfly-4/src/styles/_overrides.scss
packages/patternfly-4/src/templates/markdownPageTemplate.js
packages/patternfly-4/src/templates/markdownPageTemplate.scss
packages/patternfly-4/src/workspace.scss

This PR updates the below items to match the latest designs.
- Update the Component pages
- Alter vertical navigation styles
- Change background of navigation and hover animations

Update Component pages to match new designs

---

packages/patternfly-4/src/components/footer/footer.js

fixes https://github.com/patternfly/patternfly-org/issues/793

fix(footer): update links in footer

---

packages/patternfly-4/src/components/layout.js
packages/patternfly-4/src/styles/_search.scss
packages/patternfly-4/src/workspace.scss

related to https://github.com/patternfly/patternfly-org/issues/755

fix(search): Search styling updates

---

packages/patternfly-4/content/get-started/getstarted-dev.md

Reorganized get started content so React would appear first.
Updated configuration info in React section.
@seanforyou23 - can you take a look and just let me know if we need to add or change anything else in this section? 
Thanks!

flipped get started content, updated config examples

---

packages/patternfly-4/content/get-started/about-pf.md
packages/patternfly-4/content/get-started/getstarted-dev.md
packages/patternfly-4/content/get-started/gettingstarted-design.md

Made some small changes to.. 
- Remove content that was displaying on the site but should actually have been commented out
- Fix spacing issues
- Add yarn as a package manager option

made formatting updates to getting started content

---

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json
packages/patternfly-4/content/design-guidelines/usage-and-behavior/modal/design.md

Made updates for terminology, capitalization errors, and some small style issues.

updates to modal dialog docs

---

packages/patternfly-4/src/pages/documentation/core/css-variables.js
packages/patternfly-4/src/pages/documentation/react/css-variables.js

I added CSS variables documentation to the CSS variables grid. I'm not sure how to preview this content. Adding Adam and Christie to review while Joachim is out.

added CSS variables documentation to the vars grid

---

.circleci/config.yml
.circleci/upload_preview.sh
.travis.yml
package.json
packages/patternfly-4/gatsby-node.js
yarn.lock

build(previews): add deploy previews

---

packages/patternfly-4/content/get-started/accessibility-guide.md
packages/patternfly-4/content/get-started/get-started-navigation.json
packages/patternfly-4/src/components/content/icons.scss
packages/patternfly-4/src/templates/contentTemplate.js
packages/patternfly-4/src/templates/template.scss

Add the Accessibility Guide from pf4.patternfly.org to the new site.
Related to issue https://github.com/patternfly/patternfly-org/issues/806

feat(accessibility): add accessibility guide

---

packages/patternfly-4/src/styles/_navigation.scss

fixes issue https://github.com/patternfly/patternfly-org/issues/875

fix(nav): align link background to vertical nav

---

packages/patternfly-4/src/components/footer/footer.js
packages/patternfly-4/src/components/footer/footer.scss

Update layout, spacing, and responsiveness of the footer and associated content. Replace hover styles with Brand defined styles and simplify paddings/margins surrounding content.
Fixes issue https://github.com/patternfly/patternfly-org/issues/866

fix(footer): update layout, spacing, content

---

packages/patternfly-4/src/components/switcher/styles.scss

fixes https://github.com/patternfly/patternfly-org/issues/870

fix(switcher): fix alignment of switcher on firefox

---

packages/patternfly-4/gatsby-config.js
packages/patternfly-4/package.json
packages/patternfly-4/src/components/_core/Example/index.js
packages/patternfly-4/src/components/_react/liveEdit.js
packages/patternfly-4/src/components/example/liveDemo.js
yarn.lock

Fixes #979, Fixes #960, Fixes #942

fix(images): fix image loading and remove theme switcher temporarily

---

packages/patternfly-4/src/templates/template.scss

fix page padding for mobile

---

packages/patternfly-4/src/components/_core/Example/styles.scss

update label styles

---

packages/patternfly-4/src/workspace.scss

change anchor link color to black

---

packages/patternfly-4/src/components/footer/footer.js

Close #995 
@rachael-phillips can you create a follow up issue for the pf3 blog inside of our new navigation and/or the redesign of the new blog

add blog link

---

packages/patternfly-4/src/pages/index.js
packages/patternfly-4/src/styles/_navigation.scss

fix footer links

---

packages/patternfly-4/src/components/content/iconCard.js
packages/patternfly-4/src/components/content/icons.js

make popover inline

---

packages/patternfly-4/content/contribute/contribute-about.md
packages/patternfly-4/content/contribute/contribute-designers.md
packages/patternfly-4/content/contribute/contribute-developers.md

updates contribution guidelines:
1. h1s on each page
2. bolded steps
3. updated a link for the project board

contribute guidelines updates

---

packages/patternfly-4/plugins/gatsby-transformer-react-docgen-typescript/gatsby-node.js

Was looking in the wrong path for the compiled JS.

fix(props): fix prop table for TS props

---

packages/patternfly-4/src/components/content/iconCard.js

make the open/close behavior a little smoother

icons: tweak open/closing

---

packages/patternfly-4/src/components/content/iconCard.js

fix arrow on popover

---

packages/patternfly-3/source/_includes/header.html
packages/patternfly-3/source/_less/patternfly-site.less

When merged, the banner will start to show on the PF3 homepage

merge to enable the PF3 banner

---

packages/patternfly-4/content/get-started/getstarted-dev.md

added javascript branch info to get started docs

---

packages/patternfly-4/src/components/switcher/styles.scss

change switch to the correct color

---

packages/patternfly-4/_repos/react-core/src/components/Tooltip/Tooltip.md
packages/patternfly-4/_repos/react-core/src/components/Wizard/Wizard.md

Ultimately we want to fix this upstream, but doing it here in the short term.
Closes: #1055

temporary react example changes

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/charts/design.md

added donut chart img back to usage & behavior guidelines
closes #1063

reveal donut chart example on charts usage & behavior

---

packages/patternfly-4/content/design-guidelines/styles/typography.md
packages/patternfly-4/src/components/content/typography.js

add vars to type page

---

packages/patternfly-4/content/design-guidelines/styles/colors.mdx
packages/patternfly-4/content/design-guidelines/styles/spacers.md

fix content links on colors and spacers pages

---

packages/patternfly-4/gatsby-config.js
packages/patternfly-4/package.json
yarn.lock

There will be another PR to track outbound links

add google analytics support

---

.travis.yml

build(s3): also upload to latest folder

---

packages/patternfly-4/src/components/switcher/index.js
packages/patternfly-4/src/components/switcher/styles.scss

Close #850 
@jschuler or @redallen could one of you help direct the selects to the routes, I'm not sure how to 
:)

Replace Switch with Select

---

packages/patternfly-4/src/components/LinkPreview/LinkPreview.scss

fix(preview): left align fullscreen examples

---

packages/patternfly-4/content/design-guidelines/content/voiceandtone.md

fix(404 error): Fixed 404 error for accessibility-guide link

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/buttons-and-links/design.md

Fixed content link
closes #1156

Fixed broken link

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/modal/design.md

fix(link ref errors): fixed link errors for modal dialog info

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/alerts-and-notifications/design.md

fix(404 error): Fixed 404 error for alert group link

---

packages/patternfly-4/gatsby-config.js

mobile app background and splash colors

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/lists-and-tables/design.md

Added usage guidelines for sort based on @KendraMar 's suggestions

Add usage guidelines for sort component

---

packages/patternfly-4/content/get-started/getstarted-dev.md

Fixed 3 typos on PatternFly manual with instructions
Closes #1123

typos in manual

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/modal/design.md
packages/patternfly-4/src/components/content/typography.js

 fix(typography spacers): changed colors for consistency among spacers

---

packages/patternfly-4/content/design-guidelines/styles/colors.mdx

switch code blocks around

---

packages/patternfly-4/content/design-guidelines/styles/typography.md
packages/patternfly-4/src/components/content/typography.js

fix typography page breaking on mobile

---

packages/patternfly-4/content/design-guidelines/styles/spacers.md

fix(spacers): remove width

---

packages/patternfly-4/content/contribute/contribute-designers.md

Removed a word to fix the sentence 
[ closes issue #1202 ]

Fixed a typo

---

packages/patternfly-4/content/get-started/about-pf.md
packages/patternfly-4/content/get-started/accessibility-guide.md
packages/patternfly-4/content/get-started/getstarted-dev.md
packages/patternfly-4/content/get-started/gettingstarted-design.md
packages/patternfly-4/content/get-started/migrate.md

fixes on PF4 Getstarted tab
(fixes issue #1198 )

fixes on Get Started tab

---

packages/patternfly-4/src/components/_core/Documentation/index.js
packages/patternfly-4/src/pages/documentation/core.js
packages/patternfly-4/src/templates/contentTemplate.js

Closes: https://github.com/patternfly/patternfly-org/issues/1102

fix browser tab titles

---

packages/patternfly-4/content/design-guidelines/styles/icons.md

Updated link from pf3 icon file to pf4 icon file 
(fixes issue #1185 )

fixed link to pf4 icon file

---

packages/patternfly-4/src/components/content/icons.js

fix(icons): remove empty state button

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/charts/design.md
packages/patternfly-4/content/design-guidelines/usage-and-behavior/data-input/design.md

Fixed broken links on charts design guidelines page, removed components in data input design guidelines that have not yet been made and the designs are not correct
Closes #1239

fixing minor content issues

---

packages/patternfly-4/src/workspace.scss

add break-word to table cells

---

packages/patternfly-4/src/_typography.scss

change specificity for heading styles in website

---

packages/patternfly-4/src/pages/index.js

replace title text with paragraph text

---

packages/patternfly-4/src/components/_core/Documentation/index.js

fix(html): add class pf-m-grid to tables

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/modal/design.md

fix(modal): add aria-label to icons to fix a11y

---

packages/patternfly-4/content/design-guidelines/styles/typography.md

fix(typography): fixed a11y issues (iss1294)

---

packages/patternfly-4/src/components/content/AutoLinkHeader.js
packages/patternfly-4/src/pages/index.js
packages/patternfly-4/src/workspace.scss

Closes: https://github.com/patternfly/patternfly-org/issues/1374

add anchor links to two headings on homepage

---

packages/patternfly-4/gatsby-node.js
packages/patternfly-4/src/components/_core/Documentation/SideNav.js
packages/patternfly-4/src/templates/mdxPF4Template.js

Closes #1247.
Preview: https://patternfly-experimental.surge.sh

Add experimental components pages

---

packages/patternfly-4/src/styles/_homepage.scss

fix(a11y): fixed color contrast on homepage (iss1351)

---

packages/patternfly-4/src/pages/index.js

Removed the 4 from the button label on the home page.

removed 4 from button label

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/forms/design.md

fix(forms): fixed a11y issues on forms page(iss1298)

---

packages/patternfly-4/content/design-guidelines/usage-and-behavior/charts/design.md
packages/patternfly-4/src/styles/_homepage.scss

fix(charts): fixed a11y issues on charts page(iss1296)

---

.travis.yml

install setuptools

---

packages/patternfly-4/content/design-guidelines/styles/typography.md

Updated the copy on the typography page to reflect the changes to Red Hat font outlined in this document: https://docs.google.com/document/d/1UgzFRv0ZrYv4EzsaxrUEw_r4E5QerC6mLNzSKFIIi6g/edit?usp=sharing 
@jschuler will update the typography being displayed in the text examples to reflect the updates.

updated copy in typography page

---

packages/patternfly-4/gatsby-node.js
packages/patternfly-4/src/templates/mdxPF4Template.js

add the opt in alert

---

packages/patternfly-3/package.json
packages/patternfly-4/package.json
yarn.lock

chore(deps): update patternfly3 deps

---

packages/patternfly-4/src/workspace.scss

Fixes: https://github.com/patternfly/patternfly-org/issues/1455

fix(css): add iframe override for the qualtrics survey

---

packages/patternfly-4/content/design-guidelines/styles/spacers.md

fix(#1368): fixed double dashes in spacer variables

---

packages/patternfly-4/content/design-guidelines/design-guidelines-navigation.json
packages/patternfly-4/content/design-guidelines/styles/typography.md
packages/patternfly-4/content/documentation/core/red-hat-font.md
packages/patternfly-4/content/documentation/react/red-hat-font.md
packages/patternfly-4/content/main-navigation.json
packages/patternfly-4/gatsby-node.js
packages/patternfly-4/src/components/_core/Documentation/SideNav.js
packages/patternfly-4/src/components/_react/Documentation/SideNav.js
packages/patternfly-4/src/components/content/typography.js
packages/patternfly-4/src/components/switcher/index.js
packages/patternfly-4/src/templates/contentTemplate.js

Also default to the Release notes pages

move Red Hat font page into /documentation

---

packages/patternfly-4/content/documentation/core/overview/red-hat-font.md
packages/patternfly-4/content/documentation/react/overview/red-hat-font.md
packages/patternfly-4/gatsby-node.js
packages/patternfly-4/src/components/_core/Documentation/SideNav.js
packages/patternfly-4/src/components/_react/Documentation/SideNav.js
packages/patternfly-4/src/pages/documentation/core/overview/css-variables.js
packages/patternfly-4/src/pages/documentation/core/overview/notes.js
packages/patternfly-4/src/pages/documentation/react/overview/css-variables.js
packages/patternfly-4/src/pages/documentation/react/overview/notes.js

overview categories

---

packages/patternfly-4/src/templates/mdxPF4Template.js

for markdown rendered paragraphs in component pages

add paragraph spacing

---

packages/patternfly-4/content/design-guidelines/content/grammarandterminology.md
packages/patternfly-4/content/design-guidelines/usage-and-behavior/data-input/design.md
packages/patternfly-4/content/design-guidelines/usage-and-behavior/embedded-assistance/design.md
packages/patternfly-4/content/design-guidelines/usage-and-behavior/toolbar/design.md
packages/patternfly-4/src/templates/contentTemplate.js

fix(docs): fixed broken links & allowed mixed case links

---

packages/patternfly-4/content/get-started/getstarted-dev.md

fix(docs): added PF Base CSS notes from github readme

---

.circleci/config.yml
.circleci/upload-preview.sh
.circleci/upload-staging.sh
.gitignore
package.json
packages/patternfly-4/gatsby-config.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/globalContext.js
packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout.css
packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout.js
packages/patternfly-4/gatsby-theme-patternfly-org/versions.json
scripts/writeV3Redirects.js
scripts/writeVersionPrefix.js

Closes #1398
Edit: I need to test this on master so merge away @evwilkin and I'll iterate and backfill tomorrow

add site versioning

---

packages/patternfly-4/src/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md

Clean up broken links on this page: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection
Closes https://github.com/patternfly/patternfly-org/issues/1530

Fix broken links in Bulk Selection guidelines

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/banner/banner.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/cssVariables/cssVariables.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/example/exampleToolbar.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/footer/footer.js
packages/patternfly-4/gatsby-theme-patternfly-org/components/propsTable/propsTable.js
packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.css
packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js
yarn.lock

Update documentation for accessibility

---

packages/patternfly-4/src/content/design-guidelines/content/grammar-and-terminology.md

Made the changes discussed for sentence case guidelines.
[Fixes #1423]

sentence case guideline changes

---

packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js

Added in 'description' for property to GraphQL query.

adding description to QraphQl query.

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js
packages/patternfly-4/gatsby-theme-patternfly-org/helpers/codesandbox.js

For codesandboxes.
cc: @ddonahue007

import svgs from mdxScope

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/commonComponents/commonComponents.css
packages/patternfly-4/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.css
packages/patternfly-4/src/content/design-guidelines/styles/typography/typography.css

fix(docs): namespaced gatsby css to to fix full screen examples

---

.circleci/config.yml
packages/patternfly-4/gatsby-theme-patternfly-org/versions.json
packages/patternfly-4/package.json
yarn.lock

Release 2020.01

---

package.json
packages/patternfly-4/gatsby-browser.js

Round one of bugfixes for staging.patternfly.org:
- Add experimental CSS files
- Fix broken HTML CSS assets

chore(2020.01): bugfixes

---

.circleci/upload-staging.sh
packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js

use pointerEvents: 'all'

---

packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.css
packages/patternfly-4/src/content/design-guidelines/styles/icons/icons.md
packages/patternfly-4/src/content/design-guidelines/styles/spacers/spacers.css
packages/patternfly-4/src/content/design-guidelines/styles/typography/typography.css

Fix(docs): update markdown spacing

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/sideNav/sideNav.css

fixes https://github.com/patternfly/patternfly-org/issues/1662

fix(sidebar): adjust spacing so content in masthead and sidebar align

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.css
packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.css

fix pre styles

---

packages/patternfly-4/gatsby-theme-patternfly-org/components/example/example.js

use valid value for non-svgs

---

packages/patternfly-4/gatsby-transformer-react-docgen-typescript/package.json

Publish gatsby-transformer-react-docgen-typescript

make package public

---

packages/patternfly-4/gatsby-theme-patternfly-org/helpers/codesandbox.js

Closes https://github.com/patternfly/patternfly-next/issues/2378

feat(codesandbox): add empty style.css

---

.circleci/config.yml

Pay attention to https://circleci.com/pricing/
**Old times:**
(Total time 8:28)
Paid credits:
xlarge * (build_org + build_react) = 100 * 6.42m = 642 credits
large * (build_next) =  20 * 3.33m = 66.6 credits
Total credits: 708.6 credits
**New times:**
(Total time: 7:48)
Paid credits:
large * (build_org) = 20 * 3.83 = 76.66
medium * (build_react) = 10 * 3.5 = 35
Total credits: 111.66 credits

try to reduce CI costs

---

packages/patternfly-4/gatsby-theme-patternfly-org/gatsby-node.js
packages/patternfly-4/gatsby-theme-patternfly-org/templates/mdx.js
packages/patternfly-4/gatsby-transformer-react-docgen-typescript/gatsby-node.js

add view page source link

---

.circleci/config.yml
package.json
packages/patternfly-4/gatsby-config.js
yarn.lock

bumping gatsby-theme to latest master

---

packages/patternfly-4/gatsby-theme-patternfly-org/versions.json
yarn.lock

bump for 2020.03

---

.circleci/config.yml
packages/patternfly-4/gatsby-theme-patternfly-org/gatsby-node.js

invalidate PR number cache

---

.circleci/config.yml
.circleci/upload-preview.sh
.gitmodules
package.json
packages/patternfly-3/Gruntfile.js
packages/patternfly-4/gatsby-config.js
packages/patternfly-4/gatsby-theme-patternfly-org/gatsby-node.js
packages/patternfly-4/gatsby-theme-patternfly-org/helpers/codesandbox.js
packages/patternfly-4/gatsby-theme-patternfly-org/package.json
packages/patternfly-4/package.json
scripts/checkoutVersion.js
yarn.lock

TODO: patternfly-3/repos/** and patternfly-4/patternfly-react. Then no more submodules!!

remove patternfly-next submodule in favor of NPM

---

packages/patternfly-3/Gruntfile.js

Fix accidentally broken 3rd party deps

copy node_modules again

---

README.md

Updates for all the changes going on.

chore(readme): remove submodule part from README

---

packages/gatsby-theme-patternfly-org/components/footer/footer.js
packages/gatsby-theme-patternfly-org/gatsby-config.js
packages/gatsby-theme-patternfly-org/pages/404.js
packages/v4/gatsby-config.js
packages/v4/src/pages/get-in-touch.js
packages/v4/src/pages/index.js

chore(gdpr): temporarily disable banner

---

.circleci/config.yml

circleci now makes an ssh dir for us

---

packages/v4/package.json
yarn.lock

add demos to core

---

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

https://github.com/patternfly/patternfly-react/pull/3995 broke this. I'll go back and fix it in patternfly-react...

fix dropdownItem's href

---

packages/v4/src/content/get-started/about.md
packages/v4/src/content/get-started/get-started.css

Closes #1774 - this PR adds a list of supported browsers to the About page on PatternFly.org

docs: added supported browsers to About page

---

packages/v4/src/content/design-snippets/file-upload.md
packages/v4/src/content/design-snippets/simple-list.md

Adding content for two new components - File Upload and Simple List
Closes #1798

Added content to File Upload and Simple List snippets

---

yarn.lock

fix broken v3 example links

---

.circleci/config.yml
packages/gatsby-theme-patternfly-org/versions.json
packages/v4/package.json
yarn.lock

Delayed an hour or so because of the github outage. Towards #1792

bump for 2020.05

---

packages/gatsby-theme-patternfly-org/gatsby-node.js

Results: faster builds everywhere!
Further optimization could include transpiling `gatsby-theme-patternfly-org` before we publish it.

feat(webpack):  tweak babel-loader include/exclude

---

packages/gatsby-theme-patternfly-org/components/footer/footer.css
packages/gatsby-theme-patternfly-org/components/sideNav/sideNav.css

fix(css): remove small lines in sideNav and footer

---

packages/gatsby-theme-patternfly-org/components/sideNav/sideNav.css

I missed combining a rule into the selector.

Side nav colors 1832

---

.circleci/policy.txt
packages/gatsby-theme-patternfly-org/versions.json
packages/v4/package.json
yarn.lock

chore(2020.06): bump docs and versions.json

---

packages/gatsby-transformer-react-docgen-typescript/gatsby-node.js
packages/gatsby-transformer-react-docgen-typescript/package.json
yarn.lock

Towards https://github.com/patternfly/patternfly-react/issues/4197

fix(react-docgen): handle multiple exported components

---

packages/v4/src/content/design-guidelines/usage-and-behavior/buttons-and-links/buttons-and-links.md
packages/v4/src/content/design-guidelines/usage-and-behavior/toolbar/toolbar.md
packages/v4/src/content/design-snippets/overflow-menu.md

Closes [#3914 in patternfly-react](https://github.com/patternfly/patternfly-react/issues/3914).

Fixes "kebab" spelling in all occurrences

---

packages/gatsby-theme-patternfly-org/gatsby-node.js
packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
packages/gatsby-theme-patternfly-org/templates/mdx.js
packages/v4/gatsby-config.js

add ability to hide footer

---

packages/v4/src/pages/get-in-touch.js

fixed slack link on get in touch page

---

packages/gatsby-theme-patternfly-org/versions.json
packages/v4/CORE-UPGRADE-GUIDE.md
packages/v4/gatsby-config.js
packages/v4/package.json
packages/v4/src/content/design-guidelines/styles/icons/icons.md
yarn.lock

bump react-docs and versions.json

---

packages/v4/src/content/get-started/designers.md

Updating designer getting started documentation to include a section for e-training.
Completes step 1 of #1855

adding sketch e-training

---

packages/gatsby-theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

Closes issue reported by @mcoker

don't show nav toggle when hiding side bar

---

packages/gatsby-theme-patternfly-org/gatsby-config.js
packages/gatsby-theme-patternfly-org/pages/404.js
packages/v4/gatsby-config.js
packages/v4/src/pages/get-in-touch.js
packages/v4/src/pages/index.js

Closes #1894 
This PR reactivates the GDPR banner on the site.

chore(docs): reenabled GDPR banner

---

packages/v4/src/pages/homepage.css
packages/v4/src/pages/index.js

removed 600px max-width on homepage headline

---

packages/gatsby-theme-patternfly-org/components/sideNav/sideNav.css
packages/gatsby-theme-patternfly-org/versions.json
packages/v4/package.json
yarn.lock

Includes patch for sideNav bottom borders

bump for 2020.08

---

packages/gatsby-theme-patternfly-org/components/cssVariables/cssVariables.js
packages/gatsby-theme-patternfly-org/components/sideNav/sideNav.js

fix react token column

---

packages/gatsby-theme-patternfly-org/gatsby-node.js
packages/gatsby-theme-patternfly-org/helpers/extractExamples.js
packages/gatsby-theme-patternfly-org/index.js
packages/gatsby-theme-patternfly-org/templates/fullscreenHTML.js
packages/gatsby-theme-patternfly-org/templates/fullscreenMDX.js

Towards https://github.com/patternfly/patternfly/issues/3200

support WrapperTag

---

packages/gatsby-theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js

Fixes #1929, #1930, #1931, #1932, #1933, #1934, #1935

Create unique id for headings

---

packages/gatsby-theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js

Reverts patternfly/patternfly-org#1936

Revert "Create unique id for headings"

---

packages/gatsby-theme-patternfly-org/components/example/example.js
packages/gatsby-theme-patternfly-org/gatsby-node.js
packages/gatsby-theme-patternfly-org/helpers/codeTitleTransformer.js
packages/gatsby-theme-patternfly-org/helpers/extractExamples.js
packages/gatsby-theme-patternfly-org/templates/mdx.js
packages/v4/gatsby-config.js

Stop-gap for patternfly.org refactor

support example h3s

---

packages/v4/src/content/design-guidelines/content/punctuation.md

Edit hyphenation rules in PatternFly's content style guide

---

packages/v4/src/content/design-guidelines/styles/typography/typography.js
packages/v4/src/content/design-guidelines/styles/typography/typography.md

Changing copy in the typography section of PF for brevity and clarity 
Closes [issue 1665](https://github.com/patternfly/patternfly-org/issues/1665)

Typography Copy

---

packages/v4/src/content/get-started/designers.md

Update style guide link in "design about" page

---

packages/v4/src/content/design-guidelines/styles/typography/typography.css
packages/v4/src/content/design-guidelines/styles/typography/typography.js
packages/v4/src/content/design-guidelines/styles/typography/typography.md

fixed spacing for spacing values on typography page

---

packages/v4/src/content/design-guidelines/styles/icons/icons.md
packages/v4/src/content/design-guidelines/styles/spacers/spacers.md
packages/v4/src/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md
packages/v4/src/content/design-guidelines/usage-and-behavior/data-loading/data-loading.md
packages/v4/src/content/design-guidelines/usage-and-behavior/filters/filters.md
packages/v4/src/content/design-guidelines/usage-and-behavior/notification-drawer/notification-drawer.md
packages/v4/src/content/design-guidelines/usage-and-behavior/toolbar/toolbar.md

List of fixed links: https://docs.google.com/document/d/1IYcoZv37lFQYePd7bt0Q2y5bdZmGNlwIk_u5Pi-VhrE/edit#
@gdoyle1

Fixed Broken Links in Design Guidelines

---

packages/v4/src/content/design-guidelines/usage-and-behavior/login/login.md

Copy edits made to issue 1321

---

.circleci/upload-preview.sh

update cloudflare distribution

---

packages/theme-patternfly-org/templates/mdx.js

always use MDXChildTemplate

---

package.json
packages/theme-patternfly-org/scripts/prerender.js
packages/theme-patternfly-org/webpack.client.config.js
packages/theme-patternfly-org/webpack.server.config.js
packages/v4/package.json
packages/v4/patternfly-docs.config.js
packages/v4/scripts/sourceMD.js
yarn.lock

feat(charts): add chart docs

---

packages/v4/src/content/design-guidelines/content/terminology.md

Add OK to PF terminology list

---

.circleci/upload-staging.sh

fix(build): update cloudflare distribution

---

packages/v4/src/content/design-guidelines/content/capitalization.md

Updating guidelines and best practices for our "Capitalization" page in the PatternFly content style guide
Closes #1948

Updating "Capitalization" content

---

packages/gatsby-theme-patternfly-org/versions.json
packages/v4/package.json
yarn.lock

Follow-up to:
- https://github.com/patternfly/patternfly/pull/3399
- https://github.com/patternfly/patternfly/pull/3402
- https://github.com/patternfly/patternfly-react/pull/4693
- https://github.com/patternfly/patternfly-react/pull/4695

bumped site versions & docs for fixes caught in staging

---

packages/v4/src/content/design-guidelines/content/capitalization.md

Full review isn't needed! I just fixed a small typo in our intro so we don't repeat "consistent" and "consistency" in the same line.
Closes #2039

fixing redundant intro

---

packages/v4/scripts/sourceMD.js

Forgot to add this in initial POC.

add react table docs

---

.circleci/config.yml
packages/theme-patternfly-org/components/link/link.js
packages/theme-patternfly-org/components/sideNav/sideNav.js
packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
packages/v4/src/app.js

fix(nav): fix sidenav jumping on navigate

---

packages/theme-patternfly-org/scripts/md/parseMD.js
packages/v4/patternfly-docs.config.js

Closes 2. from https://docs.google.com/document/d/1dFxwpNDc7yqWcUtiNthwKmgnQF2Y6QJT7095BwiU4eo/edit?ts=5f453eac

fix(overview): remove overview

---

packages/v4/src/pages/home.css
packages/v4/src/pages/home.js

Homepage hero was a little wonky.

Remove height: 100% from hero

---

packages/v4/src/content/design-guidelines/components/about-modal/about-modal.md
packages/v4/src/content/design-guidelines/components/alert/alert.md
packages/v4/src/content/design-guidelines/components/button/button.md
packages/v4/src/content/design-guidelines/components/card/card.md
packages/v4/src/content/design-guidelines/components/empty-state/empty-state.md
packages/v4/src/content/design-guidelines/components/form/forms.md
packages/v4/src/content/design-guidelines/components/notification-drawer/notification-drawer.md
packages/v4/src/content/design-guidelines/components/pagination/pagination.md
packages/v4/src/content/design-guidelines/components/popover/popover.md
packages/v4/src/content/design-guidelines/components/select/select.md
packages/v4/src/content/design-guidelines/components/spinner/spinner.md
packages/v4/src/content/design-guidelines/components/toolbar/toolbar.md
packages/v4/src/content/design-guidelines/components/wizard/wizard.md
packages/v4/src/content/design-guidelines/usage-and-behavior/filters/filters.md

Closes 4. on https://docs.google.com/document/d/1dFxwpNDc7yqWcUtiNthwKmgnQF2Y6QJT7095BwiU4eo/edit?ts=5f453eac
Closes #2020

remove related components sections

---

packages/theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js
packages/theme-patternfly-org/components/footer/footer.css
packages/theme-patternfly-org/components/propsTable/propsTable.js
packages/theme-patternfly-org/components/tableOfContents/tableOfContents.css
packages/theme-patternfly-org/components/tableOfContents/tableOfContents.js
packages/theme-patternfly-org/global.css
packages/theme-patternfly-org/helpers/extractTableOfContents.js
packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
packages/theme-patternfly-org/templates/mdx.css

Implement https://marvelapp.com/prototype/b628dag/screen/72220616 and add scroll spy.
Thanks to @mcoker for [HTML/CSS](https://codepen.io/mcoker/pen/YzqZQqK).
@rachael-phillips Check out pages like https://patternfly-org-pr-2055-v4.surge.sh/v4/layouts/flex which have a huge TOC. What is the max-height you'd want to allow before just showing first-level items?

feat(toc): redesign

---

packages/theme-patternfly-org/components/link/link.js
packages/theme-patternfly-org/components/sideNav/sideNav.js
packages/theme-patternfly-org/components/tableOfContents/tableOfContents.js

Fix bug caused by fixing the nav jumping.

use useLocation to fix multi section highlight bug

---

packages/theme-patternfly-org/components/tableOfContents/tableOfContents.js

fix(toc): fix scrollspy

---

packages/theme-patternfly-org/components/sideNav/sideNav.css
packages/theme-patternfly-org/components/tableOfContents/tableOfContents.css
packages/theme-patternfly-org/helpers/extractTableOfContents.js
packages/theme-patternfly-org/templates/mdx.css
packages/v4/src/content/design-guidelines/content/brand-voice-and-tone.md
packages/v4/src/content/design-guidelines/content/capitalization.md
packages/v4/src/content/design-guidelines/content/error-messages.md
packages/v4/src/content/design-guidelines/content/numerics.md
packages/v4/src/content/design-guidelines/content/product-tours.md
packages/v4/src/content/design-guidelines/content/punctuation.md
packages/v4/src/content/design-guidelines/content/sentence-structure.md
packages/v4/src/content/design-guidelines/content/terminology.md
packages/v4/src/content/design-guidelines/content/ux-writing-best-practices.md

Here are the quick changes I was able to make while on our call.

pair programming feedback

---

packages/theme-patternfly-org/templates/mdx.css

dont display: flex main-content

---

packages/v4/src/content/design-guidelines/components/data-list/data-list.md
packages/v4/src/content/design-guidelines/components/modal/modal.md
packages/v4/src/content/design-guidelines/components/navigation/navigation.md
packages/v4/src/content/design-guidelines/components/progress/progress.md
packages/v4/src/content/design-guidelines/components/template/index.md.template

Missed these in #2051 since their headings were different

remove Components and demos used

---

packages/v4/src/content/design-guidelines/demos/primary-detail/primary-detail.md
packages/v4/src/routes.js

add primary-detail design guidelines

---

packages/v4/src/content/design-guidelines/components/about-modal/about-modal.md
packages/v4/src/content/design-guidelines/components/alert/alert.md
packages/v4/src/content/design-guidelines/components/button/button.md
packages/v4/src/content/design-guidelines/components/card/card.md
packages/v4/src/content/design-guidelines/components/empty-state/empty-state.md
packages/v4/src/content/design-guidelines/components/form/forms.md
packages/v4/src/content/design-guidelines/components/login-page/login-page.md

Components changed:
- About modal
- Alerts
- Buttons
- Cards
- Empty states
- Forms
- Login page

Updated links / descriptions for design docs

---

packages/theme-patternfly-org/package.json
packages/theme-patternfly-org/scripts/md/mdx-hast-to-jsx.js
yarn.lock

Supports #2085 .
Use `<img src="./my-gif.gif" width="500" height="300" />`.

add gif support in MD

---

packages/v4/src/content/design-guidelines/content/terminology.md

added to terminology

---

packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js
packages/theme-patternfly-org/templates/html.ejs

don't use preload

---

packages/theme-patternfly-org/components/example/example.css
packages/theme-patternfly-org/components/example/example.js
packages/theme-patternfly-org/scripts/md/example-captions.js
packages/theme-patternfly-org/scripts/md/parseMD.js

Needs followup with @rachael-phillips .
[Example with caption](https://patternfly-org-pr-2121-v4.surge.sh/v4/components/table/react-demos#automatic-pagination):

fix example captions

---

packages/theme-patternfly-org/components/example/example.js
packages/theme-patternfly-org/routes.js

Last change? :crossed_fingers:

templated MD page support

---

packages/theme-patternfly-org/components/autoLinkHeader/autoLinkHeader.js
packages/theme-patternfly-org/components/cssVariables/cssVariables.js
packages/theme-patternfly-org/components/example/exampleToolbar.js
packages/theme-patternfly-org/components/gdprBanner/gdprBanner.js
packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
packages/theme-patternfly-org/package.json
packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js
packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js
packages/theme-patternfly-org/templates/mdx.js
packages/v4/src/content/design-guidelines/styles/typography/typography.md
packages/v4/src/content/get-started/training/trainingCard/trainingCard.js
packages/v4/src/pages/get-in-touch.js
packages/v4/src/pages/home.js
yarn.lock

Use custom buble version per `react-live`'s suggestions. Use proper icon imports.

reduce bundle size

---

packages/theme-patternfly-org/helpers/capitalize.js
packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js

fix(react): build

---

packages/theme-patternfly-org/components/footer/footer.js
packages/v4/src/content/contribute/design/design.md
packages/v4/src/content/design-guidelines/styles/icons/icons.md
packages/v4/src/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md
packages/v4/src/content/get-started/design.md
packages/v4/src/content/get-started/migrate.md

Fix the remaining broken links for content from this repo. ~40 remain from Core/React.

fix broken links

---

packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js

Add sourced routes to sitemap but exclude the root route.

fix sitemap

---

packages/theme-patternfly-org/scripts/cli/start.js
packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js
packages/theme-patternfly-org/scripts/webpack/webpack.client.config.js

enable HMR for CSS

---

packages/theme-patternfly-org/scripts/md/parseMD.js
packages/v4/package.json
packages/v4/patternfly-docs.source.js
yarn.lock

fix sourcing demos

---

packages/v4/src/content/design-guidelines/components/modal/modal.md

dogfood icons in design guidelines

---

packages/theme-patternfly-org/components/footer/footer.js
packages/theme-patternfly-org/components/gdprBanner/gdprBanner.js
packages/theme-patternfly-org/routes.js
packages/theme-patternfly-org/scripts/cli/build.js
packages/theme-patternfly-org/scripts/md/parseMD.js
packages/theme-patternfly-org/scripts/webpack/getHtmlWebpackPlugins.js
packages/v3/source/get-started/repositories/index.md
packages/v4/src/content/design-guidelines/styles/icons/icons.md
packages/v4/src/content/design-guidelines/styles/spacers/spacers.md
packages/v4/src/pages/get-in-touch.js

fix(content): fix broken links

---

.circleci/config.yml

Fixes some edge-case bugs where building the docs fails

don't cache v4/public

---

packages/v4/src/content/design-guidelines/content/error-messages.md

Error message guidelines revamp

---

packages/v4/src/content/get-started/about.md

https://patternfly-org-pr-2156-v4.surge.sh/v4/get-started/about#layouts
Closes #885

fix(get-started/about): tweak sentence about layouts

---

packages/theme-patternfly-org/scripts/webpack/webpack.server.config.js

Unblocks https://github.com/patternfly/patternfly-react/pull/4907

fix(novnc): use null-loader for SSR

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css

fixes https://github.com/patternfly/patternfly-org/issues/2180

fix(sidenav): hide scrollbar unless there is overflow

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css
packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

use fixed-width input

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

feat(SkipToContent): Add skip to content to documentation

---

packages/theme-patternfly-org/helpers/xterm-addon-fit.js
packages/theme-patternfly-org/helpers/xterm.js
packages/theme-patternfly-org/scripts/webpack/webpack.server.config.js

Toward https://github.com/patternfly/patternfly-react/pull/4907

fix xterm ssr

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

fix latest version switcher

---

packages/theme-patternfly-org/package.json

Prepare upcoming change to upgrade to React 17.

fix(theme): move react to peer dep

---

packages/v4/src/content/design-guidelines/content/about.md
packages/v4/src/content/design-guidelines/content/terminology.md

Adding RH's product documentation style guide to PatternFly

---

packages/theme-patternfly-org/helpers/buble.js

fix(buble): allow JSXEmptyExpressions

---

packages/theme-patternfly-org/components/propsTable/propsTable.js
packages/theme-patternfly-org/templates/mdx.js

add 2nd level toc for props

---

packages/v4/src/content/contribute/design-guidelines/design-guidelines.md

A quick edit to align our single callout guidance with what we advise in the "Writing design documentation" page of the UX Writing Style Guide.
Closes #2191

Callout phrasing edit

---

packages/v4/src/content/design-guidelines/content/terminology.md

Add "Save" to terminology list (UX Writing style guide)

---

packages/theme-patternfly-org/helpers/buble.js
packages/theme-patternfly-org/routes.js

Add default design guidelines for new components

fix default design guidelines

---

packages/theme-patternfly-org/helpers/buble.js

Fix about modal and other examples.

fix JSXText replace regex

---

packages/theme-patternfly-org/scripts/webpack/webpack.server.config.js

Fixes https://github.com/patternfly/patternfly-react/pull/5208

handle @novnc/novnc

---

packages/v4/src/content/contribute/design-guidelines/design-guidelines.md

Fixing typos/formatting in design guidelines contribution page

---

packages/v4/src/content/design-guidelines/styles/icons/icons.js

Closes #2322 
This PR adds the fa-upload/UploadIcon to the icons table.

added UploadIcon to icons table

---

.circleci/config.yml
package.json
packages/theme-patternfly-org/scripts/tsDocgen.js

feat(docgen): add @propType and fix @hide

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

fix(page): fix nav collapsing on mobile

---

.github/release.sh
packages/theme-patternfly-org/package.json
packages/theme-patternfly-org/scripts/webpack/webpack.base.config.js
yarn.lock

feat(theme): add monaco-editor-webpack-plugin

---

packages/theme-patternfly-org/components/gdprBanner/gdprBanner.js
packages/theme-patternfly-org/scripts/webpack/prerender.js

Towards https://github.com/patternfly/patternfly-react/pull/5294

pretty prendering

---

packages/v4/patternfly-docs.source.js

Closes #2374 
Adds react-code-editor to source MD files

added code-editor to source file

---

packages/theme-patternfly-org/components/footer/footer.css
packages/theme-patternfly-org/components/footer/footer.js
packages/theme-patternfly-org/components/tableOfContents/tableOfContents.css
packages/theme-patternfly-org/templates/mdx.css
packages/theme-patternfly-org/templates/mdx.js
packages/v4/src/content/design-guidelines/components/table/table.md

Closes #2185 
This PR:
- Hides TOC scrollbar to avoid double scrollbars
- Fixes anchor links on Table design guidelines
- Removes custom PageSection styling in favor of default styling

fix scrollbars, anchor links, page section padding

---

packages/theme-patternfly-org/scripts/md/styled-tags.js
packages/v4/src/content/design-guidelines/usage-and-behavior/filters/filters.md

Makes all table headers wrap per discussion with @andybraren 
cc @mcarrano

add pf-m-wrap to MD th elements

---

packages/v4/src/content/design-guidelines/content/about.md

Update link in UX writing style guide's "About" page

---

packages/theme-patternfly-org/templates/mdx.css
packages/v4/src/content/design-guidelines/content/about.md
packages/v4/src/content/design-guidelines/content/content.css

Should fix column alignment on #2417

move content.css to mdx.css

---

packages/theme-patternfly-org/helpers/buble.js
packages/theme-patternfly-org/helpers/transformCode.js
packages/v4/src/content/design-guidelines/components/alert/alert.md

Towards fixing core `<pre>` tags

fix(transformCode): fix line breaks in html to be <br>

---

packages/theme-patternfly-org/components/footer/footer.js

Copyright date was inaccurate.

Updated copyright date

---

packages/v4/src/content/design-guidelines/components/badge/badge.md

Closes #2107 
@mcarrano just added one sentence authored by @lclay2 on clickable badges

added sentence on clickable badges

---

packages/v4/src/content/design-guidelines/content/numerics.md

Add a date/time pattern to the UX writing style guide

---

packages/v4/src/content/design-guidelines/styles/icons/icons.md

addition about fas vs far

---

packages/theme-patternfly-org/helpers/codesandbox.js

fix(codesandbox): root height

---

packages/v4/src/content/design-guidelines/content/terminology.md

Add "click" to PF terminology list

---

packages/v4/src/content/design-guidelines/content/terminology.md

Adding definitions for "sign up" variations

---

packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js

fix(hotkey): check if content editable

---

packages/v4/src/content/design-guidelines/content/capitalization.md

Add custom resource information to Capitalization page of the UX writing style guide

---

packages/v4/src/content/get-started/design.md

Updated broken library links

---

packages/v4/src/content/design-guidelines/components/modal/modal.md

closes #2499 
@mcarrano could you review this and let me know if you think the changes I made make sense in addressing the issue. Or should we just remove the row all together?

edit icon usage table

---

packages/v4/src/content/design-guidelines/components/tooltip/tooltip.md

https://github.com/patternfly/patternfly-react/pull/5746
closes #2450

add guidance for tooltip on hover delay

---

packages/theme-patternfly-org/routes.js

add a11y tab

---

packages/theme-patternfly-org/package.json
packages/theme-patternfly-org/scripts/tsDocgen.js
yarn.lock

Check v4/components/slider/#sliderstepobject:

fix(tsdocgen): interface normalizer

---

packages/theme-patternfly-org/templates/mdx.js

This is pulled out from an old PR that never got merged. I closed it: https://github.com/patternfly/patternfly-org/pull/2470

update beta tag messaging

---

packages/v4/src/content/accessibility/accordion/accordion.md

docs(Accordion): Add accordion a11y docs

---

packages/v4/src/content/accessibility/label/label.md

docs(label): add a11y documentation

---

packages/v4/src/content/accessibility/title/title.md

docs(title): add a11y documentation

---

packages/v4/src/content/accessibility/context-selector/context-selector.md

docs(ContextSelector): Add a11y documentation

---

packages/v4/src/content/accessibility/chip-group/chip-group.md

docs(Chip group): Add a11y documentation for chip group

---

packages/v4/src/content/accessibility/clipboard-copy/clipboard-copy.md

docs(ClipboardCopy): Add a11y documentation

---

packages/v4/src/content/accessibility/checkbox/checkbox.md

docs(Checkbox): Add a11y documentation for checkbox

---

packages/v4/src/content/accessibility/application-launcher/application-launcher.md

docs(AppLauncher): Add a11y documentation for app launcher

---

packages/v4/src/content/accessibility/breadcrumb/breadcrumb.md

docs(Breadcrumb): Add breadcrumb a11y docs

---

packages/v4/src/content/accessibility/AboutModal/AboutModal.md
packages/v4/src/content/accessibility/about-modal/about-modal.md

docs(AboutModal): add a11y documentation

---

packages/v4/src/content/accessibility/alert-group/alert-group.md

docs(AlertGroup): Add alert group a11y documentation

---

packages/v4/src/content/accessibility/skip-to-content/skip-to-content.md

docs(skip-to-content): add a11y documentation

---

packages/v4/src/content/accessibility/page/page.md

docs(page): add a11y documentation

---

packages/v4/src/content/accessibility/avatar/avatar.md

a11y documentation for the avatar component

docs(avatar): add a11y documentation

---

packages/theme-patternfly-org/scripts/md/mdx-ast-to-mdx-hast.js
packages/theme-patternfly-org/scripts/md/parseMD.js
packages/v4/patternfly-docs.source.js

fix(externalwatcher): watch for adding files

---

packages/theme-patternfly-org/helpers/acorn-typescript.js

Allows parsing `const a = (b: c) => {}`.

parse arrow function type parameters

---

packages/v4/src/content/design-guidelines/styles/icons/icons.js

Closes #2531 
This PR adds the TaskIcon to the list of "All icons" on the website.

added TaskIcon to icons table

---

packages/theme-patternfly-org/helpers/acorn-typescript.js

Closes #2633
See https://github.com/microsoft/TypeScript/blob/main/doc/spec-ARCHIVED.md#4153-grammar-ambiguities

fix(parser): handle ambigous TSCallExpression

---

packages/v4/src/content/accessibility/tree-view/tree-view.md

docs(tree-view): add a11y documentation

---

packages/v4/src/content/accessibility/card/card.md

docs(Card): Add a11y documentation for card

---

packages/theme-patternfly-org/scripts/cli/generate.js
packages/theme-patternfly-org/scripts/md/parseMD.js

fix(docs): disable MD external file watcher when not running in dev mode

---

packages/v4/src/content/design-guidelines/styles/typography/typography.md

add typography guidance

---

packages/theme-patternfly-org/helpers/acorn-typescript.js

add typeof and keyof parsing

---

packages/theme-patternfly-org/helpers/acorn-typescript.js

fix(ts): nested type params

---

packages/theme-patternfly-org/components/propsTable/propTypeWithLinks.js

fix duplicate keys

---

packages/theme-patternfly-org/helpers/acorn-typescript.js

Fix `React.useState<string[]>([]);`

use _parseTSType

---

packages/theme-patternfly-org/scripts/md/parseMD.js
packages/theme-patternfly-org/scripts/md/typecheck.js

Properly typecheck `import styles from '@patternfly/react-styles/css/layouts/Toolbar/toolbar'`

add react-styles/css types

---

packages/v4/src/content/accessibility/calendar-month/calendar-month.md

docs(calendar-month): add a11y documentation

---

.github/workflows-src/pr-preview.yml
.github/workflows/pr-preview.yml

fixes https://github.com/patternfly/patternfly-org/issues/2765

fix(pr-preview): updated failing job to run conditionally

---

packages/theme-patternfly-org/pages/red-hat-font.md

fixes https://github.com/patternfly/patternfly-org/issues/2762
--
This is a rough draft. @mcarrano @mceledonia @abigaeljamie please review the content and let me know what you think.

docs(font): added docs for red hat font update to 4.0.2

---

packages/v4/src/content/accessibility/banner/banner.md

docs(banner): added a11y documentation

---

packages/v4/src/pages/community.js

add patternfly calendar to community page

---

packages/v4/src/content/training/design.css
packages/v4/src/content/training/design.md
packages/v4/src/content/training/trainingCard/trainingCard.css
packages/v4/src/content/training/trainingCard/trainingCard.js

Closes #1855 
This PR adds the Sketch design training to the training section of the website.

feat(docs): add sketch design training to site

---

packages/v4/src/content/design-guidelines/components/alert-group/alert-group.md
packages/v4/src/content/design-guidelines/components/alert/alert.md
packages/v4/src/content/design-guidelines/components/banner/banner.md
packages/v4/src/content/design-guidelines/components/card/card.md
packages/v4/src/content/design-guidelines/components/checkbox/checkbox.md
packages/v4/src/content/design-guidelines/components/clipboard-copy/clipboard-copy.md
packages/v4/src/content/design-guidelines/components/code-block/code-block.md
packages/v4/src/content/design-guidelines/components/data-list/data-list.md
packages/v4/src/content/design-guidelines/components/date-picker/date-picker.md
packages/v4/src/content/design-guidelines/components/form/forms.md
packages/v4/src/content/design-guidelines/components/inline-edit/inline-edit.md
packages/v4/src/content/design-guidelines/components/input-group/input-group.md
packages/v4/src/content/design-guidelines/components/modal/modal.md
packages/v4/src/content/design-guidelines/components/navigation/navigation.md
packages/v4/src/content/design-guidelines/components/number input/number-input.md
packages/v4/src/content/design-guidelines/components/progress/progress.md
packages/v4/src/content/design-guidelines/components/radio/radio.md
packages/v4/src/content/design-guidelines/components/search-input/search-input.md
packages/v4/src/content/design-guidelines/components/select/select.md
packages/v4/src/content/design-guidelines/components/table/table.md

Audited the components to make sure all of the numbers used a symbol instead of being written out

Numbers audit

---

packages/v4/src/content/design-guidelines/components/tree-view/tree-view.md

Made slight grammar changes to the tree view design guidelines 
Closes #2773

iss2773- Edit tree view page for grammar

---

packages/v4/src/content/get-started/about.md

fix: About PatternFly - update path for global-css link

---

packages/v4/src/content/accessibility/badge/badge.md

docs(badge): added a11y documentation

---

packages/theme-patternfly-org/components/footer/footer.css
packages/theme-patternfly-org/components/footer/footer.js

fixes https://github.com/patternfly/patternfly-org/issues/2769

fix(footer): fix footer link styles

---

packages/theme-patternfly-org/pages/global-css-variables.md

Add documentation to the developer resources about how the breakpoints are used.

chore(documentation): adds breakpoint information

---

packages/v4/src/content/get-started/develop.md

Closes #2787 
This PR adds a new section "Testing" to the Getting started/developer page, which references & links to the existing OUIA page.

chore(docs): added paragraph about testing with link to OUIA

---

packages/v4/src/content/get-started/design.md

@evwilkin I fixed the links to our old Overpass library :) 
Closes #2861

Updated overpass library links

---

packages/v4/src/content/design-guidelines/styles/icons/icons.js
packages/v4/src/content/design-guidelines/styles/icons/icons.md

I've updated a link to all SVGs and added a critical risk icon to a list on a website.

Updated icons page

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

add github issue template

---

packages/v4/src/content/design-guidelines/charts/area-chart/area-chart.md
packages/v4/src/content/design-guidelines/charts/bar-chart/bar-chart.md

update minor errors on chart pages

---

packages/v4/src/content/accessibility/chip/chip.md

docs(chip): add a11y documentation

---

packages/v4/src/content/design-guidelines/components/time picker/time-picker.md

closes #2953 
This PR fixes 2 broken links in the Time picker design guidelines

fix(docs): fixed 2 broken links

---

packages/v4/src/content/design-guidelines/components/switch/switch.md

add content section and switch design guidelines

---

packages/v4/src/content/developer-resources/accessibility-guide.md

Updated get in touch link

---

packages/v4/patternfly-docs/content/design-guidelines/components/card/card.md

Card design guideline changes.

---

packages/v4/patternfly-docs/content/design-guidelines/components/data-list/data-list.md

closes #3072 
No new content added, just rearranged to reflect template and added "spacing" heading

rearrangin data list

---

packages/v4/patternfly-docs/content/design-guidelines/components/banner/banner.md

Updates banner design guidelines for consistency effort.

---

packages/v4/patternfly-docs/content/design-guidelines/components/code-editor/code-editor.md

code editor guildines consistency

---

packages/v4/patternfly-docs/content/design-guidelines/components/about-modal/about-modal.md

Just re-arranged old content and made very subtle changes!
closes #3065

about modal re-arrange

---

packages/documentation-framework/app.js
packages/documentation-framework/scripts/webpack/webpack.client.config.js

Fixes: #3054
Does fix it as @mcoker suggested, but is it the best way to handle?

Style order issue

---

packages/v4/patternfly-docs/content/design-guidelines/components/alert-group/alert-group.md
packages/v4/patternfly-docs/content/design-guidelines/components/spinner/spinner.md
packages/v4/patternfly-docs/content/design-guidelines/components/table/table.md
packages/v4/patternfly-docs/content/design-guidelines/components/tabs/tabs.md
packages/v4/patternfly-docs/content/design-guidelines/components/toggle-group/toggle-group.md
packages/v4/patternfly-docs/content/design-guidelines/components/toolbar/toolbar.md
packages/v4/patternfly-docs/content/design-guidelines/components/tooltip/tooltip.md
packages/v4/patternfly-docs/content/design-guidelines/components/tree-view/tree-view.md
packages/v4/patternfly-docs/content/design-guidelines/components/wizard/wizard.md

closes #3098 
Adjusted all fo the following components to reflect template and organize:
Table
Tabs
Toggle group
toolbar
tooltip
treeview
wizard
spinner

A bunch of minor reordering and adjustments --Iss3098

---

packages/v4/patternfly-docs/content/design-guidelines/components/action-list/action-list.md
packages/v4/patternfly-docs/content/design-guidelines/components/alert-group/alert-group.md
packages/v4/patternfly-docs/content/design-guidelines/components/alert/alert.md
packages/v4/patternfly-docs/content/design-guidelines/components/form/forms.md
packages/v4/patternfly-docs/content/design-guidelines/components/panel/panel.md

design guidelines

---

packages/documentation-framework/components/example/example.js

Was removed when rebasing a different PR before merging.

add Switch import back for Dark theme

---

packages/documentation-framework/pages/global-css-variables.md

chore(docs): better describe css variable naming

---

packages/v4/patternfly-docs/pages/community.js

Updates Fritz2 community blurb.

---

packages/v4/patternfly-docs/content/design-guidelines/components/sidebar/sidebar.md

Create guidelines for Side bar component

---

packages/v4/patternfly-docs/content/design-guidelines/components/drawer/drawer.md
packages/v4/patternfly-docs/content/design-guidelines/components/inline-edit/inline-edit.md

docs(Drawer, InlineEdit): added alt text

---

packages/v4/patternfly-docs/content/accessibility/backdrop/backdrop.md

chore(backdrop): reformat a11y docs

---

packages/v4/patternfly-docs/content/accessibility/background-image/background-image.md

Fixes #3251 
Since we mention using alt text, I added it to the HTML section. However, there isn't a React prop for it, so I didn't add it..is that something that should be added?

chore(background-image): reformat a11y docs

---

packages/v4/patternfly-docs/content/accessibility/banner/banner.md

chore(banner): update a11y docs

---

packages/v4/patternfly-docs/content/accessibility/navigation/navigation.md

docs(Navigation): add accessibility documentation

---

packages/v4/patternfly-docs/content/accessibility/action-list/action-list.md

chore(ActionList): updated a11y docs

---

packages/v4/patternfly-docs/content/accessibility/menu-toggle/menu-toggle.md

docs(MenuToggle): add accessibility documentation

---

packages/v4/patternfly-docs/content/accessibility/progress/progress.md

Closes https://github.com/patternfly/patternfly-org/issues/3244

docs(Progress): add accessibility documentation

---

packages/v4/patternfly-docs/content/accessibility/breadcrumb/breadcrumb.md

chore(Breadcrumb): updated a11y docs

---

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
packages/v4/patternfly-docs/pages/home.js

fix(sideNavLayout):replace use of PageHeader with Masthead

---

packages/documentation-framework/app.js
packages/documentation-framework/package.json
packages/documentation-framework/scripts/webpack/webpack.base.config.js
yarn.lock

Followup to #3324 as that fix does not seem to be working reliably.
Closes #3325

fix(lodash): remove lodash alias

---

packages/v4/patternfly-docs/content/design-guidelines/content/terminology.md

Add definitions for the terms Filter and Search to the UX-writing/Terminology page to address this issue: #3312
Closes #3312

Add filter and search definitions

---

packages/documentation-framework/scripts/md/parseMD.js

feat(docs): add frontmatter option to fix extensions view source link

---

packages/documentation-framework/templates/patternfly-docs/patternfly-docs.source.js
packages/v4/package.json
packages/v4/patternfly-docs/content/extensions/extensions-data.js
packages/v4/patternfly-docs/patternfly-docs.source.js
yarn.lock

docs(CatalogView): added catalog view documentation directly to the site

---

packages/documentation-framework/components/footer/footer.js
packages/v4/patternfly-docs/pages/community.js

fix(slack-link): update slack link in footer and community page

---

packages/documentation-framework/helpers/getTitle.js

This PR will update the title text that displays on browser tabs from PatternFly 4 to PatternFly 5.
Closes #3388

Update to website title PatternFly 5

---

packages/documentation-framework/components/functionsTable/functionsTable.js
packages/documentation-framework/package.json
packages/documentation-framework/scripts/cli/generate.js
packages/documentation-framework/scripts/md/parseMD.js
packages/documentation-framework/scripts/typeDocGen.js
packages/documentation-framework/templates/mdx.js
packages/v4/patternfly-docs/patternfly-docs.source.js
yarn.lock

feat(docs-framework): add support for exposing function documentation

---

packages/v4/patternfly-docs/content/design-guidelines/components/input-group/input-group.md

Updating input group guidelines

---

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
packages/documentation-framework/package.json
packages/v4/package.json
packages/v4/patternfly-docs/patternfly-docs.css.js
yarn.lock

chore(sideNavLayout): updated PageSidebar to new API

---

packages/v4/patternfly-docs/patternfly-docs.config.js

Bug fix - display utility classes in sidebar

---

packages/v4/patternfly-docs/content/developer-resources/accessibility-guide.md

Towards #3302 
Fixed md related issues. Remaining issues are related to the content in the image - if we want to make those changes to the image, it looks like we may need to open a design issue

Fix accessibility fundamentals page issues

---

packages/documentation-framework/components/example/example.css
packages/documentation-framework/components/example/example.js

fixes https://github.com/patternfly/patternfly-org/issues/3531

fix(docs): use correct theme class on full page dark theme switcher

---

README.md

Updated node version to 18.16.0

chore(readme): updated node version

---

packages/v4/patternfly-docs/content/get-started/about.md
packages/v4/patternfly-docs/content/get-started/design.md
packages/v4/patternfly-docs/content/get-started/develop.md

Progress toward: https://github.com/patternfly/patternfly-org/issues/3437

chore: broken links fixed

---

packages/v4/patternfly-docs/content/contribute/design/design.md
packages/v4/patternfly-docs/content/design-guidelines/charts/about/about.md
packages/v4/patternfly-docs/content/design-guidelines/components/alert/alert.md
packages/v4/patternfly-docs/content/design-guidelines/components/button/button.md
packages/v4/patternfly-docs/content/design-guidelines/components/time picker/time-picker.md
packages/v4/patternfly-docs/content/design-guidelines/content/punctuation.md
packages/v4/patternfly-docs/content/design-guidelines/styles/spacers/spacers.md
packages/v4/patternfly-docs/content/design-guidelines/usage-and-behavior/bulk-selection/bulk-selection.md
packages/v4/patternfly-docs/content/design-guidelines/usage-and-behavior/usage-and-behavior.md
packages/v4/patternfly-docs/content/get-started/design.md
packages/v4/patternfly-docs/content/get-started/develop.md

Went back through and made sure all corrected links were done in .md files
Closes https://github.com/patternfly/patternfly-org/issues/3437

chore: fixed links in correct files.

---

packages/v4/patternfly-docs/content/accessibility/checkbox/checkbox.md
packages/v4/patternfly-docs/content/design-guidelines/components/application-launcher/application-launcher.md
packages/v4/patternfly-docs/content/design-guidelines/components/button/button.md
packages/v4/patternfly-docs/content/design-guidelines/components/calendar-month/calendar-month.md
packages/v4/patternfly-docs/content/design-guidelines/components/card/card.md
packages/v4/patternfly-docs/content/design-guidelines/components/checkbox/checkbox.md
packages/v4/patternfly-docs/content/design-guidelines/components/data-list/data-list.md
packages/v4/patternfly-docs/content/design-guidelines/components/file-upload-multiple/file-upload-multiple.md
packages/v4/patternfly-docs/content/design-guidelines/components/form-select/form-select.md
packages/v4/patternfly-docs/content/design-guidelines/components/form/forms.md
packages/v4/patternfly-docs/content/design-guidelines/components/masthead/masthead.md
packages/v4/patternfly-docs/content/design-guidelines/components/menu-toggle/menu-toggle.md
packages/v4/patternfly-docs/content/design-guidelines/components/table/table.md

more links fixed
Closes https://github.com/patternfly/patternfly-org/issues/3437

chore: fixed links in correct file

---

packages/documentation-framework/components/footer/footer.css
packages/documentation-framework/helpers/codesandbox.js
packages/documentation-framework/templates/html.ejs
packages/documentation-framework/templates/mdx.css

Updated font families and removed unnecessary classes.
Closes https://github.com/patternfly/patternfly-org/issues/3537

chore: fixed fonts and deleted unnecessary classes

---

beta-component-promotion/promotion-2022.14/beta-promotion-candidates.md
packages/v4/patternfly-docs/components-data.json

Closes https://github.com/patternfly/patternfly-org/issues/3437

Chore: Updated more urls

---

packages/documentation-framework/components/sideNav/sideNav.js

fix(Sidenav): updated PageContext props

---

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.css
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md

Closes #3599 
This PR fixes dark theme & styling bugs on the Typography page.

fix Typography page dark theme bugs, replace hardcode with vars

---

packages/documentation-framework/templates/mdx.css
packages/v4/patternfly-docs/pages/home.css
packages/v4/patternfly-docs/pages/home.js

Added a banner to top of home page with a link to the new v5 url.
Closes https://github.com/patternfly/patternfly-org/issues/3565

chore: added banner to homepage with a link to new v5 page

---

packages/documentation-site/patternfly-docs/content/accessibility/menu-toggle/menu-toggle.md
packages/documentation-site/patternfly-docs/content/design-guidelines/components/login-page/login-page.md
packages/documentation-site/patternfly-docs/content/developer-resources/accessibility-development.md
packages/documentation-site/patternfly-docs/content/get-started/design.md
packages/documentation-site/patternfly-docs/pages/home.js

All links listed in the shared docs have been fixed.
Closes https://github.com/patternfly/patternfly-org/issues/3437

chore: all links fixed

---

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js

Update featured blog on homepage.

---

README.md

In support of https://github.com/patternfly/patternfly/issues/5601

Update README.md with links to core docs

---

packages/documentation-framework/templates/mdx.js

fixes https://github.com/patternfly/patternfly-org/issues/3720

fix(mdx): added missing key on CSSVariables

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/progress/progress.md

docs(progress): Move placement section of design guidelines to H2. 

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/banner/banner.md

docs(banner): Move placement section of design guidelines to H2. 

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/button/button.md

docs(button): Move placement section of design guidelines to H2.

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/alert/alert.md

docs(alert): Move placement section of design guidelines to H2.

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/progress-stepper/progress-stepper.md

Added when to use Progress stepper

---

packages/documentation-site/patternfly-docs/content/developer-resources/rtl-handbook.md

Adds a section in the developer resources explaining RTL.
Fixes #3736

docs(RTL): add RTL handbook

---

packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md

docs(release-highlights): creates q3 release highlights.

---

packages/documentation-framework/versions.json

Required to build the drag-drop docs in react repo.

add react-drag-drop to latest version file

---

packages/documentation-site/patternfly-docs/patternfly-docs.css.js

Closes: https://github.com/patternfly/patternfly-org/issues/3791

fix: add charts dark theme stylesheet

---

packages/documentation-site/patternfly-docs/content/accessibility/about-modal/about-modal.md

chore(AboutModal): updated a11y docs to match template

---

package.json
yarn.lock

chore(deps): add react as a dep at the root level

---

packages/documentation-site/patternfly-docs/content/accessibility/banner/banner.md
packages/documentation-site/patternfly-docs/content/accessibility/skeleton/skeleton.md

chore(Skeleton): updated a11y docs to match template

---

packages/documentation-site/patternfly-docs/content/accessibility/helper-text/helper-text.md
packages/documentation-site/patternfly-docs/content/design-guidelines/components/helper-text/helper-text.md

chore(HelperText): updated a11y docs to match template

---

packages/documentation-site/patternfly-docs/pages/landing-pages/extensions/extensions-data.json

docs(extensions): Updates the extensions landing page to add reference to the component groups extension.

---

packages/documentation-framework/components/sideNav/sideNav.js
packages/documentation-framework/templates/mdx.js

Closes: https://github.com/patternfly/patternfly-org/issues/3852

fix: avoid applying beta tags to nav items for next components

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/truncate/truncate.md

Closes https://github.com/patternfly/patternfly-design/issues/1280

fix(truncate): typos on guidelines

---

packages/documentation-framework/versions.json

Closes #3683 
Adding new version number to bump v4 staging site

Algolia fix

---

package.json
packages/documentation-framework/package.json
packages/documentation-framework/versions.json
packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
yarn.lock

Bumps versions and adds release notes for the 5.2.2 patch release that came out last night.

feat(deps): version bump and release notes for 5.2.2 patch release

---

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
packages/documentation-site/package.json

chore(search): Remove search input in v6 temporarily

---

packages/documentation-site/patternfly-docs/content/tokens/design-with-tokens.md

docs(tokens): Renames Penta to PatternFly 6 for clarity.

---

package.json
packages/documentation-framework/package.json
packages/documentation-framework/versions.json
packages/documentation-site/package.json
yarn.lock

Update react to prerelease.26 and other dependencies that bumped as a result.

update prerelease versions

---

packages/documentation-site/patternfly-docs/patternfly-docs.source.js

fix(docs): Add tokens back to site

---

packages/documentation-framework/templates/mdx.js

bug(link): Update link for deprecated alert

---

packages/documentation-framework/components/autoLinkHeader/autoLinkHeader.css
packages/documentation-framework/components/cssVariables/cssVariables.css
packages/documentation-framework/components/example/example.css
packages/documentation-framework/components/footer/footer.css
packages/documentation-framework/components/gdprBanner/gdprBanner.css
packages/documentation-framework/components/sectionGallery/sectionGallery.css
packages/documentation-framework/components/sideNav/sideNav.css
packages/documentation-framework/components/tableOfContents/tableOfContents.css
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css
packages/documentation-framework/package.json
packages/documentation-framework/pages/404/404.css
packages/documentation-framework/pages/404/index.js
packages/documentation-framework/templates/mdx.css
packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors-for-charts/colors-for-charts.css
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/ColorFamily.css
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/ColorFamily.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/ColorSwatch.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/IconsTable.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/icons.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/spacers/spacers.css
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.css
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.js
packages/documentation-site/patternfly-docs/content/extensions/extensions.css
packages/documentation-site/patternfly-docs/content/get-started/community/community.css
packages/documentation-site/patternfly-docs/content/training/design.css
packages/documentation-site/patternfly-docs/pages/home.css

Towards #3945
This PR updates global styles in the quickest way I could so that their removal in core didn't break things and prevent further progress on the style updates or block us from pulling in the latest alphas.

fix(styles): Remove and replace global styles

---

package.json
packages/documentation-framework/package.json
packages/documentation-framework/scripts/md/parseMD.js
packages/documentation-site/package.json
yarn.lock

Closes: https://github.com/patternfly/patternfly-org/issues/4010

fix: full page demos, typescript compilation still turned off

---

packages/documentation-framework/components/footer/footer.js
packages/documentation-site/patternfly-docs/content/get-started/community/community.md

Closes #4029 
this is for the v5 site

docs: Updates PatternFly mailing list link.

---

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/IconRecommendations.js
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/icons/IconsTable.js
packages/documentation-site/patternfly-docs/content/get-started/release-notes-table.js

chore(EmptyState): updated to use props instead of header/icon components

---

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors-for-charts/colors-grid.js

chore(docs): Update design guidelines colors grid to use Text component

---

packages/documentation-framework/pages/404/index.js

fix(EmptyState): removed extraneous ESIcon component import

---

packages/documentation-framework/components/footer/footer.js

also closes #4029, this pr is for the v6 site

docs: Updates mailing list link in footer.

---

.github/stale.yml

Towards https://github.com/patternfly/patternfly-react/issues/10525

chore(ci): Update stalebot to stale action

---

packages/documentation-framework/components/gdprBanner/gdprBanner.css
packages/documentation-framework/components/gdprBanner/gdprBanner.js
packages/documentation-site/package.json

Closes: https://github.com/patternfly/patternfly-org/issues/4062

fix: clean up gdpr banner styles

---

packages/documentation-framework/templates/mdx.css
packages/documentation-framework/templates/mdx.js
packages/documentation-site/package.json

Closes: https://github.com/patternfly/patternfly-org/issues/4066

fix: clean up mdx.css (after examples.css merges)

---

packages/documentation-framework/components/example/example.css
packages/documentation-framework/components/tableOfContents/tableOfContents.css
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.css
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
packages/documentation-site/package.json

Closes #4065 
delete most of the css overrides in sideNavLayout.css
also:
- fix styling on the TOC toggle button
- fix z index of full screen image links

fix: css clean up - esp sidenavlayout.css

---

packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/patternfly-docs.source.js

Closes: https://github.com/patternfly/patternfly-org/issues/3976

feat: add templates to v6 docs

---

packages/documentation-site/patternfly-docs/content/get-started/upgrade.md

docs(upgrade-guide): Update codemod option naming.

---

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js

docs(home): Updates featured Medium blogs.

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md

Fixes https://github.com/patternfly/patternfly-org/issues/4124.

fix(docs): switched from v4 to evergreen badge link

---

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js

docs(home): Fix Medium blog link.

---

packages/documentation-site/patternfly-docs/pages/featured-posts-data.js

follow-up / same thing as https://github.com/patternfly/patternfly-org/pull/4170 for main

docs(home): Updates featured Medium blogs on v5.

---

packages/documentation-framework/scripts/md/typecheck.js
packages/documentation-framework/scripts/webpack/prerender.js

V6 version of https://github.com/patternfly/patternfly-org/pull/4191

feat(docs-framework): Add support for next subpaths in react-charts

---

.github/release.sh

Reenabled releasing patternfly org documentation framework.

chore: Enable release for patternfly-org

---

packages/documentation-site/patternfly-docs/pages/landing-pages/components/components-data.json

docs(components): Updates descriptions for all components.

---

packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/content/get-started/release-notes-data.js
packages/documentation-site/patternfly-docs/content/get-started/release-notes-table.js
packages/documentation-site/patternfly-docs/content/get-started/release-notes.md
yarn.lock

Closes https://github.com/patternfly/patternfly-org/issues/3907
view it running on: https://patternfly-org-pr-4259-site.surge.sh/get-started/upgrade/release-notes

feat: add react breaking changes list to release notes

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/accordion/accordion.md
packages/documentation-site/patternfly-docs/content/design-guidelines/components/table/table.md
packages/documentation-site/patternfly-docs/content/design-guidelines/components/tree-view/tree-view.md

docs(design-guidelines): Clarifies table vs tree view vs accordion.

---

packages/documentation-framework/scripts/md/typecheck.js

Add default imports for new react-charts modules

Add default imports

---

packages/documentation-site/patternfly-docs/pages/landing-pages/components/components-data.json

docs(background-image): Updates description in header.

---

packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md

docs(release-highlights) Adds last updated date for each release.

---

packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md

docs(release-highlights): Adds 5.4 patch notes.

---

packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/patternfly-docs.config.js

Added code to allow component groups section.

fix: updated to allow compnonent groups section.

---

packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md

Update release highlights to include updates for react-charts
https://github.com/patternfly/patternfly-react/issues/11125

Update release highlights to include react-charts (v6)

---

.prettierignore
.prettierrc
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js

Closes #4281.
Also adds a .prettierrc that matches the react repo, and a .prettierignore to prevent it from running on anything other than js files (to avoid it messing with markdown files).

feat(site): update version switcher for v5

---

packages/documentation-site/patternfly-docs/content/get-started/upgrade.md

Closes #4347
Makes progress on https://github.com/patternfly/patternfly-org/issues/4345 (or maybe closes)
Also adds info from https://github.com/patternfly/patternfly/issues/6996

docs(upgrade): Updates upgrade instructions.

---

packages/documentation-site/patternfly-docs/content/get-started/develop.md

docs(develop): Adds information about breaking changes.

---

packages/documentation-framework/templates/mdx.js

Closes: https://github.com/patternfly/patternfly-org/issues/3490

fix: Update text to 'Edit this page on Github'

---

packages/documentation-site/patternfly-docs/content/get-started/upgrade.md

docs(upgrade): Fix anchor link.

---

packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js
packages/documentation-framework/templates/html.ejs

Reverting https://github.com/patternfly/patternfly-org/pull/4389 for now.

feat(dark theme): revert localstorage/pref feature

---

packages/documentation-framework/versions.json
packages/documentation-site/package.json
packages/documentation-site/patternfly-docs/patternfly-docs.source.js
scripts/latest-versions.sh
yarn.lock

Added patternfly extension react data view to patternfly org site.

Added react data view to patternfly org

---

yarn.lock

fixes broken `pr-preview / build-upload (pull_request_target)` CI:
➤ YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.

fix: Update yarn lockfile

---

packages/documentation-site/patternfly-docs/patternfly-docs.config.js

fix(analytics): update ID

---

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/spacers/spacers.md

docs(spacers): Fix px typo.

---

packages/documentation-framework/components/footer/footer.js
packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js

chore(PF Logos): updated accessible name of link logos

---

.github/workflows-src/partials/build.yml
.github/workflows/pr-preview.yml
.github/workflows/release.yml

chore(CI): Update actions/cache version

---

packages/documentation-site/patternfly-docs/content/tokens/design-with-tokens.md

docs(tokens): Fixes link on design with tokens page.

---

packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md

docs(typography): Updates size for h1 headings.

---

packages/documentation-framework/package.json
yarn.lock

This reverts commit 07ed7ae30789543204f8c8f5031c96e478164957.

Revert "feat(ver): enable react 19 support in framework (#4515)"

---

packages/documentation-framework/templates/mdx.css
packages/documentation-framework/templates/mdx.js

fixes https://github.com/patternfly/patternfly-org/issues/4548

fix(example): keeps example content from overflowing content area

---

packages/documentation-framework/package.json
yarn.lock

Reverts patternfly/patternfly-org#4582

Revert "chore(deps): Temporarily allow for React 19 peer dependency"

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/content/content.md
packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md

docs(typography): Adds guidance for line length.

---

yarn.lock

Causes dropdowns to break in Org due to mismatched versions.

fix(Lockfile): Remove PF deps from ChatBot

---

packages/documentation-site/patternfly-docs/content/design-guidelines/components/modal/modal.md

docs(modal): Updates design guidelines for v6.

---

packages/documentation-framework/hooks/useTheme.js

fix(theme): Set theme defaults to system if no value is stored
